import {expect,type Browser,type Page} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
import type {EventPackage} from '../../shared/types'
const evidence='/tmp/tongye-activity-user-evidence';mkdirSync(evidence,{recursive:true})
export async function close(page:Page){await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0)}
export async function tab(page:Page,name:string){await page.locator('.tabbar').getByRole('button',{name,exact:true}).click()}
export async function imageFixture(page:Page){await page.route('**/api/media/read?**',route=>route.fulfill({contentType:'image/png',body:readFileSync('examples/assets/convention-demo.png')}))}
export async function publishFixture(browser:Browser,suffix:string,base='http://localhost:5173'){const context=await browser.newContext(),page=await context.newPage();const pack=JSON.parse(readFileSync('examples/convention-demo.v2.json','utf8')) as EventPackage;pack.event.id=`ui-activity-${suffix}`;pack.event.title=`虚构活动视觉验收-${suffix}`;pack.event.extensions!.convention.pois[0].tags=['手作','角色','测试标签'];await imageFixture(page);await page.goto(base+'/admin');await page.getByLabel('管理员密码').fill('a'.repeat(64));await page.getByRole('button',{name:'进入管理'}).click();await page.getByRole('button',{name:'新建活动',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'导入或导出活动文件'}).click();await page.getByLabel('或粘贴 JSON').fill(JSON.stringify(pack));await page.getByRole('button',{name:'校验并使用'}).click();await page.getByRole('button',{name:'预览保存'}).click();await page.getByRole('button',{name:'确认保存'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await page.request.post(`http://localhost:8787/__e2e/seed-fixture?eventId=${pack.event.id}`)).status()).toBe(200);await page.getByRole('button',{name:new RegExp(pack.event.title)}).click();await page.getByRole('dialog').getByLabel('活动状态').selectOption('published');await page.getByRole('button',{name:'预览保存'}).click();await page.getByRole('button',{name:'确认保存'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.screenshot({path:`${evidence}/admin-${suffix}.png`});await context.close();return pack}
export async function enter(page:Page,pack:EventPackage,base='http://localhost:5173'){await imageFixture(page);await page.goto(base+'/');await page.getByRole('button',{name:new RegExp(pack.event.title)}).click();await expect(page.locator('.tabbar').getByRole('button',{name:'逛展',exact:true})).toBeVisible()}
export async function save(page:Page){const accepted=page.waitForResponse(r=>r.request().method()==='PUT'&&/\/personal\//.test(r.url()));await page.getByRole('button',{name:'保存个人计划',exact:true}).click();expect((await accepted).status()).toBe(200);await expect(page.locator('p[role=status]')).toContainText('已保存到云端')}
