import {test,expect} from '@playwright/test'
import {mkdirSync} from 'node:fs'
import {publishFixture,imageFixture,tab,close} from './activity-fixture'
import {download} from './ui-helpers'
const evidence='/tmp/tongye-browse-tools-evidence';mkdirSync(evidence,{recursive:true})
test('最近活动独立于小队；地图列表收藏过滤和公开地点分享不改变计划',async({browser})=>{
 test.setTimeout(90000);const pack=await publishFixture(browser,'browse-tools'),context=await browser.newContext({viewport:{width:390,height:900}}),page=await context.newPage();await imageFixture(page)
 await page.goto('/');await expect(page.getByRole('region',{name:'最近活动'})).toHaveCount(0);await page.getByRole('button',{name:new RegExp(pack.event.title)}).click()
 await expect(page.getByRole('group',{name:'活动地图，可平移与缩放'})).toBeVisible();await expect(page.getByRole('button',{name:'地图',exact:true})).toHaveAttribute('aria-pressed','true')
 await page.getByRole('button',{name:'仅收藏',exact:true}).click();await expect(page.locator('svg [data-poi]')).toHaveCount(0);await expect(page.getByText('暂无收藏',{exact:true})).toBeVisible();await page.getByRole('button',{name:'仅收藏',exact:true}).click()
 await page.getByRole('button',{name:'列表',exact:true}).click();await expect(page.getByRole('group',{name:'活动地图，可平移与缩放'})).not.toBeVisible();await page.locator('.sched-row').filter({hasText:'示例地点 A'}).click()
 await page.getByRole('dialog').getByRole('button',{name:'收藏',exact:true}).click();await expect.poll(()=>page.getByRole('dialog').getByRole('button',{name:'取消收藏',exact:true}).count()).toBe(1)
 await page.getByRole('dialog').getByRole('button',{name:'分享地点',exact:true}).click();const link=await page.getByLabel('地点链接').inputValue();expect(link).toBe(`${new URL(page.url()).origin}/events/${pack.event.id}?poi=poi-a`);expect(link).not.toMatch(/personal|personId|token|#|group/)
 const recipient=await browser.newContext(),recipientPage=await recipient.newPage();await imageFixture(recipientPage);await recipientPage.goto(link);await expect(recipientPage.getByRole('dialog',{name:'示例地点 A'})).toBeVisible();await recipient.close()
 await close(page);await page.getByRole('button',{name:'仅收藏',exact:true}).click();await expect(page.locator('.activity-place-pane .sched-row')).toHaveCount(1);await page.getByRole('button',{name:'地图',exact:true}).click();await expect(page.locator('svg [data-poi]')).toHaveCount(1);await expect(page.locator('svg [data-poi]')).toHaveAttribute('data-poi','poi-a')
 for(const width of [375,390,430]){await page.setViewportSize({width,height:900});for(const scheme of ['light','dark'] as const){await page.emulateMedia({colorScheme:scheme});await page.screenshot({path:`${evidence}/map-favorites-${width}-${scheme}.png`,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'列表',exact:true}).click();await page.screenshot({path:`${evidence}/list-favorites-${width}-${scheme}.png`,animations:'disabled'});await page.getByRole('button',{name:'地图',exact:true}).click()}}
 await tab(page,'我的');await page.getByRole('button',{name:'恢复与导出'}).click();const exported=JSON.parse(await download(page,'导出个人计划'));expect(exported.plan.response.busy).toEqual([]);expect(exported.plan.routes).toEqual([]);expect(exported.plan.favorites).toHaveLength(1);await close(page)
 await page.getByRole('button',{name:'返回活动列表'}).click();const recent=page.getByRole('region',{name:'最近活动'});await expect(recent.getByRole('button',{name:pack.event.title,exact:true})).toBeVisible();await expect(page.getByText('最近小队',{exact:true})).toHaveCount(0);await page.reload();await expect(recent.getByRole('button',{name:pack.event.title,exact:true})).toBeVisible();await recent.getByRole('button',{name:pack.event.title,exact:true}).click();await tab(page,'我的');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'移除此设备资料'}).click();await expect(page.getByRole('region',{name:'最近活动'})).toHaveCount(0);await context.close()
})
