import {API_BASE} from './api-base'
import { test, expect } from '@playwright/test'
import {mkdirSync} from 'node:fs'
import { download } from './ui-helpers'
test('管理员通过网页表单发布分钟场次并导出回读',async({page})=>{
 await page.goto('/admin');await page.getByLabel('管理员密码').fill('a'.repeat(64));await page.getByRole('button',{name:'进入管理'}).click();await page.getByRole('button',{name:'新建活动',exact:true}).click();const d=page.getByRole('dialog',{name:'编辑活动'});await d.getByLabel('活动名称',{exact:true}).fill('表单分钟验收');await d.getByLabel('活动类型').selectOption('generic');await d.getByLabel('开始日期').fill('2026-10-03');await d.getByLabel('结束日期').fill('2026-10-03');await d.getByRole('button',{name:'场次',exact:true}).click();await d.locator('button[aria-expanded]').filter({hasText:'活动场次'}).click();await d.getByRole('button',{name:'添加场次'}).click();await page.getByRole('dialog',{name:'编辑场次'}).getByLabel('场次名称').fill('分钟场次');await page.getByRole('dialog',{name:'编辑场次'}).getByLabel('开始时间').fill('13:07');await page.getByRole('dialog',{name:'编辑场次'}).getByLabel('结束时间').fill('13:52');await page.getByRole('button',{name:'完成场次'}).click();await d.getByLabel('活动状态').selectOption('published');await d.getByRole('button',{name:'预览保存'}).click();await page.getByRole('button',{name:'确认保存'}).click();await expect(page.getByRole('button',{name:/表单分钟验收/})).toBeVisible();await page.getByRole('button',{name:/表单分钟验收/}).click();await d.getByRole('button',{name:'导入或导出活动文件'}).click();const pack=JSON.parse(await download(page,'导出活动 JSON'));expect(pack.event.activities[0].sessions[0]).toMatchObject({start:'13:07',end:'13:52'});const publicly=await (await page.request.get(`${API_BASE}/api/v1/events`)).json();expect(publicly.data.some((e:{id:string})=>e.id===pack.event.id)).toBe(true);
})
for(const width of [375,390,430,1440])test(`管理员活动表单${width}失败草稿保留与键盘关闭`,async({browser})=>{
 const context=await browser.newContext({viewport:{width,height:900},colorScheme:width===390||width===1440?'dark':'light'}),page=await context.newPage();await page.goto('/admin');await page.getByLabel('管理员密码').fill('a'.repeat(64));await page.getByRole('button',{name:'进入管理'}).click();await page.getByRole('button',{name:'新建活动',exact:true}).click();const d=page.getByRole('dialog',{name:'编辑活动'});const name='长活动名'.repeat(18);await d.getByLabel('活动名称',{exact:true}).fill(name);await d.getByLabel('活动类型').selectOption('comic_convention');await d.getByRole('button',{name:'地图',exact:true}).click();await expect(d.getByText('先保存活动，再上传地图和标注通道。')).toBeVisible();await d.getByRole('button',{name:'活动信息',exact:true}).click();page.once('dialog',dialog=>dialog.accept());await d.getByLabel('活动类型').selectOption('generic');await d.getByRole('button',{name:'预览保存'}).click();await page.route('**/api/v1/admin/events',async route=>{if(route.request().method()==='POST')await route.abort('failed');else await route.continue()});await page.getByRole('button',{name:'确认保存'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('连接失败');await page.reload();await page.getByRole('button',{name:'新建活动',exact:true}).click();await expect(d.getByLabel('活动名称',{exact:true})).toHaveValue(name);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);mkdirSync('/tmp/tongye-activity-admin-evidence',{recursive:true});await d.getByLabel('活动类型').scrollIntoViewIfNeeded();await page.screenshot({path:`/tmp/tongye-activity-admin-evidence/activity-form-${width}.png`});await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await context.close()
})
