import {API_BASE} from './api-base'
import {test,expect} from '@playwright/test'
import {readFileSync,mkdirSync} from 'node:fs'
const evidence='/tmp/tongye-activity-admin-evidence';mkdirSync(evidence,{recursive:true})
for(const width of [375,390])test(`管理员${width}真实活动UI发布更新归档与退出撤销`,async({browser})=>{
 const context=await browser.newContext({viewport:{width,height:844}}),page=await context.newPage();await page.goto('/admin');await page.getByLabel('管理员密码').fill('a'.repeat(64));await page.getByRole('button',{name:'进入管理'}).click();await page.getByRole('button',{name:'新建活动',exact:true}).click();const pack=JSON.parse(readFileSync('examples/event-demo.json','utf8'));pack.event.id=`admin-ui-${width}`;pack.event.title=`管理员本地示例-${width}`;
 async function importPack(){await page.getByRole('dialog').getByRole('button',{name:'导入或导出活动文件'}).click();await page.getByLabel('或粘贴 JSON').fill(JSON.stringify(pack));await page.getByRole('button',{name:'校验并使用'}).click()}
 async function save(status:string){await page.getByRole('dialog').getByLabel('活动状态').selectOption(status);await page.getByRole('button',{name:'预览保存'}).click();await page.getByRole('button',{name:'确认保存'}).click();await expect(page.getByRole('dialog')).toHaveCount(0)}
 await importPack();await save('published');let published=(await (await page.request.get(`${API_BASE}/api/v1/events`)).json()).data.find((e:{id:string})=>e.id===pack.event.id);expect(published.revision).toBe(1);await page.getByRole('button',{name:new RegExp(pack.event.title)}).click();pack.event.activities[0].sessions[1].start='13:08';await importPack();await save('published');published=(await (await page.request.get(`${API_BASE}/api/v1/events`)).json()).data.find((e:{id:string})=>e.id===pack.event.id);expect(published.revision).toBe(2);expect(published.eventPackage.event.activities[0].sessions[1].start).toBe('13:08');await page.screenshot({path:`${evidence}/administrator-list-${width}.png`});await page.getByRole('button',{name:new RegExp(pack.event.title)}).click();await save('archived');published=(await (await page.request.get(`${API_BASE}/api/v1/events`)).json()).data.find((e:{id:string})=>e.id===pack.event.id);expect(published.status).toBe('archived');expect(published.revision).toBe(3);const session=await page.evaluate(()=>sessionStorage.getItem('coukong-admin'));await page.getByRole('button',{name:'退出登录',exact:true}).click();await expect(page.getByLabel('管理员密码')).toHaveValue('');expect((await page.request.get(`${API_BASE}/api/v1/admin/events`,{headers:{Authorization:`Bearer ${session}`}})).status()).toBe(401);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await context.close()
})
