import {API_BASE} from './api-base'
import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {randomUUID} from 'node:crypto'
import {adminSession} from './activity-fixture'
import type {EventPackage} from '../../shared/types'
// Isolated metadata/image fixture. Real admin UI writes use local Worker/D1;
// this is not an upload or production Blob availability test.
for(const reuse of [false,true])test(`地图换图先保存再校对${reuse?'，等比例坐标复用':''}`,async({page,request})=>{test.setTimeout(120000);
 const token='c'.repeat(64);await adminSession(request,token);const pack=JSON.parse(readFileSync('examples/convention-demo.v2.json','utf8')) as EventPackage;pack.event.id='map-transition-'+randomUUID();pack.event.title='换图门禁'+(reuse?'同比':'普通');const first=await request.post(`${API_BASE}/api/v1/admin/events`,{headers:{Authorization:'Bearer '+token},data:{eventPackage:pack,status:'draft',expectedRevision:0,operationId:randomUUID()}});expect(first.ok()).toBe(true);const rev=(await first.json()).data.revision;const next=structuredClone(pack),map=next.event.extensions!.convention.maps[0];map.revision++;map.assetKey='replacement-'+map.assetKey;map.needsReview=true;next.assetManifest![0].assetKey=map.assetKey;next.assetManifest![0].sha256='a'.repeat(64);if(reuse){for(const p of next.event.extensions!.convention.pois)if(p.position?.mapId===map.id)p.position.mapRevision=map.revision;for(const g of next.event.extensions!.convention.routingGraphs)if(g.mapId===map.id){g.mapRevision=map.revision;g.revision++}}
 await page.goto('/admin');await page.getByLabel('管理员密码').fill('a'.repeat(64));let login=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/admin/session'));await page.getByRole('button',{name:'进入管理'}).click();const loginStatus=(await login).status();expect([200,429]).toContain(loginStatus);if(loginStatus===429){await page.waitForTimeout(60000-Date.now()%60000+100);login=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/admin/session'));await page.getByRole('button',{name:'进入管理'}).click();expect((await login).status()).toBe(200)}await page.getByRole('button',{name:pack.event.title,exact:false}).click();await page.getByRole('button',{name:'导入或导出活动文件'}).click();await page.getByLabel('或粘贴 JSON').fill(JSON.stringify(next));await page.getByRole('button',{name:'校验并使用'}).click();let d=page.getByRole('dialog');await d.locator('button[aria-expanded]').filter({hasText:'地图与通道'}).click();await expect(d.getByRole('button',{name:'完成地图校对'})).toBeDisabled();await d.getByRole('button',{name:'预览保存'}).click();await page.getByRole('button',{name:'确认保存'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:pack.event.title,exact:false}).click();d=page.getByRole('dialog');await d.locator('button[aria-expanded]').filter({hasText:'地图与通道'}).click();if(!reuse){for(const p of next.event.extensions!.convention.pois.filter(p=>p.position?.mapId===map.id)){await d.getByRole('combobox',{name:'选择地点',exact:true}).selectOption(p.id);await d.getByRole('button',{name:'已核对此位置',exact:true}).click()}page.once('dialog',dialog=>dialog.accept());await d.getByRole('button',{name:'已核对通道节点'}).click()}await expect(d.getByRole('button',{name:'完成地图校对'})).toBeEnabled();page.once('dialog',dialog=>dialog.accept());await d.getByRole('button',{name:'完成地图校对'}).click();await d.getByRole('button',{name:'预览保存'}).click();await page.getByRole('button',{name:'确认保存'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);const current=await request.get(`${API_BASE}/api/v1/admin/events`,{headers:{Authorization:'Bearer '+token}});const actual=(await current.json()).data.find((v:{id:string})=>v.id===pack.event.id);expect(actual.revision).toBe(rev+2);expect(actual.eventPackage.event.extensions.convention.maps[0]).toMatchObject({revision:map.revision,needsReview:false});expect(actual.eventPackage.event.extensions.convention.pois[0].position).toMatchObject({x:pack.event.extensions!.convention.pois[0].position!.x,y:pack.event.extensions!.convention.pois[0].position!.y,mapRevision:map.revision});
})
