import {test,expect} from '@playwright/test'
import {mkdirSync} from 'node:fs'
const evidence='/tmp/tongye-meet-ui-refinement';mkdirSync(evidence,{recursive:true})
for(const width of [375,390])test(`新用户手机${width}邀请到分钟填写和三人结果`,async({browser})=>{
 const contexts=await Promise.all([browser.newContext({viewport:{width,height:844}}),browser.newContext({viewport:{width,height:844}}),browser.newContext({viewport:{width,height:844}})]);const [owner,a,b]=await Promise.all(contexts.map(c=>c.newPage()));
 await owner.goto('/create');await owner.getByLabel('小队标题').fill(`本地手机新用户-${width}`);await owner.getByLabel('站点创建码').fill('test-create');await owner.getByRole('button',{name:'确认创建',exact:true}).click();await expect(owner.getByRole('button',{name:'管理',exact:true})).toBeVisible();await owner.getByRole('button',{name:'管理',exact:true}).click();const invite=await owner.getByLabel('邀请链接').inputValue();
 for(const [page,name,start,end] of [[a,'手机A','13:07','13:52'],[b,'手机B','13:00','14:00']] as const){await page.goto(invite);await expect(page.getByLabel('怎么称呼')).toBeVisible();await page.getByLabel('怎么称呼').fill(name);await page.getByRole('button',{name:'加入小队',exact:true}).click();await expect(page.getByRole('heading',{name:'我的日程'})).toBeVisible();await page.getByRole('button',{name:'添加区间',exact:true}).first().click();await page.getByLabel('开始时间 1',{exact:true}).first().fill(start);await page.getByLabel('结束时间 1',{exact:true}).first().fill(end);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(page===a)await page.screenshot({path:`${evidence}/member-fill-${width}.png`,fullPage:true});await page.getByRole('button',{name:'提交',exact:true}).click();await expect(page.locator('p.muted').filter({hasText:'已提交'}).first()).toBeVisible()}
 await owner.getByRole('button',{name:'安排',exact:true}).click();await owner.getByLabel('怎么称呼').fill('手机发起人');await owner.getByRole('button',{name:'加入小队',exact:true}).click();await expect(owner.getByRole('heading',{name:'我的日程'})).toBeVisible();await owner.getByRole('button',{name:'全部开放时间可用'}).click();await owner.getByRole('button',{name:'提交',exact:true}).click();await expect(owner.locator('p.muted').filter({hasText:'已提交'}).first()).toBeVisible();await a.getByRole('button',{name:'共同空闲',exact:true}).click();await a.getByRole('button',{name:'刷新',exact:true}).click();await expect(a.getByText('3 人已加入，3 人已确认',{exact:true})).toBeVisible();await expect(a.getByText('13:07–13:52',{exact:true})).toBeVisible();expect(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await a.screenshot({path:`${evidence}/common-result-${width}.png`,fullPage:true});await Promise.all(contexts.map(c=>c.close()));
})
