import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
async function join(page:Page,link:string,name:string){await page.goto(link);await page.getByLabel('你的名字').fill(name);await page.getByRole('button',{name:'加入小队',exact:true}).click();await expect(page.getByRole('heading',{name:'我的可参与时间'})).toBeVisible()}
async function presence(page:Page,start:string,end:string){await page.getByRole('button',{name:'添加区间',exact:true}).first().click();await page.getByLabel('开始时间 1',{exact:true}).first().fill(start);await page.getByLabel('结束时间 1',{exact:true}).first().fill(end)}
async function submit(page:Page){await page.getByRole('button',{name:'确认提交',exact:true}).click();await expect(page.getByText('已提交，其他成员现在可以看到',{exact:false})).toBeVisible()}
async function downloaded(page:Page,button:string){const promise=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const d=await promise;return readFileSync((await d.path())!,'utf8')}

test('三个独立身份：真实D1、分钟、状态、导入、离线与并发',async({browser})=>{
 const contexts=await Promise.all([browser.newContext(),browser.newContext(),browser.newContext()]);const [owner,a,b]=await Promise.all(contexts.map(c=>c.newPage()));
 await owner.goto('/create');await owner.getByLabel('小队标题').fill('本地真实三人验收');await owner.getByLabel('开始时间 1',{exact:true}).fill('09:00');await owner.getByLabel('结束时间 1',{exact:true}).fill('18:00');await owner.getByLabel('站点创建码').fill('test-create');await owner.getByRole('button',{name:'确认创建',exact:true}).click();await expect(owner.getByRole('heading',{name:'本地真实三人验收'})).toBeVisible();await owner.getByRole('button',{name:'管理',exact:true}).click();const invite=await owner.getByLabel('邀请链接').inputValue();
 await join(a,invite,'A');await join(b,invite,'B');await owner.getByRole('button',{name:'安排',exact:true}).click();await owner.getByLabel('你的名字').fill('发起人');await owner.getByRole('button',{name:'加入小队',exact:true}).click();await expect(owner.getByRole('heading',{name:'我的可参与时间'})).toBeVisible();await owner.getByRole('button',{name:'明确选择全部开放时间可用'}).click();await submit(owner);
 await owner.getByRole('button',{name:'共同空闲',exact:true}).click();await owner.getByRole('button',{name:'刷新',exact:true}).click();await expect(owner.getByText(/等待.*A.*B.*确认/)).toBeVisible();
 await presence(a,'09:00','12:00');await a.getByLabel('个人忙碌缓冲（分钟）').fill('5');await a.getByRole('button',{name:'添加忙碌安排'}).click();await a.getByLabel('开始时间 1',{exact:true}).nth(1).fill('10:07');await a.getByLabel('结束时间 1',{exact:true}).nth(1).fill('10:22');await a.getByLabel('私密备注').fill('只有A可读的私密备注');await submit(a);
 await presence(b,'09:15','11:50');await b.getByRole('button',{name:'添加忙碌安排'}).click();await b.getByLabel('开始时间 1',{exact:true}).nth(1).fill('09:40');await b.getByLabel('结束时间 1',{exact:true}).nth(1).fill('09:55');await submit(b);
 await owner.getByRole('button',{name:'刷新',exact:true}).click();await owner.getByLabel('最短时长（分钟）').fill('5');for(const time of ['09:15–09:40','09:55–10:02','10:27–11:50'])await expect(owner.getByText(time,{exact:true})).toBeVisible();await expect(owner.getByText('只有A可读的私密备注')).toHaveCount(0);await owner.getByLabel('最短时长（分钟）').fill('15');await expect(owner.getByText('09:55–10:02',{exact:true})).toHaveCount(0);
 await a.getByRole('button',{name:'添加忙碌安排'}).click();await a.getByLabel('快捷选择步长').selectOption('5');await submit(a);await a.reload();await expect(a.getByLabel('开始时间 1',{exact:true}).nth(2)).toHaveValue('13:07');await expect(a.getByLabel('结束时间 1',{exact:true}).nth(2)).toHaveValue('13:52');const personal=JSON.parse(await downloaded(a,'导出个人安排'));expect(personal.response.busy[1].start).toBe('13:07');expect(personal.response.busy[1].end).toBe('13:52');
 // Restore same capability in a fourth independent browser, then race stale UI revisions.
 await a.getByRole('button',{name:'成员',exact:true}).click();const recovery=await downloaded(a,'保存我的恢复链接');const duplicateContext=await browser.newContext();const duplicate=await duplicateContext.newPage();await duplicate.goto(recovery);await expect(duplicate.getByRole('heading',{name:'我的可参与时间'})).toBeVisible();await a.getByRole('button',{name:'安排',exact:true}).click();await a.getByLabel('名字',{exact:true}).fill('A更新');await submit(a);await duplicate.getByLabel('名字',{exact:true}).fill('A冲突草稿');await duplicate.getByRole('button',{name:'确认提交',exact:true}).click();await expect(duplicate.getByText('未提交成功，草稿保留。版本冲突时请先刷新比较。')).toBeVisible();
 await contexts[1].setOffline(true);await a.getByLabel('名字',{exact:true}).fill('A离线草稿');await a.getByRole('button',{name:'确认提交',exact:true}).click();await expect(a.getByText('未提交成功，草稿保留。版本冲突时请先刷新比较。')).toBeVisible();await contexts[1].setOffline(false);await a.reload();await expect(a.getByLabel('名字',{exact:true})).toHaveValue('A离线草稿');
 await owner.getByRole('button',{name:'管理',exact:true}).click();const pack=JSON.parse(readFileSync('examples/event-demo.json','utf8'));await owner.getByLabel('或粘贴 JSON').fill(JSON.stringify(pack));await owner.getByRole('button',{name:'校验并预览',exact:true}).click();await expect(owner.getByRole('button',{name:'确认原子导入'})).toBeVisible();await owner.getByRole('button',{name:'确认原子导入'}).click();await owner.getByRole('button',{name:'成员',exact:true}).click();await expect(owner.getByText(/B · 需要重新确认/)).toBeVisible();await owner.getByRole('button',{name:'管理',exact:true}).click();const exported=JSON.parse(await downloaded(owner,'导出活动 JSON'));expect(exported).toEqual(pack);expect(JSON.stringify(exported)).not.toContain('只有A可读');
 await b.getByRole('button',{name:'刷新',exact:true}).click();b.once('dialog',dialog=>dialog.accept());await b.getByRole('button',{name:'已核对当前活动，允许重新提交'}).click();await expect(b.getByText('已核对当前活动，请再次点击确认提交',{exact:false})).toBeVisible();await b.getByLabel('2026-10-03 13:07–13:52',{exact:false}).check();await submit(b);const changed=structuredClone(pack);changed.event.activities[0].sessions[1].start='13:08';await owner.getByLabel('或粘贴 JSON').fill(JSON.stringify(changed));await owner.getByRole('button',{name:'校验并预览',exact:true}).click();await owner.getByRole('button',{name:'确认原子导入'}).click();await b.getByRole('button',{name:'刷新',exact:true}).click();await expect(b.getByText(/保留原安排 2026-10-03 13:07–13:52/)).toBeVisible();await owner.getByLabel('主题').selectOption('dark');await expect(owner.locator('html')).toHaveAttribute('data-theme','dark');await contexts[0].grantPermissions([]);await owner.emulateMedia({reducedMotion:'reduce'});await owner.keyboard.press('Tab');expect(await owner.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');
 for(const width of [375,390,430,1440]){await owner.setViewportSize({width,height:900});expect(await owner.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 await duplicateContext.close();await Promise.all(contexts.map(c=>c.close()));
})

test('站内帮助与真实示例下载',async({page})=>{await page.goto('/help/');await expect(page.locator('body')).toContainText('邀请');const response=await page.request.get('/examples/event-demo.json');expect(response.status()).toBe(200);expect(await response.text()).toBe(readFileSync('examples/event-demo.json','utf8'));await page.goto('/help/event-json/');await expect(page.locator('body')).toContainText('JSON')})

test('旧本机原文保护、首屏hydration与静态入口',async({page})=>{
 const raw=JSON.stringify({state:{profile:{name:'旧本人'},bookings:[{day:'10-03',start:'13:07',end:'13:52',title:'旧安排'}],friends:[{name:'旧朋友'}]},version:0});
 await page.addInitScript(value=>localStorage.setItem('coukong',value),raw);await page.goto('/');
 await expect(page.getByRole('button',{name:'下载旧数据原文'})).toBeVisible();expect(await downloaded(page,'下载旧数据原文')).toBe(raw);
 expect(await page.evaluate(()=>localStorage.getItem('coukong'))).toBe(raw);await expect(page.getByRole('button',{name:'小队 →'})).toHaveCount(0);
})
