import {field} from './ui-helpers'
import { test, expect, type Page } from '@playwright/test'
import { build, preview, type PreviewServer } from 'vite'
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
let server:PreviewServer
const output=mkdtempSync(join(tmpdir(),'coukong-pwa-e2e-'))
test.beforeAll(async()=>{process.env.VITE_API_URL='http://localhost:8787';await build({build:{outDir:output,emptyOutDir:false},logLevel:'warn'});server=await preview({build:{outDir:output},preview:{host:'127.0.0.1',port:5174,strictPort:true},logLevel:'warn'})},120000)
test.afterAll(async()=>{await new Promise<void>(resolve=>server?.httpServer.close(()=>resolve()));console.log(`Production PWA test build retained at ${output}`)})
async function create(owner:Page){await owner.goto('http://localhost:5174/create');await owner.getByLabel('小队标题').fill('离线刷新回归');await owner.getByLabel('站点创建码').fill('test-create');await owner.getByRole('button',{name:'确认创建',exact:true}).click();await expect(owner.getByRole('button',{name:'管理',exact:true})).toBeVisible();await owner.getByRole('button',{name:'管理',exact:true}).click();return await owner.getByLabel('邀请链接').inputValue()}
async function joinMember(page:Page,link:string){await page.goto(link);await page.getByLabel('怎么称呼').fill('离线成员');await page.getByRole('button',{name:'加入小队',exact:true}).click();await expect(page.getByRole('heading',{name:'我的日程'})).toBeVisible();await page.getByRole('button',{name:'添加区间',exact:true}).first().click();await page.getByLabel('开始时间 1',{exact:true}).first().fill('13:07');await page.getByLabel('结束时间 1',{exact:true}).first().fill('13:52');await page.getByRole('button',{name:'提交',exact:true}).click();await expect(page.locator('p.muted').filter({hasText:'已提交'}).first()).toBeVisible()}

test('生产SW真实离线刷新恢复草稿，重连活动版本变化拒绝旧草稿',async({browser})=>{
 const ownerContext=await browser.newContext(),memberContext=await browser.newContext();const owner=await ownerContext.newPage(),member=await memberContext.newPage();const link=await create(owner);await joinMember(member,link);
 await member.evaluate(async()=>{await navigator.serviceWorker.ready});await member.reload();await expect((await field(member,'怎么称呼'))).toHaveValue('离线成员');expect(await member.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
 await memberContext.setOffline(true);await (await field(member,'怎么称呼')).fill('离线修改保留');await expect(member.locator('p.muted').filter({hasText:'未提交'}).first()).toBeVisible();await member.reload();await expect((await field(member,'怎么称呼'))).toHaveValue('离线修改保留');await expect(member.getByLabel('开始时间 1',{exact:true}).first()).toHaveValue('13:07');await expect(member.getByLabel('结束时间 1',{exact:true}).first()).toHaveValue('13:52');
 const exportedPromise=owner.waitForEvent('download');await owner.getByRole('button',{name:'导出活动 JSON'}).click();const exported=await exportedPromise;const {readFileSync}=await import('node:fs');const pack=JSON.parse(readFileSync((await exported.path())!,'utf8'));pack.event.days[0].openIntervals[0].end='19:00';await (await field(owner,'或粘贴 JSON')).fill(JSON.stringify(pack));await owner.getByRole('button',{name:'预览',exact:true}).click();await owner.getByRole('button',{name:'确认导入'}).click();
 await memberContext.setOffline(false);await member.getByRole('button',{name:'刷新',exact:true}).click();await expect(member.getByRole('button',{name:'已核对当前活动，允许重新提交'})).toBeVisible();const responsePromise=member.waitForResponse(r=>r.request().method()==='PUT'&&r.url().includes('/response'));await member.getByRole('button',{name:'提交',exact:true}).click();expect((await responsePromise).status()).toBe(409);await expect((await field(member,'怎么称呼'))).toHaveValue('离线修改保留');await expect(member.locator('p.muted').filter({hasText:'未提交'}).first()).toBeVisible();await member.reload();await expect((await field(member,'怎么称呼'))).toHaveValue('离线修改保留');
 await ownerContext.close();await memberContext.close();
})

test('慢PUT期间新编辑保留，交错小队与结果版本拒绝混合刷新',async({browser})=>{
 const ownerContext=await browser.newContext({serviceWorkers:'block'}),memberContext=await browser.newContext({serviceWorkers:'block'});const owner=await ownerContext.newPage(),member=await memberContext.newPage();const link=await create(owner);await joinMember(member,link);
 let release!:()=>void,arrived!:()=>void;const waiting=new Promise<void>(resolve=>release=resolve),seen=new Promise<void>(resolve=>arrived=resolve);await member.route('**/members/*/response',async route=>{if(route.request().method()==='PUT'){arrived();await waiting}await route.continue()});await (await field(member,'怎么称呼')).fill('慢请求提交内容');await member.getByRole('button',{name:'提交',exact:true}).click();await seen;await (await field(member,'怎么称呼')).fill('提交中继续编辑');await expect(member.locator('p.muted').filter({hasText:'未提交'}).first()).toBeVisible();const delayedResponse=member.waitForResponse(r=>r.url().endsWith('/response')&&r.request().method()==='PUT');release();expect((await delayedResponse).status()).toBe(200);await expect(member.getByRole('button',{name:'提交',exact:true})).toBeEnabled();await expect(member.locator('p.muted').filter({hasText:'未提交'}).first()).toBeVisible();await member.reload();await expect((await field(member,'怎么称呼'))).toHaveValue('提交中继续编辑');await member.unroute('**/members/*/response');await member.getByRole('button',{name:'提交',exact:true}).click();await expect(member.locator('p.muted').filter({hasText:'已提交'}).first()).toBeVisible();
 const availabilityPromise=member.waitForResponse(r=>r.url().endsWith('/availability')&&r.request().method()==='GET');await member.getByRole('button',{name:'刷新',exact:true}).click();const stale=await (await availabilityPromise).json();const downloadPromise=owner.waitForEvent('download');await owner.getByRole('button',{name:'导出活动 JSON'}).click();const download=await downloadPromise;const {readFileSync}=await import('node:fs');const pack=JSON.parse(readFileSync((await download.path())!,'utf8'));pack.event.days[0].openIntervals[0].end='18:00';await (await field(owner,'或粘贴 JSON')).fill(JSON.stringify(pack));await owner.getByRole('button',{name:'预览',exact:true}).click();await owner.getByRole('button',{name:'确认导入'}).click();await expect(owner.getByRole('button',{name:'确认导入'})).toHaveCount(0);
 await member.route('**/availability',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(stale)}));await member.getByRole('button',{name:'刷新',exact:true}).click();await expect(member.getByRole('alert').filter({hasText:'活动资料正在更新，请稍后刷新'})).toBeVisible();await expect(member.getByText('开放：13:00–20:00',{exact:true})).toBeVisible();await expect(member.getByText('开放：13:00–18:00',{exact:true})).toHaveCount(0);
 await ownerContext.close();await memberContext.close();
})
