import {test,expect} from '@playwright/test'
import {API_BASE} from './api-base'
import {tab} from './activity-fixture'
import {randomUUID} from 'node:crypto'
import {readFileSync} from 'node:fs'
import type {EventPackage} from '../../shared/types'
async function privateActivity(page:import('@playwright/test').Page){await page.goto('/create?personal=1');await page.getByLabel('活动名称').fill('个人与管理权隔离'+randomUUID().slice(0,6));await page.getByLabel('站点创建码').fill('test-create');await page.getByRole('button',{name:'确认创建',exact:true}).click();await expect(page).toHaveURL(/\/events\//);return new URL(page.url()).pathname.split('/')[2]}
test('建队丢响应后改标题和码仍重放原body，保留当前表单和原管理能力',async({page})=>{const id=await privateActivity(page),bodies:Record<string,unknown>[]=[];let group='';await page.route('**/api/v1/groups',async route=>{bodies.push(route.request().postDataJSON());if(bodies.length===1){const res=await route.fetch();expect(res.status()).toBe(200);group=(await res.json()).data.id;await route.abort('failed')}else await route.continue()});await tab(page,'同行');await page.getByRole('button',{name:'创建小队',exact:true}).click();await page.getByLabel('小队标题').fill('原小队');await page.getByLabel('站点创建码').fill('test-create');await page.getByRole('button',{name:'确认创建',exact:true}).click();await expect(page.getByRole('alert')).toContainText('连接失败');await page.getByLabel('小队标题').fill('当前表单');await page.getByLabel('站点创建码').fill('wrong-current-code');await page.getByRole('button',{name:'确认创建',exact:true}).click();await expect(page.getByRole('alert')).toContainText('上次创建的小队已恢复');expect(bodies[1]).toEqual(bodies[0]);await expect(page.getByLabel('小队标题')).toHaveValue('当前表单');await expect(page).toHaveURL(new RegExp('/events/'+id));const caps=await page.evaluate(async()=>{const path='/src/online/storage.ts',s=await import(path);return s.readLocal('capabilities')});expect(caps).toEqual(expect.arrayContaining([expect.objectContaining({groupId:group,role:'manager',token:bodies[0].managerToken}),expect.objectContaining({groupId:group,role:'invite',token:bodies[0].inviteToken})]))})
test('删除个人计划保留独立owner和活动编辑入口',async({page})=>{const id=await privateActivity(page);await tab(page,'我的');await page.getByRole('button',{name:'恢复与导出',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'删除云端个人记录',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'编辑活动资料',exact:true})).toBeVisible();const state=await page.evaluate(async id=>{const path='/src/online/storage.ts',s=await import(path);return{owner:await s.readLocal('activity-owner:'+id),cap:await s.readLocal('activity-cap:'+id),plan:await s.readLocal('activity-personal:'+id)}},id);expect(state.owner).toMatchObject({token:expect.any(String)});expect(state.cap).toBeUndefined();expect(state.plan).toBeUndefined();await page.reload();await tab(page,'我的');await expect(page.getByRole('button',{name:'编辑活动资料',exact:true})).toBeVisible()})
test('空称呼客户端拒绝且明确400旧pending允许纠正',async({page,request})=>{const token='d'.repeat(64);await request.post(API_BASE+'/api/v1/admin/session',{data:{rootToken:'a'.repeat(64),sessionToken:token}});const pack=JSON.parse(readFileSync('examples/event-minimal.json','utf8')) as EventPackage;pack.event.id='name-fix-'+randomUUID();expect((await request.post(API_BASE+'/api/v1/admin/events',{headers:{Authorization:'Bearer '+token},data:{eventPackage:pack,status:'published',expectedRevision:0,operationId:randomUUID()}})).ok()).toBe(true);await page.goto('/events/'+pack.event.id+'?view=me');await page.getByLabel('个人称呼').fill('');await tab(page,'计划');await page.getByRole('button',{name:'保存个人计划',exact:true}).click();await expect(page.getByRole('alert')).toContainText('称呼');await page.evaluate(async id=>{const path='/src/online/storage.ts',s=await import(path),token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''),operationId=crypto.randomUUID();await s.writeLocal('activity-cap:'+id,{eventId:id,token,operationId});await s.writeLocal('activity-personal-create:'+id,{personalToken:token,operationId,name:''})},pack.event.id);await page.reload();await tab(page,'我的');await page.getByLabel('个人称呼').fill('已更正');await tab(page,'计划');await page.getByRole('button',{name:'保存个人计划',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'保存个人计划',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'已保存到云端'})).toBeVisible()})
