import { describe,it,expect,beforeAll,afterAll } from 'vitest'
import { Miniflare, convertV4MiniflareOptions } from 'miniflare'
import { build } from 'esbuild'
import { readFileSync } from 'node:fs'
import { randomBytes,randomUUID,createHash } from 'node:crypto'
let mf:Miniflare
const token=()=>randomBytes(32).toString('hex')
const adminRoot=token();const manager=token(),invite=token(),a=token(),b=token();let group:string,memberA:string,memberB:string
const pkg=JSON.parse(readFileSync('examples/event-demo.json','utf8'));pkg.event.days[0].openIntervals=[{start:'09:00',end:'12:00'}];pkg.event.activities=[]
async function api(path:string,method='GET',auth='',body?:unknown){const res=await mf.dispatchFetch('http://localhost/api/v1'+path,{method,headers:{...(auth?{Authorization:'Bearer '+auth}:{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:res.status,...await res.json() as any}}
const response=(name:string,presenceStart:string,busy:any[],bufferMinutes:number)=>({name,presence:[{date:'2026-10-03',intervals:[{start:presenceStart,end:name==='B'?'11:50':'12:00'}]}],busy,bufferMinutes})
beforeAll(async()=>{const built=await build({entryPoints:['worker/src/index.ts'],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'});mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-09-01',d1Databases:['DB'],bindings:{CREATION_MODE:'invite',CREATION_CODE:'test-create',ADMIN_ROOT_SECRET:adminRoot,ALLOWED_ORIGINS:'http://localhost:5173',BUILD_VERSION:'integration'}}));const db=await mf.getD1Database('DB');for(const migration of ['0001_initial.sql','0002_audit.sql','0003_operation_ownership.sql','0004_management_idempotency.sql'])await db.exec(readFileSync('worker/migrations/'+migration,'utf8').replace(/\n/g,' '))},30000)
afterAll(async()=>{await mf?.dispose()})
describe.sequential('真实 workerd / SQLite D1 多人闭环',()=>{
 it('创建保护，创建响应丢失安全重试',async()=>{expect((await api('/groups','POST','',{eventPackage:pkg,managerToken:manager,inviteToken:invite,operationId:randomUUID(),creationCode:'wrong'})).status).toBe(403);const body={eventPackage:pkg,managerToken:manager,inviteToken:invite,operationId:randomUUID(),creationCode:'test-create'};const first=await api('/groups','POST','',body);expect(first.status).toBe(200);group=first.data.id;expect((await api('/groups','POST','',body)).data.id).toBe(group);expect((await api('/groups','POST','',{...body,eventPackage:{...pkg,event:{...pkg.event,title:'不同内容'}}})).status).toBe(409)})
 it('两名同名成员独立加入，邀请不可读取私人回复',async()=>{const joinA={name:'同名',memberToken:a,operationId:randomUUID()};const A=await api(`/groups/${group}/join`,'POST',invite,joinA);expect(A.status).toBe(200);memberA=A.data.id;expect((await api(`/groups/${group}/join`,'POST',invite,joinA)).data.id).toBe(memberA);expect((await api(`/groups/${group}/join`,'POST',invite,{...joinA,name:'不同内容'})).status).toBe(409);const B=await api(`/groups/${group}/join`,'POST',invite,{name:'同名',memberToken:b,operationId:randomUUID()});memberB=B.data.id;expect(memberA).not.toBe(memberB);expect((await api(`/groups/${group}/members/${memberA}/response`,'GET',invite)).status).toBe(403);expect((await api(`/groups/${group}/availability`,'GET',a)).data.members.every((m:any)=>m.status==='unsubmitted'&&m.availability.length===0)).toBe(true)})
 it('精确提交、隐私裁剪、幂等和并发只有一份成功',async()=>{const founderToken=token();const founder=await api(`/groups/${group}/join`,'POST',invite,{name:'发起人',memberToken:founderToken,operationId:randomUUID()});expect((await api(`/groups/${group}/members/${founder.data.id}/response`,'PUT',founderToken,{expectedRevision:0,scheduleRevision:0,operationId:randomUUID(),response:response('发起人','09:00',[],0)})).status).toBe(200);const body={expectedRevision:0,scheduleRevision:0,operationId:randomUUID(),response:response('A','09:00',[{id:'private',date:'2026-10-03',start:'10:07',end:'10:22',title:'秘密标题',note:'秘密备注',source:'manual'}],5)};expect((await api(`/groups/${group}/members/${memberA}/response`,'PUT',a,body)).status).toBe(200);expect((await api(`/groups/${group}/members/${memberA}/response`,'PUT',a,body)).data.member.revision).toBe(1);expect((await api(`/groups/${group}/members/${memberA}/response`,'PUT',b,body)).status).toBe(403);expect((await api(`/groups/${group}/members/${memberA}/response`,'GET',manager)).status).toBe(403);const writes=await Promise.all([1,2].map(()=>api(`/groups/${group}/members/${memberB}/response`,'PUT',b,{expectedRevision:0,scheduleRevision:0,operationId:randomUUID(),response:response('B','09:15',[{id:'busy',date:'2026-10-03',start:'09:40',end:'09:55',title:'私事',source:'manual'}],0)})));expect(writes.map(x=>x.status).sort()).toEqual([200,409]);const db=await mf.getD1Database('DB');expect((await db.prepare('SELECT count(*) AS total FROM operations WHERE scope=?').bind(createHash('sha256').update(b).digest('hex')+':'+memberB).first<any>())!.total).toBe(1);expect((await api(`/groups/${group}/members/${memberA}/response`,'PUT',a,{...body,response:{...body.response,name:'篡改'}})).status).toBe(409);const result=await api(`/groups/${group}/availability`,'GET',a);expect(JSON.stringify(result)).not.toMatch(/秘密|私事|token/);expect(result.data.members.find((m:any)=>m.id===memberA).availability).toEqual([{date:'2026-10-03',start:'09:00',end:'10:02'},{date:'2026-10-03',start:'10:27',end:'12:00'}])})
 it('JSON分钟保存回读、失败不部分写入、活动变更使旧确认失效',async()=>{const demo=JSON.parse(readFileSync('examples/event-demo.json','utf8'));const importBody={eventPackage:demo,expectedRevision:0,operationId:randomUUID()};const imported=await api(`/groups/${group}/event-import/commit`,'POST',manager,importBody);expect((await api(`/groups/${group}/event-import/commit`,'POST',manager,importBody)).data.revision).toBe(1);expect((await api(`/groups/${group}/event-import/commit`,'POST',manager,{...importBody,eventPackage:{...demo,event:{...demo.event,title:'不同内容'}}})).status).toBe(409);expect(imported.status).toBe(200);expect(imported.data.scheduleRevision).toBe(1);expect((await api(`/groups/${group}/event-export`,'GET',a)).data.event.activities[0].sessions[1].start).toBe('13:07');expect((await api(`/groups/${group}/availability`,'GET',a)).data.members.every((m:any)=>m.status==='needs_review'&&m.availability.length===0)).toBe(true);const invalid=structuredClone(demo);invalid.event.activities[0].sessions[1].end='13:00';expect((await api(`/groups/${group}/event-import/commit`,'POST',manager,{eventPackage:invalid,expectedRevision:1,operationId:randomUUID()})).status).toBe(400);expect((await api(`/groups/${group}`,'GET',manager)).data.revision).toBe(1);expect((await api(`/groups/${group}/members/${memberA}/response`,'PUT',a,{expectedRevision:1,scheduleRevision:0,operationId:randomUUID(),response:response('A','09:00',[],0)})).status).toBe(409)})
 it('管理员真实会话鉴权，模板版本不可变，公共访问不含秘密',async()=>{const session=token();expect((await api('/admin/templates','GET',manager)).status).toBe(401);expect((await api('/admin/session','POST','',{rootSecret:adminRoot,sessionToken:session})).status).toBe(200);const templateBody={eventPackage:pkg,expectedRevision:0,published:true,operationId:randomUUID()};const template=await api('/admin/templates','POST',session,templateBody);expect((await api('/admin/templates','POST',session,templateBody)).data.revision).toBe(1);expect((await api('/admin/templates','POST',session,{...templateBody,published:false})).status).toBe(409);expect(template.status).toBe(200);expect((await api('/templates')).data.some((t:any)=>t.id===pkg.event.id)).toBe(true);expect((await api('/admin/templates','POST',session,{eventPackage:pkg,expectedRevision:0,published:true,operationId:randomUUID()})).status).toBe(409);expect((await api('/admin/session','DELETE',session)).status).toBe(200);expect((await api('/admin/templates','GET',session)).status).toBe(401)})
 it('模板最新公开状态：下架不复活旧版本，历史与小队快照不变',async()=>{
  const session=token();await api('/admin/session','POST','',{rootSecret:adminRoot,sessionToken:session});const pack=structuredClone(pkg);pack.event.id='template-state-test';
  const snapshot=await api(`/groups/${group}/event-export`,'GET',manager);
  expect((await api('/admin/templates','POST',session,{eventPackage:pack,expectedRevision:0,published:true,operationId:randomUUID()})).status).toBe(200);
  pack.event.title='新版模板';expect((await api('/admin/templates','POST',session,{eventPackage:pack,expectedRevision:1,published:false,operationId:randomUUID()})).status).toBe(200);
  expect((await api('/templates')).data.filter((t:any)=>t.id===pack.event.id)).toHaveLength(0);
  expect((await api('/admin/templates','GET',session)).data.filter((t:any)=>t.id===pack.event.id).map((t:any)=>[t.revision,t.published])).toEqual([[2,false]]);
  expect((await api(`/groups/${group}/event-export`,'GET',manager)).data).toEqual(snapshot.data);
  expect((await api('/admin/templates','POST',session,{eventPackage:pack,expectedRevision:2,published:true,operationId:randomUUID()})).status).toBe(200);
  expect((await api('/templates')).data.filter((t:any)=>t.id===pack.event.id).map((t:any)=>t.revision)).toEqual([3]);
  const db=await mf.getD1Database('DB');expect((await db.prepare('SELECT revision,published FROM templates WHERE id=? ORDER BY revision').bind(pack.event.id).all<any>()).results).toEqual([{revision:1,published:1},{revision:2,published:0},{revision:3,published:1}]);
  await api('/admin/session','DELETE',session);
 })
 it('时区变更与首次成员确认竞态只能一个成功',async()=>{const m=token(),inv=token(),self=token();const created=await api('/groups','POST','',{eventPackage:pkg,managerToken:m,inviteToken:inv,operationId:randomUUID(),creationCode:'test-create'});const gid=created.data.id;const joined=await api(`/groups/${gid}/join`,'POST',inv,{memberToken:self,name:'竞态成员',operationId:randomUUID()});const changed=structuredClone(pkg);changed.event.timezone='Asia/Tokyo';const results=await Promise.all([api(`/groups/${gid}/event-import/commit`,'POST',m,{eventPackage:changed,expectedRevision:0,operationId:randomUUID()}),api(`/groups/${gid}/members/${joined.data.id}/response`,'PUT',self,{expectedRevision:0,scheduleRevision:0,operationId:randomUUID(),response:response('竞态成员','09:00',[],0)})]);expect(results.filter(x=>x.status===200)).toHaveLength(1);expect(results.filter(x=>[403,409].includes(x.status))).toHaveLength(1)})
 it('隔离小队、撤销邀请和移除成员后token失效',async()=>{const second=await api('/groups','POST','',{eventPackage:pkg,managerToken:token(),inviteToken:token(),operationId:randomUUID(),creationCode:'test-create'});expect((await api(`/groups/${second.data.id}`,'GET',a)).status).toBe(401);const rotation={inviteToken:token(),expectedRevision:1,operationId:randomUUID()};expect((await api(`/groups/${group}/invite/rotate`,'POST',manager,rotation)).status).toBe(200);expect((await api(`/groups/${group}/invite/rotate`,'POST',manager,rotation)).data.revision).toBe(2);expect((await api(`/groups/${group}/invite/rotate`,'POST',manager,{...rotation,inviteToken:token()})).status).toBe(409);expect((await api(`/groups/${group}`,'GET',invite)).status).toBe(401);expect((await api(`/groups/${group}/members/${memberB}`,'DELETE',manager)).status).toBe(200);expect((await api(`/groups/${group}`,'GET',b)).status).toBe(401);const db=await mf.getD1Database('DB');expect((await db.prepare('SELECT count(*) AS total FROM operations WHERE member_id=?').bind(memberB).first<any>())!.total).toBe(0);const closeBody={status:'closed',expectedRevision:2,operationId:randomUUID()};expect((await api(`/groups/${group}`,'PATCH',manager,closeBody)).status).toBe(200);expect((await api(`/groups/${group}`,'PATCH',manager,closeBody)).data.revision).toBe(3);expect((await api(`/groups/${group}`,'PATCH',manager,{...closeBody,status:'open'})).status).toBe(409);expect((await api(`/groups/${group}/members/${memberA}/response`,'PUT',a,{expectedRevision:1,scheduleRevision:1,operationId:randomUUID(),response:response('A','09:00',[],0)})).status).toBe(409);const deleteBody={confirm:group,expectedRevision:3,operationId:randomUUID()};expect((await api(`/groups/${group}`,'DELETE',manager,deleteBody)).status).toBe(200);expect((await api(`/groups/${group}`,'DELETE',manager,deleteBody)).data.deleted).toBe(true);expect((await api(`/groups/${group}`,'DELETE',manager,{...deleteBody,expectedRevision:4})).status).toBe(409);expect((await api(`/groups/${group}`,'GET',a)).status).toBe(404);expect((await db.prepare('SELECT count(*) AS total FROM operations WHERE group_id=?').bind(group).first<any>())!.total).toBe(0)})
})
