import { beforeAll,afterAll,describe,it,expect } from 'vitest'
import { Miniflare,convertV4MiniflareOptions } from 'miniflare'
import { build } from 'esbuild'
import { readFileSync,readdirSync } from 'node:fs'
import { randomBytes,randomUUID } from 'node:crypto'
let mf:Miniflare,event:any,person:any,latest:any,accepted:any
const random=()=>randomBytes(32).toString('hex'),root=random(),admin=random(),owner=random()
const pkg=JSON.parse(readFileSync('examples/event-minimal.json','utf8'));pkg.event.id='storage-budget-test'
const bigPlan={response:{name:'存储测试',presence:[{date:'2026-10-03',intervals:[{start:'13:00',end:'20:00'}]}],bufferMinutes:0,busy:Array.from({length:500},(_,i)=>({id:'busy-'+i,date:'2026-10-03',start:'13:07',end:'13:52',title:'有效安排',source:'manual',note:'A'.repeat(2000)}))},favorites:[],routes:[]}
async function api(path:string,method='GET',auth='',body?:unknown){const res=await mf.dispatchFetch('http://localhost/api/v1'+path,{method,headers:{...(auth?{Authorization:'Bearer '+auth}:{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:res.status,...await res.json() as any}}
const put=(body:any)=>api(`/events/${event.id}/personal/${person.id}`,'PUT',owner,body)
beforeAll(async()=>{const built=await build({entryPoints:['worker/src/index.ts'],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'});mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-09-01',d1Databases:['DB'],bindings:{CREATION_MODE:'invite',CREATION_CODE:'test-create',ADMIN_ROOT_SECRET:root,ALLOWED_ORIGINS:'http://localhost:5173',BUILD_VERSION:'storage-test'}}));const db=await mf.getD1Database('DB');for(const m of readdirSync('worker/migrations').filter(x=>x.endsWith('.sql')).sort())await db.exec(readFileSync('worker/migrations/'+m,'utf8').replace(/\n/g,' '));expect((await api('/admin/session','POST','',{rootToken:root,sessionToken:admin})).status).toBe(200);event=(await api('/admin/events','POST',admin,{eventPackage:pkg,status:'published',expectedRevision:0,operationId:randomUUID()})).data;person=(await api(`/events/${event.id}/personal`,'POST','',{name:'存储测试',personalToken:owner,operationId:randomUUID()})).data},30000)
afterAll(async()=>{await mf?.dispose()})
describe.sequential('个人历史与跨身份累计存储预算',()=>{
 it('合法500条长备注仍可保存，但receipt不再保存1MB完整历史',async()=>{expect(Buffer.byteLength(JSON.stringify(bigPlan))).toBeGreaterThan(1_000_000);accepted={plan:bigPlan,operationId:randomUUID(),expectedRevision:0,scheduleRevision:event.scheduleRevision,spatialRevision:event.spatialRevision};const saved=await put(accepted);expect(saved.status).toBe(200);latest=saved.data;const second=await put({...accepted,operationId:randomUUID(),expectedRevision:1});expect(second.status).toBe(200);latest=second.data;const db=await mf.getD1Database('DB');const rows=(await db.prepare('SELECT result_json FROM personal_operations WHERE personal_id=?').bind(person.id).all<any>()).results;expect(rows.length).toBe(2);expect(rows.every(r=>Buffer.byteLength(r.result_json)<4096&&!r.result_json.includes('plan'))).toBe(true)})
 it('近期last op可重试，旧提交被后续写超越明确拒绝，同op改内容409',async()=>{const replay=await put(accepted);expect(replay.status).toBe(409);expect(replay.error.code).toBe('OPERATION_SUPERSEDED');const modified=await put({...accepted,plan:{...bigPlan,favorites:[]},expectedRevision:99});expect(modified.status).toBe(409);expect(modified.error.code).toBe('VERSION_CONFLICT')})
 it('过期重试明确失败不重写；下一次有效更新释放到期receipt预算',async()=>{const db=await mf.getD1Database('DB'),last=await db.prepare('SELECT last_op FROM personal_plans WHERE id=?').bind(person.id).first<any>();await db.prepare('UPDATE personal_operations SET expires_at=0 WHERE personal_id=?').bind(person.id).run();await db.prepare('UPDATE personal_plans SET last_receipt_expires_at=0 WHERE id=?').bind(person.id).run();const budgetBefore=(await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes;expect((await put({...accepted,operationId:last.last_op,expectedRevision:1})).error.code).toBe('IDEMPOTENCY_EXPIRED');expect((await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes).toBe(budgetBefore);const saved=await put({...accepted,operationId:randomUUID(),expectedRevision:latest.revision});expect(saved.status).toBe(200);latest=saved.data;expect((await db.prepare('SELECT count(*) AS n FROM personal_operations WHERE personal_id=?').bind(person.id).first<any>())!.n).toBe(1);expect((await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes).toBeLessThan(budgetBefore)})
 it('每人最多64条compact receipt，旧未知op仅CAS冲突；显式计划字节上限无截断',async()=>{const db=await mf.getD1Database('DB');const small=person.plan;for(let i=0;i<70;i++){if(i%25===0)await db.prepare("UPDATE rate_limits SET count=0 WHERE key LIKE 'personal-write:%'").run();const saved=await put({...accepted,plan:small,operationId:randomUUID(),expectedRevision:latest.revision});expect(saved.status).toBe(200);latest=saved.data}expect((await db.prepare('SELECT count(*) AS n FROM personal_operations WHERE personal_id=?').bind(person.id).first<any>())!.n).toBe(64);const old=await put(accepted);expect(old.status).toBe(409);const oversized=structuredClone(bigPlan);oversized.response.busy=oversized.response.busy.map(b=>({...b,note:'汉'.repeat(1100)}));const tooBig=await put({...accepted,plan:oversized,expectedRevision:latest.revision,operationId:randomUUID()});expect(tooBig.status).toBe(413);expect(tooBig.error.code).toBe('PERSONAL_PLAN_TOO_LARGE');expect((await api(`/events/${event.id}/personal/${person.id}`,'GET',owner)).data.revision).toBe(latest.revision)})
 it('两个匿名身份争最后容量仅一个成功，失败不改budget/receipt，管理写仍成功',async()=>{const db=await mf.getD1Database('DB'),limits=(await api('/limits')).data,budget=(await db.prepare('SELECT * FROM visitor_storage_budget WHERE id=1').first<any>())!;expect(budget.max_bytes).toBe(limits.visitorStorageBytes);await db.prepare('UPDATE visitor_storage_budget SET max_bytes=used_bytes+1800 WHERE id=1').run();const clients=[random(),random()];const creates=await Promise.all(clients.map(personalToken=>api(`/events/${event.id}/personal`,'POST','',{name:'竞争',personalToken,operationId:randomUUID()})));expect(creates.map(r=>r.status).sort()).toEqual([200,507]);const before=(await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes,revision=latest.revision,receipts=(await db.prepare('SELECT count(*) AS n FROM personal_operations WHERE personal_id=?').bind(person.id).first<any>())!.n;const denied=await put({...accepted,operationId:randomUUID(),expectedRevision:revision});expect(denied.status).toBe(507);expect(denied.error.code).toBe('STORAGE_BUDGET_EXCEEDED');expect((await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes).toBe(before);expect((await db.prepare('SELECT count(*) AS n FROM personal_operations WHERE personal_id=?').bind(person.id).first<any>())!.n).toBe(receipts);expect((await api(`/events/${event.id}/personal/${person.id}`,'GET',owner)).data.revision).toBe(revision);const renamed=structuredClone(pkg);renamed.event.title='管理写保留余量';const management=await api('/admin/events','POST',admin,{eventPackage:renamed,status:'published',expectedRevision:event.revision,operationId:randomUUID()});expect(management.status).toBe(200);event=management.data;await db.prepare('UPDATE visitor_storage_budget SET max_bytes=? WHERE id=1').bind(limits.visitorStorageBytes).run()})
 it('同op并发安全回放不重复扣预算',async()=>{const db=await mf.getD1Database('DB');await db.prepare("UPDATE rate_limits SET count=0 WHERE key LIKE 'personal-write:%'").run();const body={...accepted,plan:person.plan,expectedRevision:latest.revision,operationId:randomUUID()};const results=await Promise.all([put(body),put(body)]);expect(results.every(r=>r.status===200||r.status===409)).toBe(true);latest=(await api(`/events/${event.id}/personal/${person.id}`,'GET',owner)).data;expect((await put(body)).status).toBe(200);const budget=(await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes;const actual=(await db.prepare('SELECT COALESCE((SELECT SUM(length(CAST(plan_json AS BLOB))+length(CAST(availability_json AS BLOB))+1024) FROM personal_plans),0)+COALESCE((SELECT SUM(length(CAST(result_json AS BLOB))+1024) FROM personal_operations),0)+COALESCE((SELECT count(*)*1024 FROM personal_tombstones),0) AS n').first<any>())!.n;expect(budget).toBe(actual)})
 it('删除释放当前计划和全部receipt，只留小型删除重试记录',async()=>{const db=await mf.getD1Database('DB'),before=(await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes;const deletion={operationId:randomUUID(),expectedRevision:latest.revision};expect((await api(`/events/${event.id}/personal/${person.id}`,'DELETE',owner,deletion)).status).toBe(200);expect((await api(`/events/${event.id}/personal/${person.id}`,'DELETE',owner,deletion)).status).toBe(200);expect((await db.prepare('SELECT count(*) AS n FROM personal_operations WHERE personal_id=?').bind(person.id).first<any>())!.n).toBe(0);expect((await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes).toBeLessThan(before)})
})
