import { describe,it,expect,beforeAll,afterAll } from 'vitest'
import { Miniflare,convertV4MiniflareOptions } from 'miniflare'
import { build } from 'esbuild'
import { readFileSync,readdirSync } from 'node:fs'
import { randomBytes,randomUUID } from 'node:crypto'
let mf:Miniflare
const random=()=>randomBytes(32).toString('hex'),operation=()=>randomUUID(),owner=random(),personalToken=random(),admin=random(),root=random(),manager=random(),invite=random()
const pkg=JSON.parse(readFileSync('examples/event-minimal.json','utf8'))
const creation={creationCode:'test-create',ownerToken:owner,personalToken,name:'私人日程',eventPackage:pkg,operationId:operation()}
let activity:any,personal:any,group:any
async function api(path:string,method='GET',auth='',body?:unknown){const r=await mf.dispatchFetch('http://localhost/api/v1'+path,{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,...await r.json() as any}}
beforeAll(async()=>{const built=await build({entryPoints:['worker/src/index.ts'],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'});mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-09-01',d1Databases:['DB'],bindings:{CREATION_MODE:'invite',CREATION_CODE:'test-create',ADMIN_ROOT_SECRET:root,ALLOWED_ORIGINS:'http://localhost:5173',BUILD_VERSION:'private-test'}}));const db=await mf.getD1Database('DB');for(const name of readdirSync('worker/migrations').filter(x=>x.endsWith('.sql')).sort())await db.exec(readFileSync('worker/migrations/'+name,'utf8').replace(/\n/g,' '))},30000)
afterAll(async()=>{await mf?.dispose()})
describe.sequential('受控私人活动与个人空间真实D1',()=>{
 it('无需组队建立私人活动和个人记录，创建保护与永久安全重试',async()=>{expect((await api('/private-events','POST','',{...creation,creationCode:'wrong'})).status).toBe(403);const created=await api('/private-events','POST','',creation);expect(created.status).toBe(200);activity=created.data.activity;personal=created.data.personal;expect(activity.visibility).toBe('private');const db=await mf.getD1Database('DB');expect((await db.prepare('SELECT public_revision FROM events WHERE id=?').bind(activity.id).first<any>())!.public_revision).toBeNull();expect((await db.prepare('SELECT e.id FROM events e JOIN event_versions v ON v.event_id=e.id AND v.revision=e.public_revision WHERE e.id=?').bind(activity.id).all()).results).toEqual([]);expect(activity.id).not.toBe(pkg.event.id);expect((await api('/private-events','POST','',creation)).data).toEqual(created.data);expect((await api('/private-events','POST','',{...creation,name:'改内容'})).status).toBe(409);expect((await api('/events')).data).toEqual([]);expect((await api('/events/'+activity.id)).status).toBe(404);expect((await api('/events/'+activity.id,'GET',owner)).data.id).toBe(activity.id);expect((await api('/events/'+activity.id,'GET',personalToken)).data.id).toBe(activity.id);expect((await api('/events/'+activity.id+'/personal/'+personal.id,'GET',owner)).status).toBe(403)})
 it('私人JSON不能发布或授予权限，管理员普通列表不可发现私人资料',async()=>{await api('/admin/session','POST','',{rootToken:root,sessionToken:admin});expect((await api('/admin/events','GET',admin)).data).toEqual([]);const malicious=structuredClone(pkg);malicious.ownerToken=owner;expect((await api('/private-events','POST','',{...creation,ownerToken:random(),personalToken:random(),eventPackage:malicious,operationId:operation()})).status).toBe(400);const publicAttempt=structuredClone(pkg);publicAttempt.event.id=activity.id;expect((await api('/admin/events','POST',admin,{eventPackage:publicAttempt,status:'published',expectedRevision:1,operationId:operation()})).status).toBe(403);expect((await api('/events')).data).toEqual([])})
 it('个人分钟提交保留CAS与预算，管理权限不能读个人备注',async()=>{const plan={...personal.plan,response:{...personal.plan.response,presence:[{date:'2026-10-03',intervals:[{start:'13:07',end:'13:52'}]}],busy:[{id:'note',date:'2026-10-03',start:'13:20',end:'13:25',title:'私人安排',note:'私人备注',source:'manual'}]}};const b={plan,expectedRevision:0,scheduleRevision:activity.scheduleRevision,spatialRevision:activity.spatialRevision,operationId:operation()};const saved=await api(`/events/${activity.id}/personal/${personal.id}`,'PUT',personalToken,b);expect(saved.status).toBe(200);expect((await api(`/events/${activity.id}/personal/${personal.id}`,'PUT',personalToken,b)).data.plan).toEqual(plan);expect((await api(`/events/${activity.id}/personal/${personal.id}`,'PUT',personalToken,{...b,operationId:operation()})).status).toBe(409);const db=await mf.getD1Database('DB');expect((await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes).toBeGreaterThan(2048)})
 it('私人源建队要单独能力证明，邀请可读资料但只能新建自己的个人身份',async()=>{const b={sourceEventId:activity.id,sourceEventRevision:activity.revision,creationCode:'test-create',managerToken:manager,inviteToken:invite,operationId:operation()};expect((await api('/groups','POST','',b)).status).toBe(409);const created=await api('/groups','POST','',{...b,sourceEventToken:personalToken});expect(created.status).toBe(200);group=created.data;expect(group.sourceEventId).toBe(activity.id);expect((await api('/events/'+activity.id,'GET',invite)).status).toBe(200);const visitorToken=random(),visitorBody={personalToken:visitorToken,name:'同名',operationId:operation()};expect((await api(`/events/${activity.id}/personal`,'POST','',visitorBody)).status).toBe(409);const visitor=await api(`/events/${activity.id}/personal`,'POST',invite,visitorBody);expect(visitor.status).toBe(200);expect(visitor.data.id).not.toBe(personal.id);expect((await api(`/events/${activity.id}/personal/${personal.id}`,'GET',visitorToken)).status).toBe(403);expect((await api(`/events/${activity.id}/personal/${personal.id}`,'GET',manager)).status).toBe(403);expect(JSON.stringify((await api('/groups/'+group.id,'GET',invite)).data)).not.toMatch(/私人备注|ownerToken|personalToken/);expect((await api('/events')).data).toEqual([])})
 it('邀请撤销后不能读取私人活动；独立个人凭据不随邀请撤销丢失',async()=>{const rotate=await api(`/groups/${group.id}/invite/rotate`,'POST',manager,{inviteToken:random(),expectedRevision:group.revision,operationId:operation()});expect(rotate.status).toBe(200);expect((await api('/events/'+activity.id,'GET',invite)).status).toBe(404);expect((await api('/events/'+activity.id,'GET',personalToken)).status).toBe(200);expect((await api('/groups/'+group.id,'GET',manager)).data.sourceStatus).toBe('published');expect((await api(`/groups/${group.id}/source-refresh`,'POST',manager,{expectedRevision:rotate.data.revision,sourceEventRevision:activity.revision,operationId:operation()})).status).toBe(200)})
 it('只有私人活动owner能修改资料；标题不复核、时间变化要求复核且小队快照保留',async()=>{const title=structuredClone(pkg);title.event.title='私人改名';const request={eventPackage:title,expectedRevision:activity.revision,operationId:operation()};expect((await api('/events/'+activity.id,'PATCH',personalToken,request)).status).toBe(403);const updated=await api('/events/'+activity.id,'PATCH',owner,request);expect(updated.status).toBe(200);expect(updated.data.scheduleRevision).toBe(activity.scheduleRevision);expect((await api('/events/'+activity.id,'PATCH',owner,request)).data.revision).toBe(updated.data.revision);expect((await api('/events/'+activity.id+'/event-export','GET',invite)).status).toBe(404);expect((await api('/events/'+activity.id+'/event-export','GET',personalToken)).data).toEqual(title);const times=structuredClone(title);times.event.days[0].openIntervals[0].end='19:00';const raced=await Promise.all([1,2].map(()=>api('/events/'+activity.id,'PATCH',owner,{eventPackage:times,expectedRevision:updated.data.revision,operationId:operation()})));expect(raced.map(x=>x.status).sort()).toEqual([200,409]);const next=raced.find(x=>x.status===200)!.data;expect(next.scheduleRevision).toBe(activity.scheduleRevision+1);const own=(await api(`/events/${activity.id}/personal/${personal.id}`,'GET',personalToken)).data;expect((await api(`/events/${activity.id}/personal/${personal.id}`,'PUT',personalToken,{plan:own.plan,expectedRevision:own.revision,scheduleRevision:activity.scheduleRevision,spatialRevision:activity.spatialRevision,operationId:operation()})).status).toBe(409);expect((await api('/groups/'+group.id,'GET',manager)).data.eventPackage.event.title).toBe(pkg.event.title);expect((await api('/events')).data).toEqual([]);activity=next})
 it('跨活动源凭据不能建队或认领个人；移除成员只撤其小队能力',async()=>{const second=await api('/private-events','POST','',{...creation,ownerToken:random(),personalToken:random(),name:'另一活动',operationId:operation()});expect(second.status).toBe(200);const secondId=second.data.activity.id;expect((await api('/events/'+secondId,'GET',personalToken)).status).toBe(404);expect((await api('/groups','POST','',{sourceEventId:secondId,sourceEventToken:personalToken,managerToken:random(),inviteToken:random(),creationCode:'test-create',operationId:operation()})).status).toBe(409);const current=(await api('/groups/'+group.id,'GET',manager)).data,newInvite=random();await api(`/groups/${group.id}/invite/rotate`,'POST',manager,{inviteToken:newInvite,expectedRevision:current.revision,operationId:operation()});const memberToken=random(),joined=await api(`/groups/${group.id}/join`,'POST',newInvite,{memberToken,name:'队员',operationId:operation()});expect(joined.status).toBe(200);expect((await api('/events/'+activity.id,'GET',memberToken)).status).toBe(200);const ownToken=random(),own=await api(`/events/${activity.id}/personal`,'POST',memberToken,{personalToken:ownToken,name:'队员',operationId:operation()});expect(own.status).toBe(200);expect((await api(`/events/${activity.id}/personal/${own.data.id}/link`,'POST',ownToken,{memberToken,memberId:joined.data.id})).data.linked).toBe(true);expect((await api(`/groups/${group.id}/members/${joined.data.id}`,'DELETE',manager)).status).toBe(200);expect((await api('/events/'+activity.id,'GET',memberToken)).status).toBe(404);expect((await api('/events/'+activity.id,'GET',ownToken)).status).toBe(200);expect((await api(`/events/${activity.id}/personal/${own.data.id}/links`,'GET',ownToken)).data).toEqual([]);expect((await api('/events')).data).toEqual([])})
 it('队长可改本队私人配置，不改源活动或别队，也不能替成员提交',async()=>{const current=(await api('/groups/'+group.id,'GET',manager)).data,pack=structuredClone(current.eventPackage);pack.event.title='本队自己的标题';const preview=await api(`/groups/${group.id}/event-import/preview`,'POST',manager,{eventPackage:pack});expect(preview.status).toBe(200);const committed=await api(`/groups/${group.id}/event-import/commit`,'POST',manager,{eventPackage:pack,expectedRevision:current.revision,operationId:operation()});expect(committed.status).toBe(200);expect(committed.data.eventPackage.event.title).toBe('本队自己的标题');expect((await api('/events/'+activity.id,'GET',owner)).data.eventPackage.event.title).toBe('私人改名');expect((await api(`/groups/${group.id}/event-import/commit`,'POST',personalToken,{eventPackage:pack,expectedRevision:committed.data.revision,operationId:operation()})).status).toBe(401)})
 it('私有活动包与个人初始预算原子提交，预算不足不留下部分事件',async()=>{const db=await mf.getD1Database('DB'),before=(await db.prepare('SELECT count(*) AS n FROM events').first<any>())!.n,budget=await db.prepare('SELECT used_bytes,max_bytes FROM visitor_storage_budget WHERE id=1').first<any>();await db.prepare('UPDATE visitor_storage_budget SET max_bytes=used_bytes+100 WHERE id=1').run();const result=await api('/private-events','POST','',{...creation,ownerToken:random(),personalToken:random(),operationId:operation()});expect(result.status).toBe(507);expect((await db.prepare('SELECT count(*) AS n FROM events').first<any>())!.n).toBe(before);expect((await db.prepare('SELECT used_bytes FROM visitor_storage_budget WHERE id=1').first<any>())!.used_bytes).toBe(budget.used_bytes);await db.prepare('UPDATE visitor_storage_budget SET max_bytes=? WHERE id=1').bind(budget.max_bytes).run()})
})
