import { describe,it,expect } from 'vitest'
import { Miniflare,convertV4MiniflareOptions } from 'miniflare'
import { build } from 'esbuild'
import { readFileSync,readdirSync } from 'node:fs'
import { randomUUID,randomBytes,createHash } from 'node:crypto'
import { parseEventPackage } from '../../shared/event-validation'
const token=()=>randomBytes(32).toString('hex'),hash=(s:string)=>createHash('sha256').update(s).digest('hex'),minimal=JSON.parse(readFileSync('examples/event-minimal.json','utf8')),demo=JSON.parse(readFileSync('examples/convention-demo.v2.json','utf8'))
async function database(mf:Miniflare){const db=await mf.getD1Database('DB');for(const f of readdirSync('worker/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('worker/migrations/'+f,'utf8').replace(/\n/g,' '));return db}
describe('公开媒体查询预算与raw运输边界真实D1',()=>{
 it('50张ready历史仅有界查询，精确旧manifest地图可公开且取消仍拒',async()=>{
  const code=`import{handleMedia}from'./worker/src/media';export default{async fetch(req,env){let queries=0;const DB={prepare(sql){queries++;if(queries>50)throw new Error('QUERY_LIMIT');return env.DB.prepare(sql)}};try{const out=await handleMedia({req,DB,path:new URL(req.url).pathname,method:req.method,authHash:'',now:new Date().toISOString(),admin:async()=>{throw new Error('FORBIDDEN')},verifyNode:async()=>{},fail:(code,message,status=400)=>{throw Object.assign(new Error(message),{code,status})}});return Response.json({data:out.data,queries})}catch(e){return Response.json({error:{code:e.code||e.message},queries},{status:e.status||503})}}}`
  const built=await build({stdin:{contents:code,resolveDir:process.cwd(),sourcefile:'query-budget-worker.ts'},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'}),mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-09-01',d1Databases:['DB']}));try{const db=await database(mf),pack=structuredClone(demo);pack.event.id='query-history-fixture';const m=pack.assetManifest[0],now=new Date().toISOString();await db.prepare("INSERT INTO events(id,revision,schedule_revision,spatial_revision,status,event_json,public_revision,last_op,last_digest,created_at,updated_at) VALUES(?,1,1,1,'published',?,1,'seed','seed',?,?)").bind(pack.event.id,JSON.stringify(pack),now,now).run();await db.prepare('INSERT INTO event_versions SELECT id,revision,schedule_revision,spatial_revision,status,event_json,updated_at FROM events WHERE id=?').bind(pack.event.id).run();let bound='';for(let i=0;i<50;i++){const id=randomUUID();if(i===0)bound=id;await db.prepare("INSERT INTO media_assets(id,event_id,asset_key,state,mime_type,width,height,size_bytes,sha256,expected_event_revision,ticket_hash,expires_at,operation_id,operation_digest,revision,created_at,updated_at) VALUES(?,?,?,'ready',?,?,?,?,?,1,?,?,?,?, ?,?,?)").bind(id,pack.event.id,m.assetKey,m.mimeType,m.width,m.height,m.sizeBytes,i===0?m.sha256:String(i).padStart(64,'0'),hash(token()),Date.now()+60000,randomUUID(),'fixture',i+1,now,now).run()}
   const path='http://localhost/events/'+pack.event.id+'/assets',res=await mf.dispatchFetch(path),json=await res.json() as any;expect(res.status).toBe(200);expect(json.queries).toBeLessThanOrEqual(3);expect(json.data.map((a:any)=>a.id)).toEqual([bound]);expect(json.data[0].sha256).toBe(m.sha256);await db.prepare("UPDATE events SET status='cancelled' WHERE id=?").bind(pack.event.id).run();const denied=await mf.dispatchFetch(path),deniedBody=await denied.json() as any;expect(denied.status).toBe(200);expect(deniedBody.data).toEqual([]);expect(deniedBody.queries).toBeLessThanOrEqual(3)
  }finally{await mf.dispose()}
 })
 it('仅活动包路由容纳1MiB raw最坏合法转义，包上限和普通2MiB请求仍拒超限',async()=>{
  // Buffer the HTTP transport before the unchanged Worker entrypoint to avoid
  // undici EPIPE when production correctly returns before reading a large body.
  const transport=`import worker from './worker/src/index';export default{async fetch(req,env,ctx){const bytes=await req.arrayBuffer();return worker.fetch(new Request(req.url,{method:req.method,headers:req.headers,body:bytes}),env,ctx)}}`,built=await build({stdin:{contents:transport,resolveDir:process.cwd(),sourcefile:'encoded-body-transport.ts'},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'}),mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-09-01',d1Databases:['DB'],bindings:{BUILD_VERSION:'isolated-encoded-body'}}));try{const db=await database(mf),admin=token();await db.prepare('INSERT INTO admin_sessions VALUES(?,?)').bind(hash(admin),Date.now()+3600000).run();const p=structuredClone(minimal);p.schemaVersion=2;p.event.eventType='generic';p.event.id='encoded-raw-fixture';const base=JSON.stringify(p),raw=base+'\t'.repeat(1048576-Buffer.byteLength(base));expect(Buffer.byteLength(raw)).toBe(1048576);expect(parseEventPackage(raw).event.id).toBe(p.event.id);const escape=(value:string)=>'"'+Array.from(value,c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0')).join('')+'"',envelope=(text:string)=>'{"raw":'+escape(text)+',"status":"draft","expectedRevision":0,"operationId":"'+randomUUID()+'"}';
   const send=async(path:string,body:string)=>{const res=await mf.dispatchFetch('http://localhost/api/v1'+path,{method:'POST',headers:{Authorization:'Bearer '+admin,'Content-Type':'application/json'},body});return {status:res.status,...await res.json() as any}},body=envelope(raw);expect(Buffer.byteLength(body)).toBeGreaterThan(2*1024*1024);const saved=await send('/admin/events',body);expect(saved.status).toBe(200);expect(saved.data.eventPackage.event.id).toBe(p.event.id);
   const bad=await send('/admin/events',envelope(raw+'\t'));expect(bad.status).toBe(400);expect(bad.error.code).toBe('LIMIT_EXCEEDED');expect((await db.prepare('SELECT count(*) AS n FROM events').first<any>())!.n).toBe(1);const ordinary=await send('/admin/session','x'.repeat(2*1024*1024+1));expect(ordinary.status).toBe(413);expect(ordinary.error.code).toBe('LIMIT_EXCEEDED');const oversized=await send('/admin/events','x'.repeat(6*1024*1024+65537));expect(oversized.status).toBe(413);expect(oversized.error.code).toBe('LIMIT_EXCEEDED')
  }finally{await mf.dispose()}
 },30000)
})
