import { describe,it,expect,beforeAll,afterAll,vi } from 'vitest'
import { Miniflare,convertV4MiniflareOptions } from 'miniflare'
import { build } from 'esbuild'
import { readFileSync,readdirSync } from 'node:fs'
import { randomBytes,randomUUID,createHash } from 'node:crypto'
vi.mock('@vercel/oidc',()=>({getVercelOidcToken:async()=> 'isolated-node-proof'}))
import { finishImage } from '../../src/server/media-service'
let mf:Miniflare
const token=()=>randomBytes(32).toString('hex'),hash=(s:string)=>createHash('sha256').update(s).digest('hex'),admin=token()
const minimal=JSON.parse(readFileSync('examples/event-minimal.json','utf8')),demo=JSON.parse(readFileSync('examples/convention-demo.v2.json','utf8'))
async function api(path:string,method='GET',bearer='',body?:unknown,trusted=false){const response=await mf.dispatchFetch('http://localhost'+path,{method,headers:{Authorization:'Bearer '+bearer,'Content-Type':'application/json',...(trusted?{'X-Test-Trusted-Node':'yes'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,...await response.json() as any}}
beforeAll(async()=>{
 // Only the Node verifier is supplied by this isolated harness. Real RS256 issuer,
 // project and environment boundaries remain covered by the existing OIDC tests.
 const code=`import {handleMedia} from './worker/src/media';import {handleActivity} from './worker/src/activity';export default{async fetch(req,env){const hash=async(s)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),x=>x.toString(16).padStart(2,'0')).join('');const authHash=await hash(req.headers.get('Authorization').replace(/^Bearer /,''));const fail=(code,message,status=400)=>{throw Object.assign(new Error(message),{code,status})};try{const ctx={req,DB:env.DB,path:new URL(req.url).pathname,method:req.method,authHash,now:new Date().toISOString(),body:()=>req.json(),hash,token:s=>{if(!/^[a-f0-9]{64}$/.test(s))fail('INVALID_CAPABILITY','token',401);return s},op:s=>s,admin:async()=>{if(!await env.DB.prepare('SELECT hash FROM admin_sessions WHERE hash=? AND expires_at>?').bind(authHash,Date.now()).first())fail('INVALID_CAPABILITY','admin',401)},creation:async(code)=>{if(code!=='isolated-create')fail('FORBIDDEN','creation',403)},limited:async(key,max)=>{const window=Math.floor(Date.now()/60000);await env.DB.prepare('INSERT INTO rate_limits(key,window,count) VALUES(?,?,1) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END,window=excluded.window').bind(key,window).run();if((await env.DB.prepare('SELECT count FROM rate_limits WHERE key=?').bind(key).first()).count>max)fail('LIMIT_EXCEEDED','rate',429)},verifyNode:async()=>{if(req.headers.get('X-Test-Trusted-Node')!=='yes')fail('FORBIDDEN','node',403)},fail};let out=await handleMedia(ctx);if(!out.handled)out=await handleActivity(ctx);return Response.json(out.handled?{data:out.data}:{error:{code:'NOT_FOUND'}},{status:out.handled?200:404})}catch(e){return Response.json({error:{code:e.code,message:e.message}},{status:e.status||503})}}}`
 const built=await build({stdin:{contents:code,resolveDir:process.cwd(),sourcefile:'review-worker-test.ts'},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'})
 mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-09-01',d1Databases:['DB']}))
 const db=await mf.getD1Database('DB');for(const file of readdirSync('worker/migrations').filter(x=>x.endsWith('.sql')).sort())await db.exec(readFileSync('worker/migrations/'+file,'utf8').replace(/\n/g,' '))
 await db.prepare('INSERT INTO admin_sessions VALUES(?,?)').bind(hash(admin),Date.now()+3600000).run()
},30000)
afterAll(async()=>{await mf?.dispose()})
async function seedEvent(pack:any){const db=await mf.getD1Database('DB'),now=new Date().toISOString();await db.prepare("INSERT INTO events(id,revision,schedule_revision,spatial_revision,status,event_json,public_revision,last_op,last_digest,created_at,updated_at) VALUES(?,1,1,1,'draft',?,NULL,'seed','seed',?,?)").bind(pack.event.id,JSON.stringify(pack),now,now).run();return db}
async function seedReady(eventId:string,assetKey:string,sha='a'.repeat(64),revision=1,width=64,height=32,mime='image/png',size=200){const db=await mf.getD1Database('DB'),id=randomUUID(),now=new Date().toISOString();await db.prepare("INSERT INTO media_assets(id,event_id,asset_key,state,mime_type,width,height,size_bytes,sha256,expected_event_revision,ticket_hash,expires_at,operation_id,operation_digest,declared_size_bytes,source_path,display_path,display_size_bytes,revision,created_at,updated_at) VALUES(?,?,?,'ready',?,?,?,?,?,1,?,?,?,?,200,?,?,100,?,?,?)").bind(id,eventId,assetKey,mime,width,height,size,sha,hash(token()),Date.now()-1000,randomUUID(),'fixture',`assets/${eventId}/${id}/source-${sha}`,`assets/${eventId}/${id}/display-${'b'.repeat(64)}.webp`,revision,now,now).run();return id}
const reserve=(uploadToken:string,assetKey:string)=>({uploadToken,assetKey,operationId:randomUUID(),sizeBytes:100,mimeType:'image/png'})
const metadata=(eventId:string,id:string)=>({sourcePath:`assets/${eventId}/${id}/source-${'a'.repeat(64)}`,displayPath:`assets/${eventId}/${id}/display-${'b'.repeat(64)}.webp`,mimeType:'image/png',width:64,height:32,sizeBytes:200,sha256:'a'.repeat(64),displaySizeBytes:100,displayMimeType:'image/webp',displayWidth:64,displayHeight:32})
describe.sequential('审查修复真实隔离D1回归',()=>{
 it('私人创建失败猜码也消耗来源限流，超限不写入',async()=>{const db=await mf.getD1Database('DB'),body={creationCode:'wrong',ownerToken:token(),personalToken:token(),name:'隔离测试',eventPackage:minimal,operationId:randomUUID()};for(let i=0;i<20;i++)expect((await api('/private-events','POST','',body)).status).toBe(403);expect((await api('/private-events','POST','',body)).status).toBe(429);expect((await db.prepare('SELECT count(*) AS n FROM events').first<any>())!.n).toBe(0);await db.prepare("DELETE FROM rate_limits WHERE key LIKE 'private-create:%'").run()})
 it('私人包ID不可修改，拒绝后版本与快照不变',async()=>{const owner=token(),body={creationCode:'isolated-create',ownerToken:owner,personalToken:token(),name:'隔离测试',eventPackage:minimal,operationId:randomUUID()},created=await api('/private-events','POST','',body);expect(created.status).toBe(200);const changed=structuredClone(minimal);changed.event.id='other-package-id';expect((await api('/events/'+created.data.activity.id,'PATCH',owner,{eventPackage:changed,expectedRevision:1,operationId:randomUUID()})).status).toBe(400);expect((await api('/events/'+created.data.activity.id,'GET',owner)).data).toEqual(created.data.activity)})
 it('发布精确选择清单旧ready，最新同key不同hash或尺寸不遮挡合法资产',async()=>{const pack=structuredClone(demo);pack.event.id='identity-selection-fixture';const db=await seedEvent(pack),m=pack.assetManifest[0];await seedReady(pack.event.id,m.assetKey,m.sha256,1,m.width,m.height,m.mimeType,m.sizeBytes);await seedReady(pack.event.id,m.assetKey,'c'.repeat(64),2,m.width,m.height,m.mimeType,m.sizeBytes);await seedReady(pack.event.id,m.assetKey,m.sha256,3,m.width+1,m.height,m.mimeType,m.sizeBytes);const published=await api('/admin/events','POST',admin,{eventPackage:pack,status:'published',expectedRevision:1,operationId:randomUUID()});expect(published.status).toBe(200);expect((await db.prepare('SELECT public_revision FROM events WHERE id=?').bind(pack.event.id).first<any>())!.public_revision).toBe(2);const bad=structuredClone(pack);bad.assetManifest[0].sha256='d'.repeat(64);bad.event.extensions.convention.maps[0].revision++;bad.event.extensions.convention.maps[0].needsReview=true;expect((await api('/admin/events','POST',admin,{eventPackage:bad,status:'published',expectedRevision:2,operationId:randomUUID()})).status).toBe(400);expect((await db.prepare('SELECT revision FROM events WHERE id=?').bind(pack.event.id).first<any>())!.revision).toBe(2)})
 it('ready激活响应丢失后过期仍可安全回读，错误token/非Node/过期pending仍拒绝',async()=>{const pack=structuredClone(minimal);pack.event.id='activation-retry-fixture';const db=await seedEvent(pack),t=token(),saved=await api(`/admin/events/${pack.event.id}/assets`,'POST',admin,reserve(t,'retry-map'));expect(saved.status).toBe(200);const id=saved.data.asset.id,path=`/events/${pack.event.id}/assets/${id}/activate`,body=metadata(pack.event.id,id),first=await api(path,'POST',t,body,true);expect(first.status).toBe(200);await db.prepare('UPDATE media_assets SET expires_at=? WHERE id=?').bind(Date.now()-1,id).run();expect((await api(path,'POST',t,body,true)).data).toEqual(first.data);expect((await api(path,'POST',token(),body,true)).status).toBe(401);expect((await api(path,'POST',t,body)).status).toBe(403);const finishReplay=await api(`/events/${pack.event.id}/assets/${id}/ticket`,'POST',t,{},true);expect(finishReplay.status).toBe(200);expect(finishReplay.data).toEqual({asset:first.data});
 const previousAPI=process.env.ACTIVITY_API_URL,previousStore=process.env.BLOB_STORE_ID;process.env.ACTIVITY_API_URL='https://isolated.invalid';process.env.BLOB_STORE_ID='isolated-unused-store';
 const fetchSpy=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=new URL(String(input));expect(url.host).toBe('isolated.invalid');expect(url.pathname).toBe('/api/v1'+`/events/${pack.event.id}/assets/${id}/ticket`);const headers=new Headers(init?.headers);expect(headers.get('X-Vercel-OIDC-Token')).toBe('isolated-node-proof');headers.set('X-Test-Trusted-Node','yes');return mf.dispatchFetch('http://localhost'+url.pathname.replace('/api/v1',''),{...init,headers})});
 try{expect(await finishImage({eventId:pack.event.id,assetId:id,uploadToken:t})).toEqual(first.data);expect(fetchSpy).toHaveBeenCalledTimes(1)}finally{fetchSpy.mockRestore();if(previousAPI===undefined)delete process.env.ACTIVITY_API_URL;else process.env.ACTIVITY_API_URL=previousAPI;if(previousStore===undefined)delete process.env.BLOB_STORE_ID;else process.env.BLOB_STORE_ID=previousStore}
 expect((await api(`/events/${pack.event.id}/assets/${id}/ticket`,'POST',t,{})).status).toBe(403);expect((await api(`/events/${pack.event.id}/assets/${id}/ticket`,'POST',token(),{},true)).status).toBe(401);const pendingToken=token(),pending=await api(`/admin/events/${pack.event.id}/assets`,'POST',admin,reserve(pendingToken,'pending-map'));await db.prepare('UPDATE media_assets SET expires_at=? WHERE id=?').bind(Date.now()-1,pending.data.asset.id).run();expect((await api(`/events/${pack.event.id}/assets/${pending.data.asset.id}/activate`,'POST',pendingToken,metadata(pack.event.id,pending.data.asset.id),true)).status).toBe(401)})
 it('五张当前图多次替换不被历史ready锁死，并发额外slot至多一张',async()=>{const pack=structuredClone(minimal);pack.event.id='five-map-replacement-fixture';pack.event.extensions={convention:{maps:Array.from({length:5},(_,i)=>({id:'bound-'+i,assetKey:'bound-'+i,width:64,height:32})),pois:[],routingGraphs:[]}};const db=await seedEvent(pack);for(let i=0;i<5;i++)await seedReady(pack.event.id,'bound-'+i);await seedReady(pack.event.id,'historical-unbound');const path=`/admin/events/${pack.event.id}/assets`;const replacement=await api(path,'POST',admin,reserve(token(),'replacement-one'));expect(replacement.status).toBe(200);await db.prepare("UPDATE media_assets SET state='ready',source_path='isolated-source',display_path='isolated-display',size_bytes=200,display_size_bytes=100 WHERE id=?").bind(replacement.data.asset.id).run();const raced=await Promise.all(['replacement-two','replacement-three'].map(k=>api(path,'POST',admin,reserve(token(),k))));expect(raced.map(r=>r.status).sort()).toEqual([200,409]);expect((await db.prepare("SELECT count(*) AS n FROM media_assets WHERE event_id=? AND state IN ('pending','processing') AND expires_at>?").bind(pack.event.id,Date.now()).first<any>())!.n).toBe(1)})
 it('归档公开活动仍可读匹配地图，草稿/取消/错误manifest与跨活动仍拒绝',async()=>{
  const pack=structuredClone(demo);pack.event.id='archived-public-map-fixture';const db=await seedEvent(pack),m=pack.assetManifest[0],id=await seedReady(pack.event.id,m.assetKey,m.sha256,1,m.width,m.height,m.mimeType,m.sizeBytes),path=`/events/${pack.event.id}/assets/${id}/read-ticket`;
  expect((await api(`/events/${pack.event.id}/assets`)).data).toEqual([]);expect((await api(path,'GET','',undefined,true)).status).toBe(401);
  const publish=await api('/admin/events','POST',admin,{eventPackage:pack,status:'published',expectedRevision:1,operationId:randomUUID()});expect(publish.status).toBe(200);
  const archive=await api('/admin/events','POST',admin,{eventPackage:pack,status:'archived',expectedRevision:2,operationId:randomUUID()});expect(archive.status).toBe(200);expect((await api('/events/'+pack.event.id)).data.status).toBe('archived');
  expect((await api(`/events/${pack.event.id}/assets`)).data.map((a:any)=>a.id)).toEqual([id]);expect((await api(path,'GET','',undefined,true)).status).toBe(200);expect((await api(`/events/another-event/assets/${id}/read-ticket`,'GET','',undefined,true)).status).toBe(404);
  const altered=structuredClone(pack);altered.assetManifest[0].sha256='f'.repeat(64);await db.prepare('UPDATE event_versions SET event_json=? WHERE event_id=? AND revision=3').bind(JSON.stringify(altered),pack.event.id).run();expect((await api(`/events/${pack.event.id}/assets`)).data).toEqual([]);expect((await api(path,'GET','',undefined,true)).status).toBe(401);await db.prepare('UPDATE event_versions SET event_json=? WHERE event_id=? AND revision=3').bind(JSON.stringify(pack),pack.event.id).run();
  const cancel=await api('/admin/events','POST',admin,{eventPackage:pack,status:'cancelled',expectedRevision:3,operationId:randomUUID()});expect(cancel.status).toBe(200);expect((await api(`/events/${pack.event.id}/assets`)).data).toEqual([]);expect((await api(path,'GET','',undefined,true)).status).toBe(404)
 })
 it('真实Worker来源超限先拒绝畸形/大body/坏token，合法个人创建仍幂等',async()=>{
  // Buffer only at the test transport boundary: workerd otherwise closes an unread
  // large HTTP upload after its early 429, causing undici's write EPIPE to abort
  // response consumption. The original Worker still sees the original bytes and
  // declared length; the body-read sentinel proves its parser is never reached.
  const transport=`import worker from './worker/src/index';export default{async fetch(req,env,ctx){const bytes=await req.arrayBuffer();const request=new Request(req.url,{method:req.method,headers:req.headers,body:bytes});if(req.headers.get('X-Test-Body-Read-Guard')==='yes')Object.defineProperty(request,'body',{get(){throw new Error('TEST_BODY_PARSED_BEFORE_SOURCE_LIMIT')}});return worker.fetch(request,env,ctx)}}`
  const built=await build({stdin:{contents:transport,resolveDir:process.cwd(),sourcefile:'rate-limit-test-transport.ts'},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022'}),actual=new Miniflare(convertV4MiniflareOptions({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-09-01',d1Databases:['DB'],bindings:{CREATION_MODE:'invite',CREATION_CODE:'isolated-create',ADMIN_ROOT_SECRET:token(),BUILD_VERSION:'isolated-review'}}));
  try{const db=await actual.getD1Database('DB');for(const file of readdirSync('worker/migrations').filter(x=>x.endsWith('.sql')).sort())await db.exec(readFileSync('worker/migrations/'+file,'utf8').replace(/\n/g,' '));const pack=structuredClone(minimal);pack.event.id='anonymous-source-gate-fixture';const now=new Date().toISOString();await db.prepare("INSERT INTO events(id,revision,schedule_revision,spatial_revision,status,event_json,public_revision,last_op,last_digest,created_at,updated_at) VALUES(?,1,1,1,'published',?,1,'seed','seed',?,?)").bind(pack.event.id,JSON.stringify(pack),now,now).run();await db.prepare('INSERT INTO event_versions SELECT id,revision,schedule_revision,spatial_revision,status,event_json,updated_at FROM events WHERE id=?').bind(pack.event.id).run();
   const source='198.51.100.24',key='personal-create-source:'+source,path='http://localhost/api/v1/events/'+pack.event.id+'/personal',headers={'CF-Connecting-IP':source,'Content-Type':'application/json'};
   await db.prepare('INSERT INTO rate_limits(key,window,count) VALUES(?,?,120)').bind(key,Math.floor(Date.now()/60000)).run();
   for(const request of [{body:'{'},{body:'x'.repeat(2097153)},{body:JSON.stringify({personalToken:'bad',operationId:randomUUID()})}]){const response=await actual.dispatchFetch(path,{method:'POST',headers:{...headers,'X-Test-Body-Read-Guard':'yes'},body:request.body});expect(response.status).toBe(429);expect((await response.json() as any).error.code).toBe('LIMIT_EXCEEDED')}
   expect((await db.prepare('SELECT count(*) AS n FROM personal_plans').first<any>())!.n).toBe(0);expect(await db.prepare('SELECT key FROM rate_limits WHERE key=?').bind('personal-create-day:'+source).first()).toBeNull();
   await db.prepare('UPDATE rate_limits SET count=0 WHERE key=?').bind(key).run();expect((await actual.dispatchFetch(path,{method:'POST',headers,body:'{'})).status).toBe(400);expect((await db.prepare('SELECT count FROM rate_limits WHERE key=?').bind(key).first<any>())!.count).toBe(1);
   const body={personalToken:token(),operationId:randomUUID(),name:'隔离个人'},request=async(value:unknown)=>{const res=await actual.dispatchFetch(path,{method:'POST',headers,body:JSON.stringify(value)});return {status:res.status,...await res.json() as any}};const created=await request(body);expect(created.status).toBe(200);expect((await request(body)).data.id).toBe(created.data.id);expect((await request({...body,name:'改内容'})).status).toBe(409);expect((await db.prepare('SELECT count(*) AS n FROM personal_plans').first<any>())!.n).toBe(1)
  }finally{await actual.dispose()}
 })

 it('owner只读证明仅私人owner成功，个人/小队/错误/public拒绝且无写入',async()=>{
  const owner=token(),personalToken=token(),body={creationCode:'isolated-create',ownerToken:owner,personalToken,name:'owner恢复隔离',eventPackage:minimal,operationId:randomUUID()},created=await api('/private-events','POST','',body);expect(created.status).toBe(200);const eventId=created.data.activity.id,db=await mf.getD1Database('DB'),groupToken=token(),now=new Date().toISOString();
  await db.prepare("INSERT INTO groups(id,title,event_json,manager_hash,invite_hash,create_op,create_digest,created_at,updated_at,source_event_id) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(randomUUID(),'隔离小队',JSON.stringify(minimal),hash(token()),hash(groupToken),randomUUID(),'fixture',now,now,eventId).run();expect((await api('/events/'+eventId,'GET',groupToken)).status).toBe(200);
  const before=await db.prepare('SELECT * FROM events ORDER BY id').all();expect((await api(`/events/${eventId}/owner`,'GET',owner)).data).toEqual(created.data.activity);for(const bad of [personalToken,groupToken,token(),''])expect((await api(`/events/${eventId}/owner`,'GET',bad)).status).toBe(403);expect((await api('/events/identity-selection-fixture/owner','GET',owner)).status).toBe(403);expect((await api('/events/missing-owner-fixture/owner','GET',owner)).status).toBe(403);expect((await db.prepare('SELECT * FROM events ORDER BY id').all()).results).toEqual(before.results)
 })

})
