import {useEffect,useRef,useState,type ReactNode} from 'react'
import {Map,CalendarDays,Users,UserRound,ChevronRight,Heart,MapPin,Download,Link2,ArrowLeft} from 'lucide-react'
import {TabBar} from '../../ui/TabBar'
import {Sheet} from '../../ui/Sheet'
import {api,ApiFailure} from '../api'
import {readLocal,writeLocal,removeLocal,download} from '../storage'
import {newToken,operationId} from '../../../shared/api'
import {validateResponse} from '../../../shared/event-validation'
import type {ActivityDTO,PersonalDTO,PersonalPlan,PersonalCapability,POI} from '../../../shared/activity-contract'
import type {CapabilityRecord,GroupDTO,ParticipantResponse} from '../../../shared/types'
import {receivePersonal,acknowledgePersonal,type PersonalDraft} from './personal-state'
import type {PathResult} from '../../../shared/routing'
import {prepareActivity} from './offline'
import {PersonalPlanView} from './PersonalPlanView'
export interface ActivityAppProps{eventId?:string;caps:CapabilityRecord[];remember:(c:CapabilityRecord)=>Promise<void>;go:(path:string)=>void;renderGroup:(id:string,plan?:ParticipantResponse,eventId?:string)=>ReactNode;theme:string;setTheme:(v:string)=>void;renderMap?:(activity:ActivityDTO,mapId:string,selectedPoiId:string|undefined,favorites:string[],onSelect:(id:string)=>void,route?:PathResult)=>ReactNode}
const typeText={generic:'活动',comic_convention:'漫展'}
function blank(activity:ActivityDTO,name='我'):PersonalPlan{return {response:{name,presence:activity.eventPackage.event.days.map(d=>({date:d.date,intervals:[]})),busy:[],bufferMinutes:activity.eventPackage.event.defaultBufferMinutes},favorites:[],routes:[]}}
export function ActivityApp({eventId,caps,remember,go,renderGroup,theme,setTheme,renderMap}:ActivityAppProps){const [events,setEvents]=useState<ActivityDTO[]>([]);const [activity,setActivity]=useState<ActivityDTO|null>(null);const [cap,setCap]=useState<PersonalCapability|null>(null);const [draft,setDraft]=useState<PersonalDraft|null>(null);const ref=useRef(draft);ref.current=draft;const creationTask=useRef<Promise<PersonalDraft>|null>(null);const active=useRef(eventId);active.current=eventId;const [tab,setTab]=useState('browse');const [selectedPoi,setSelectedPoi]=useState<string|null>(null);const [selectedSession,setSelectedSession]=useState<string|null>(null);const [mapId,setMapId]=useState('');const [search,setSearch]=useState('');const [error,setError]=useState('');const [status,setStatus]=useState('');const [pending,setPending]=useState(false);const [loaded,setLoaded]=useState(false);const [name,setName]=useState('我');const [personalSheet,setPersonalSheet]=useState(false);const [groups,setGroups]=useState<GroupDTO[]>([]);const [groupId,setGroupId]=useState<string|null>(null);const [createSheet,setCreateSheet]=useState(false);const [groupTitle,setGroupTitle]=useState('');const [creationCode,setCreationCode]=useState('');const [conflict,setConflict]=useState(false);const [date,setDate]=useState('');const [highlightPoi,setHighlightPoi]=useState<string|undefined>(undefined)
 const personalKey=`activity-personal:${eventId}`;const capKey=`activity-cap:${eventId}`;const snapshotKey=`activity-snapshot:${eventId}`;
 const query=new URLSearchParams(location.search);function updateContext(next:Record<string,string|undefined>){const p=new URLSearchParams(location.search);for(const [key,value]of Object.entries(next)){if(value)p.set(key,value);else p.delete(key)}history.replaceState(null,'',`${location.pathname}${p.size?'?'+p.toString():''}`)}
 useEffect(()=>{let cancelled=false;creationTask.current=null;setLoaded(false);setError('');setActivity(null);setDraft(null);ref.current=null;setCap(null);setSelectedPoi(null);setSelectedSession(null);setGroupId(null);setPersonalSheet(false);setCreateSheet(false);setTab(query.get('view')||'browse');setSearch('');setConflict(false);setDate(query.get('date')||'');setHighlightPoi(undefined);
 (async()=>{if(!eventId){try{const data=await api<ActivityDTO[]|{items:ActivityDTO[]}>('/events');if(!cancelled){const list=Array.isArray(data)?data:data.items;setEvents(list);await writeLocal('published-activity-list',list)}}catch(e){if(!cancelled){setError((e as Error).message);setEvents(await readLocal<ActivityDTO[]>('published-activity-list')||[])}}if(!cancelled)setLoaded(true);return}
 const [savedActivity,savedCap,local]=await Promise.all([readLocal<ActivityDTO>(snapshotKey),readLocal<PersonalCapability>(capKey),readLocal<PersonalDraft>(personalKey)]);if(cancelled)return;let identity=savedCap;const hash=new URLSearchParams(location.hash.slice(1));const token=hash.get('personal');const personId=hash.get('personId');if(token&&/^[a-f0-9]{64}$/.test(token)&&personId){identity={eventId,personId,token,operationId:operationId()};await writeLocal(capKey,identity);if(savedCap&&savedCap.personId!==personId){ref.current=null;setDraft(null)}}if(location.hash)history.replaceState(null,'',location.pathname+location.search);if(savedActivity&&savedActivity.id===eventId)setActivity(savedActivity);if(identity)setCap(identity);if(local&&local.eventId===eventId&&local.personId===identity?.personId){ref.current=local;setDraft(local);setName(local.plan.response.name);if(local.dirty)setStatus('未保存到云端')}const pois=query.get('poi');const session=query.get('session');setSelectedPoi(pois);setSelectedSession(session);if(query.get('group')){setGroupId(query.get('group'));setTab('companions')}if(query.get('plan'))setTab('plan');setLoaded(true);
 try{const fresh=await api<ActivityDTO>(`/events/${eventId}`);if(cancelled||fresh.id!==eventId)return;setActivity(fresh);setMapId(fresh.eventPackage.event.extensions?.convention.maps[0]?.id||'');await writeLocal(snapshotKey,fresh);if(identity?.personId){const remote=await api<PersonalDTO>(`/events/${eventId}/personal/${identity.personId}`,identity.token);if(cancelled)return;const next=receivePersonal(ref.current||undefined,remote);ref.current=next;setDraft(next);setName(next.plan.response.name);await writeLocal(personalKey,next);if(!next.dirty)setStatus('已保存到云端')}}catch(e){if(!cancelled){setError((e as Error).message);setStatus('未联网，已下载资料可继续查看')}}
 const resources=Array.from(new Set(caps.map(c=>c.groupId)));const found:GroupDTO[]=[];for(const id of resources){const c=caps.find(c=>c.groupId===id&&c.role==='member')||caps.find(c=>c.groupId===id)!;try{const g=await api<GroupDTO>(`/groups/${id}`,c.token);if(g.sourceEventId===eventId)found.push(g)}catch{/* a revoked local entry cannot expose a different group */}}if(!cancelled)setGroups(found)
 })().catch(e=>{if(!cancelled){setError((e as Error).message);setLoaded(true)}});return()=>{cancelled=true}},[eventId])
 useEffect(()=>{if(!draft?.dirty)return;const before=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};addEventListener('beforeunload',before);return()=>removeEventListener('beforeunload',before)},[draft?.dirty])
 async function createPersonal():Promise<PersonalDraft>{if(ref.current)return ref.current;if(!activity||!eventId)throw new Error('请先打开活动');let identity=cap||await readLocal<PersonalCapability>(capKey);if(!identity){identity={eventId,token:newToken(),operationId:operationId()};await writeLocal(capKey,identity);setCap(identity)}const pendingKey=`activity-personal-create:${eventId}`;let request=await readLocal<{personalToken:string;operationId:string;name:string}>(pendingKey);if(!identity.personId&&!request){request={personalToken:identity.token,operationId:identity.operationId,name};await writeLocal(pendingKey,request)}const remote=identity.personId?await api<PersonalDTO>(`/events/${eventId}/personal/${identity.personId}`,identity.token):await api<PersonalDTO>(`/events/${eventId}/personal`,undefined,request,'POST');if(active.current!==eventId)throw new Error('活动已切换');identity={...identity,personId:remote.id};await writeLocal(capKey,identity);setCap(identity);const next=receivePersonal(undefined,remote);ref.current=next;setDraft(next);await writeLocal(personalKey,next);await removeLocal(pendingKey);return next}
 async function ensurePersonal():Promise<PersonalDraft>{if(ref.current)return ref.current;if(!creationTask.current)creationTask.current=createPersonal().finally(()=>{creationTask.current=null});return creationTask.current}
 async function change(plan:PersonalPlan){try{const current=ref.current||await ensurePersonal();if(active.current!==eventId)return;const next={...current,plan,generation:current.generation+1,dirty:true};ref.current=next;setDraft(next);await writeLocal(personalKey,next);setStatus(navigator.onLine?'未保存到云端':'未联网，稍后保存')}catch(e){setError((e as Error).message)}}
 async function mutate(transform:(plan:PersonalPlan)=>PersonalPlan){try{const current=await ensurePersonal();await change(transform((ref.current||current).plan))}catch(e){setError((e as Error).message)}}
 async function save(){if(!activity||!eventId)return;setPending(true);try{const current=await ensurePersonal();const identity=cap||await readLocal<PersonalCapability>(capKey);if(!identity?.personId)throw new Error('个人入口尚未就绪');validateResponse(current.plan.response,activity.eventPackage.event);const key=`activity-submit:${eventId}:${identity.personId}`;let request=await readLocal<{operationId:string;expectedRevision:number;scheduleRevision:number;spatialRevision:number;plan:PersonalPlan}>(key);if(!request||JSON.stringify(request.plan)!==JSON.stringify(current.plan)||request.expectedRevision!==current.revision){request={operationId:operationId(),expectedRevision:current.revision,scheduleRevision:current.scheduleRevision,spatialRevision:current.spatialRevision,plan:current.plan};await writeLocal(key,request)}const remote=await api<PersonalDTO>(`/events/${eventId}/personal/${identity.personId}`,identity.token,request,'PUT');if(active.current!==eventId)return;const next=acknowledgePersonal(ref.current||current,remote,current.generation);ref.current=next;setDraft(next);await writeLocal(personalKey,next);await removeLocal(key);setConflict(false);setStatus(next.dirty?'上一版本已保存，新编辑尚未保存':'已保存到云端')}catch(e){setError((e as Error).message);if(e instanceof ApiFailure&&e.status===409)setConflict(true);setStatus(navigator.onLine?'未保存成功，本机草稿保留':'未联网，稍后保存')}finally{setPending(false)}}
 async function favorite(id:string){await mutate(plan=>({...plan,favorites:plan.favorites.some(f=>f.poiId===id)?plan.favorites.filter(f=>f.poiId!==id):[...plan.favorites,{poiId:id,visited:false}]}))}
 async function addRoute(poi:POI){if(!activity)return;await mutate(plan=>{const day=activity.eventPackage.event.days.some(d=>d.date===date)?date:activity.eventPackage.event.startDate;const r=plan.routes.find(r=>r.date===day)||{date:day,mapId:poi.position?.mapId,stops:[],spatialRevision:activity.spatialRevision};return r.stops.some(s=>s.poiId===poi.id)?plan:{...plan,routes:[...plan.routes.filter(r=>r.date!==day),{...r,stops:[...r.stops,{poiId:poi.id,visited:false}]}]}})}
 async function addSession(id:string){if(!activity)return;const a=activity.eventPackage.event.activities.find(a=>a.sessions.some(s=>s.id===id));const session=a?.sessions.find(s=>s.id===id);if(!session||!a)return;await mutate(plan=>plan.response.busy.some(b=>b.sessionId===id)?plan:{...plan,response:{...plan.response,busy:[...plan.response.busy,{id:operationId(),source:'session',sessionId:id,date:session.date,start:session.start,end:session.end,title:a.title,location:session.location}]}});setSelectedSession(null);setTab('plan');updateContext({session:undefined,view:'plan'})}
 async function createGroup(){if(!activity||!eventId)return;setPending(true);try{const key=`activity-create-group:${eventId}`;let request=await readLocal<{operationId:string;managerToken:string;inviteToken:string;creationCode:string;eventPackage:ActivityDTO['eventPackage'];sourceEventId:string;sourceEventRevision:number;title:string}>(key);if(!request||request.title!==(groupTitle||activity.eventPackage.event.title)){request={operationId:operationId(),managerToken:newToken(),inviteToken:newToken(),creationCode,eventPackage:activity.eventPackage,sourceEventId:eventId,sourceEventRevision:activity.revision,title:groupTitle||activity.eventPackage.event.title};await writeLocal(key,request)}const g=await api<GroupDTO>('/groups',undefined,request);await remember({groupId:g.id,role:'manager',token:request.managerToken,title:g.title});await remember({groupId:g.id,role:'invite',token:request.inviteToken,title:g.title});await removeLocal(key);setGroups([...groups.filter(x=>x.id!==g.id),g]);setGroupId(g.id);setCreateSheet(false);updateContext({group:g.id,view:'companions'})}catch(e){setError((e as Error).message)}finally{setPending(false)}}
 if(!eventId)return <div className="app-shell"><main className="page"><h1 className="page-title">同野·游</h1><p className="page-sub">活动</p><input className="input" aria-label="搜索活动" placeholder="搜索活动" value={search} onChange={e=>setSearch(e.target.value)}/>{error&&<p className="notice" role="alert">{error}</p>}{!loaded?<p className="page-sub">读取活动中…</p>:events.length===0?<div className="empty"><div className="empty-title">暂无公开活动</div><div className="empty-sub">管理员发布后会显示在这里</div></div>:<div className="sched-list" style={{marginTop:16}}>{events.filter(a=>a.eventPackage.event.title.toLowerCase().includes(search.trim().toLowerCase())).map(a=><button className="sched-row" key={a.id} onClick={()=>go(`/events/${a.id}`)}><span className="sched-main"><span className="sched-title">{a.eventPackage.event.title}</span><span className="sched-meta">{a.eventPackage.event.startDate}–{a.eventPackage.event.endDate} · {typeText[a.eventPackage.event.eventType||'generic']}{a.status==='cancelled'?' · 已取消':a.status==='archived'?' · 已归档':''}{a.eventPackage.event.location?` · ${a.eventPackage.event.location}`:''}</span></span><ChevronRight size={17}/></button>)}</div>}<button className="me-row" onClick={()=>go('/create')}><span className="me-row-label">发起日常活动</span><ChevronRight size={17}/></button><details><summary>本机最近小队</summary>{Array.from(new Set(caps.map(c=>c.groupId))).map(id=><button className="me-row" key={id} onClick={()=>go(`/groups/${id}`)}>{caps.find(c=>c.groupId===id)?.title||'小队'}<ChevronRight size={17}/></button>)}</details><button className="me-row" onClick={()=>go('/admin')}>管理员入口<ChevronRight size={17}/></button><button className="me-row" onClick={()=>location.assign('/help/index.html')}>帮助<ChevronRight size={17}/></button></main></div>
 if(!activity)return <div className="app-shell"><main className="page"><button className="icon-btn" aria-label="返回活动列表" onClick={()=>go('/')}><ArrowLeft size={20}/></button><h1 className="page-title">活动</h1><p role="alert" className="notice">{error||'读取活动中…'}</p><button className="btn btn-surface" onClick={()=>location.reload()}>重试</button></main></div>
 const event=activity.eventPackage.event;const convention=event.extensions?.convention;const pois=convention?.pois||[];const selected=pois.find(p=>p.id===selectedPoi);const matched=pois.filter(p=>{const needle=search.trim().toLowerCase().replace(/[-—\s]/g,'');const value=[p.name,p.boothCode,...p.tags||[]].join(' ').toLowerCase().replace(/[-—\s]/g,'');return value.includes(needle)});const isConvention=event.eventType==='comic_convention';const sessionActivity=event.activities.find(a=>a.sessions.some(s=>s.id===selectedSession));const session=sessionActivity?.sessions.find(s=>s.id===selectedSession);const plan=draft?.plan||blank(activity,name);
 return <div className="app-shell activity-personal"><div className="page"><button className="icon-btn activity-back" aria-label="切换活动" onClick={()=>go('/')}><ArrowLeft size={20}/></button><h1 className="page-title">{event.title}</h1><p className="page-sub">{event.startDate}–{event.endDate} · {event.timezone}</p>{error&&<p className="notice" role="alert">{error}</p>}{activity.status==='cancelled'&&<p className="notice">活动已取消，请核实安排。</p>}
 {tab==='browse'&&<><p>{event.description}</p>{event.location&&<p className="page-sub">{event.location}</p>}{activity.eventPackage.meta?.sourceNote&&<details><summary>资料来源</summary><p>{activity.eventPackage.meta.sourceNote}</p></details>}{isConvention&&<div className="activity-browse"><div className="activity-map-pane"><div className="field"><select className="select" aria-label="地图区域" value={mapId} onChange={e=>setMapId(e.target.value)}>{convention?.maps.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div>{!convention?.maps.length?<p className="notice">地图资料未提供，地点列表仍可使用。</p>:renderMap?renderMap(activity,mapId||convention.maps[0].id,selectedPoi||highlightPoi,plan.favorites.map(f=>f.poiId),id=>{setSelectedPoi(id);updateContext({poi:id})}):<p className="notice">地图暂时无法载入，请使用下方地点列表。</p>}</div><div className="activity-place-pane"><input className="input" aria-label="搜索地点" placeholder="名称、展位、标签" value={search} onChange={e=>setSearch(e.target.value)}/><div className="sched-list">{matched.map(p=><button className="sched-row" key={p.id} onClick={()=>{setSelectedPoi(p.id);updateContext({poi:p.id})}}><MapPin size={17}/><span className="sched-main"><span className="sched-title">{p.name}{p.closed?' · 已关闭':''}</span><span className="sched-meta">{[p.boothCode,...p.tags||[]].filter(Boolean).join(' · ')}</span></span>{plan.favorites.some(f=>f.poiId===p.id)&&<Heart size={16}/>}<ChevronRight size={16}/></button>)}</div>{matched.length===0&&<div className="empty"><div className="empty-sub">没有找到地点</div></div>}</div></div>}{event.activities.length>0&&<><h2 className="section-title">场次</h2>{event.activities.map(a=><div key={a.id}>{a.sessions.map(s=><button className="sched-row" key={s.id} onClick={()=>{setSelectedSession(s.id);updateContext({session:s.id})}}><span className="sched-time">{s.start}<span className="sched-time-end">{s.end}</span></span><span className="sched-main"><span className="sched-title">{a.title}</span><span className="sched-meta">{s.date}{s.poiId?` · ${pois.find(p=>p.id===s.poiId)?.name||'地点资料待核实'}`:''}</span></span><ChevronRight size={16}/></button>)}</div>)}</>}{event.activities.length===0&&!isConvention&&<p className="page-sub">可直接在计划里填写自己的时间。</p>}</>}
 {tab==='plan'&&<><PersonalPlanView activity={activity} plan={plan} date={date} onDateChange={day=>{setDate(day);updateContext({date:day})}} onChange={change} onSelectPoi={id=>{setSelectedPoi(id);updateContext({poi:id})}} onSave={save} status={status||'个人计划不要求先加入小队'} busy={pending} renderRouteMap={renderMap?(mapId,path)=>renderMap(activity,mapId,undefined,plan.favorites.map(f=>f.poiId),id=>setSelectedPoi(id),path):undefined}/>{conflict&&<button className="btn btn-surface btn-block" onClick={()=>setPersonalSheet(true)}>保留草稿，核对更新</button>}</>}
 {tab==='companions'&&(groupId?<><button className="btn btn-surface btn-sm" onClick={()=>{setGroupId(null);updateContext({group:undefined})}}>返回我的小队</button>{renderGroup(groupId,draft?.plan.response,eventId)}</>:<><p className="page-sub">个人计划不会自动分享，加入小队后再确认同步。</p>{groups.map(g=><button className="me-row" key={g.id} onClick={()=>{setGroupId(g.id);updateContext({group:g.id})}}><span className="me-row-label">{g.title}</span><ChevronRight size={17}/></button>)}{groups.length===0&&<div className="empty"><div className="empty-sub">还没有参加这个活动的小队</div></div>}<button className="btn btn-primary btn-block" onClick={()=>setCreateSheet(true)}>创建小队</button><p className="page-sub">收到邀请可直接打开邀请链接加入。</p></>)}
 {tab==='me'&&<><div className="me-row"><span className="me-row-label">怎么称呼</span><input className="input" aria-label="个人称呼" value={draft?.plan.response.name||name} maxLength={50} onChange={e=>{setName(e.target.value);if(draft)change({...draft.plan,response:{...draft.plan.response,name:e.target.value}})}}/></div><button className="me-row" onClick={()=>setPersonalSheet(true)}><span className="me-row-label"><Link2 size={17}/>恢复与导出</span><ChevronRight size={17}/></button><div className="me-row"><span className="me-row-label">外观</span><select className="select" aria-label="外观" value={theme} onChange={e=>setTheme(e.target.value)}><option value="auto">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></div><button className="me-row" onClick={async()=>{try{setPending(true);setStatus('正在下载活动与地图');const prepared=await prepareActivity(activity,'public');await writeLocal(snapshotKey,prepared.activity);if(draft)await writeLocal(personalKey,draft);setStatus(`离线资料已准备 · ${prepared.preparedAt}；个人草稿保留在此设备`);prepared.release();setPending(false)}catch(e){setPending(false);setError((e as Error).message)}}} disabled={pending}><span className="me-row-label"><Download size={17}/>为现场准备离线数据</span><ChevronRight size={17}/></button><p className="page-sub" role="status">{status}</p><button className="me-row" onClick={()=>location.assign('/help/index.html')}>帮助<ChevronRight size={17}/></button><button className="me-row" onClick={()=>location.assign('/help/event-json/index.html')}>活动资料格式<ChevronRight size={17}/></button><button className="me-row" onClick={async()=>{if(!confirm('仅移除此设备的活动入口和快照？云端计划保留。'))return;await removeLocal(capKey);await removeLocal(personalKey);await removeLocal(snapshotKey);setCap(null);ref.current=null;setDraft(null);go('/')}}>移除此设备入口<ChevronRight size={17}/></button></>}
 </div><TabBar items={[{key:'browse',label:isConvention?'逛展':'活动',icon:Map},{key:'plan',label:'计划',icon:CalendarDays},{key:'companions',label:'同行',icon:Users},{key:'me',label:'我的',icon:UserRound}]} value={tab} onChange={key=>{setTab(key);updateContext({view:key,poi:undefined,session:undefined})}}/>
 <Sheet open={selectedPoi!==null} title={selected?.name||'地点资料'} onClose={()=>{setSelectedPoi(null);updateContext({poi:undefined})}}>{selected?<><p className="page-sub">{[selected.boothCode,...selected.tags||[]].filter(Boolean).join(' · ')}</p>{selected.description&&<p>{selected.description}</p>}{selected.sourceNote&&<p className="page-sub">{selected.sourceNote}</p>}<div className="btn-row"><button className="btn btn-primary" onClick={()=>favorite(selected.id)}>{plan.favorites.some(f=>f.poiId===selected.id)?'取消收藏':'收藏'}</button><button className="btn btn-surface" onClick={()=>addRoute(selected)}>加入路线</button></div>{selected.position&&<button className="me-row" onClick={()=>{setMapId(selected.position!.mapId);setHighlightPoi(selected.id);setTab('browse');setSelectedPoi(null);updateContext({view:'browse',poi:undefined})}}>查看地图<ChevronRight size={17}/></button>}{event.activities.flatMap(a=>a.sessions.filter(s=>s.poiId===selected.id).map(s=><button className="sched-row" key={s.id} onClick={()=>{setSelectedPoi(null);setSelectedSession(s.id);updateContext({poi:undefined,session:s.id})}}>{a.title} · {s.date} {s.start}–{s.end}<ChevronRight size={16}/></button>))}<button className="btn btn-surface btn-block" style={{marginTop:16}} onClick={save}>保存个人计划</button><p className="page-sub" role="status">{status}</p></>:<p className="notice">地点资料已移除，收藏不会转移到同名地点。</p>}</Sheet>
 <Sheet open={selectedSession!==null} title={sessionActivity?.title||'场次'} onClose={()=>{setSelectedSession(null);updateContext({session:undefined})}}>{session?<><p>{session.date} {session.start}–{session.end}</p><p className="page-sub">加入安排不会替你完成官方预约。</p><button className="btn btn-primary btn-block" onClick={()=>addSession(session.id)}>加入个人安排</button>{session.poiId&&<button className="me-row" onClick={()=>{setSelectedSession(null);setSelectedPoi(session.poiId!);updateContext({session:undefined,poi:session.poiId})}}>查看地点<ChevronRight size={17}/></button>}</>:<p className="notice">场次资料已移除，请核对当前活动。</p>}</Sheet>
 <Sheet open={personalSheet} title="恢复与导出" onClose={()=>setPersonalSheet(false)}>{cap?.personId&&<button className="me-row" onClick={()=>download('个人恢复链接.txt',`${location.origin}/events/${eventId}#personal=${cap.token}&personId=${cap.personId}`)}>保存个人恢复链接<ChevronRight size={17}/></button>}<p className="page-sub">恢复链接等效于个人编辑权限，请私下保存。</p><button className="me-row" onClick={()=>download('tongye-personal-plan.json',{kind:'tongye.personal-plan',schemaVersion:1,eventId,plan})}>导出个人计划<ChevronRight size={17}/></button>{conflict&&cap?.personId&&draft&&<><button className="me-row" onClick={async()=>{try{download('cloud-personal-compare.json',await api(`/events/${eventId}/personal/${cap.personId}`,cap.token))}catch(e){setError((e as Error).message)}}}>下载云端计划比较<ChevronRight size={17}/></button><button className="btn btn-primary btn-block" onClick={async()=>{if(!confirm('我已核对当前活动和地图变化，保留本机计划并重新确认保存？'))return;try{const remote=await api<PersonalDTO>(`/events/${eventId}/personal/${cap.personId}`,cap.token);const next={...draft,revision:remote.revision,scheduleRevision:activity.scheduleRevision,spatialRevision:activity.spatialRevision};ref.current=next;setDraft(next);await writeLocal(personalKey,next);await removeLocal(`activity-submit:${eventId}:${cap.personId}`);setPersonalSheet(false);setStatus('已核对，请保存个人计划')}catch(e){setError((e as Error).message)}}}>已核对，保留草稿</button></>}</Sheet>
 <Sheet open={createSheet} title="创建小队" onClose={()=>setCreateSheet(false)}><div className="field"><label className="field-label">小队标题</label><input className="input" aria-label="小队标题" value={groupTitle} onChange={e=>setGroupTitle(e.target.value)} maxLength={100}/></div><div className="field"><label className="field-label">站点创建码</label><input className="input" aria-label="站点创建码" type="password" value={creationCode} onChange={e=>setCreationCode(e.target.value)}/></div><p className="page-sub">使用当前活动资料，个人计划不会自动提交给小队。</p><button className="btn btn-primary btn-block" disabled={pending} onClick={createGroup}>确认创建</button></Sheet>
 </div>
}
