import { Disclosure } from '../../ui/Disclosure'
import { useEffect, useState, type ReactNode } from 'react'
import { ChevronRight } from 'lucide-react'
import {FigmaAdminPreview} from './FigmaAdminPreview'
import {FigmaAdminTabs,type AdminSection} from './FigmaAdminTabs'
import { MapEditor } from './MapEditor'
import { Sheet } from '../../ui/Sheet'
import { api, ApiFailure } from '../api'
import { readLocal, writeLocal, removeLocal } from '../storage'
import { parseEventPackage } from '../../../shared/event-validation'
import type { EventPackage, EventActivity, TimeInterval } from '../../../shared/types'
import type { ActivityDTO, ConventionData, EventStatus, POI, POIKind } from '../../../shared/activity-contract'

export interface AdminMapsProps { eventPackage: EventPackage; onChange: (pack: EventPackage) => void; eventId: string; token: string }
interface Props { headerActions?: ReactNode; token: string; onError: (message: string) => void; onExpired?: () => void; renderMaps?: (props: AdminMapsProps) => ReactNode }
const emptyConvention = (): ConventionData => ({ maps: [], pois: [], routingGraphs: [] })
const statusNames: Record<EventStatus, string> = { draft: '草稿', published: '已发布', archived: '已归档', cancelled: '已取消' }
const kinds: Record<POIKind,string> = { booth:'摊位',stage:'舞台',entrance:'入口',exit:'出口',service:'服务台',toilet:'卫生间',food:'餐饮',medical:'医疗点',rest:'休息区',meeting:'集合点' }
const uid = () => crypto.randomUUID()
function blank(): EventPackage { return {kind:'coukong.event',schemaVersion:2,event:{id:`event-${uid()}`,eventType:'generic',title:'',timezone:'Asia/Shanghai',startDate:'2026-10-03',endDate:'2026-10-03',defaultBufferMinutes:0,defaultMinSlotMinutes:30,defaultSelectionStepMinutes:15,days:[{date:'2026-10-03',openIntervals:[{start:'09:00',end:'21:00'}]}],activities:[]}} }
function dates(start:string,end:string): string[] { if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end))return [];const a=Date.parse(start+'T00:00:00Z'),b=Date.parse(end+'T00:00:00Z');if(!Number.isFinite(a)||!Number.isFinite(b)||b<a||b-a>30*86400000)return [];return Array.from({length:(b-a)/86400000+1},(_,i)=>new Date(a+i*86400000).toISOString().slice(0,10)) }
function saveFile(pack:EventPackage){const url=URL.createObjectURL(new Blob([JSON.stringify(pack,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='event-package.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function changes(before:EventPackage|undefined,after:EventPackage):string[] {
 const summaries:string[]=[]
 function compare(label:string,old: {id:string}[],next:{id:string}[]){const prior=new Map(old.map(x=>[x.id,x]));const current=new Map(next.map(x=>[x.id,x]));const added=next.filter(x=>!prior.has(x.id)).length,removed=old.filter(x=>!current.has(x.id)).length,modified=next.filter(x=>prior.has(x.id)&&JSON.stringify(prior.get(x.id))!==JSON.stringify(x)).length;if(added||removed||modified)summaries.push(`${label}：新增 ${added}，修改 ${modified}，移除 ${removed}`)}
 compare('场次',before?.event.activities.flatMap(a=>a.sessions)??[],after.event.activities.flatMap(a=>a.sessions));const a=before?.event.extensions?.convention,b=after.event.extensions?.convention;compare('地点',a?.pois??[],b?.pois??[]);compare('地图',a?.maps??[],b?.maps??[]);compare('通道',a?.routingGraphs.flatMap(g=>g.edges)??[],b?.routingGraphs.flatMap(g=>g.edges)??[])
 if(before&&(before.event.startDate!==after.event.startDate||before.event.endDate!==after.event.endDate||before.event.timezone!==after.event.timezone||JSON.stringify(before.event.days)!==JSON.stringify(after.event.days)))summaries.push('活动日期、时区或开放时间有变化，请核对个人计划。')
 return summaries
}
function IntervalFields({value,onChange}:{value:TimeInterval[];onChange:(v:TimeInterval[])=>void}) {return <>{value.map((v,i)=><div className="interval" key={i}><input className="input" aria-label={`开放开始 ${i+1}`} value={v.start} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,start:e.target.value}:x))}/><span>至</span><input className="input" aria-label={`开放结束 ${i+1}`} value={v.end} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,end:e.target.value}:x))}/><button className="btn btn-surface" aria-label={`移除开放时段 ${i+1}`} onClick={()=>onChange(value.filter((_,j)=>j!==i))}>移除</button></div>)}<button className="btn btn-surface" onClick={()=>onChange([...value,{start:'13:00',end:'18:00'}])}>添加开放时段</button></>}
export function AdminActivity({token,onError,onExpired,renderMaps,headerActions}:Props){
 const [section,setSection]=useState<AdminSection>('info'),[view,setView]=useState<'edit'|'preview'>('edit')
 const [items,setItems]=useState<ActivityDTO[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[pack,setPack]=useState<EventPackage|null>(null),[target,setTarget]=useState<ActivityDTO|null>(null),[baseRevision,setBaseRevision]=useState(0),[status,setStatus]=useState<EventStatus>('draft'),[screen,setScreen]=useState<'edit'|'session'|'poi'|'json'|'preview'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[raw,setRaw]=useState(''),[session,setSession]=useState<EventActivity|null>(null),[poi,setPoi]=useState<POI|null>(null),[undoPOI,setUndoPOI]=useState<POI|null>(null)
 function fail(e:unknown){const message=(e as Error).message;setError(message);setConflict(e instanceof ApiFailure&&e.status===409);onError(message);if(e instanceof ApiFailure&&e.status===401)onExpired?.()}
 async function load(){setLoading(true);setLoadError('');try{setItems(await api<ActivityDTO[]>('/admin/events',token))}catch(e){setLoadError((e as Error).message);fail(e)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[token])
 const draftKey=pack?`admin-activity-draft:${pack.event.id}`:''
 function change(next:EventPackage){setPack(next);setError('');void writeLocal(`admin-activity-draft:${next.event.id}`,{pack:next,status,expectedRevision:baseRevision})}
 function event(patch:Partial<EventPackage['event']>){if(pack)change({...pack,schemaVersion:2,event:{...pack.event,eventType:pack.event.eventType??'generic',...patch}})}
 async function open(item:ActivityDTO|null){setTarget(item);setStatus(item?.status??'draft');const newId=!item?await readLocal<string>('admin-activity-new-id'):null;const initial=item?.eventPackage??blank();const id=item?.id??newId??initial.event.id;const stored=await readLocal<{pack:EventPackage;status:EventStatus;expectedRevision:number}>(`admin-activity-draft:${id}`);setPack(stored?.pack??initial);setBaseRevision(stored?.expectedRevision??item?.revision??0);if(stored)setStatus(stored.status);if(!item)await writeLocal('admin-activity-new-id',stored?.pack.event.id??initial.event.id);setSection('info');setView('edit');setScreen('edit');setError('');setConflict(false)}

 function convention(next:ConventionData){if(pack)event({extensions:{convention:next}})}
 function preview(nextStatus:EventStatus=status){if(!pack)return;try{const valid=parseEventPackage(JSON.stringify(pack));setPack(valid);setStatus(nextStatus);void writeLocal(draftKey,{pack:valid,status:nextStatus,expectedRevision:baseRevision});setError('');setScreen('preview')}catch(e){fail(e)}}
 async function commit(){if(!pack||busy)return;setBusy(true);try{const body={eventPackage:pack,status,expectedRevision:baseRevision};const key=`pending-admin-event:${pack.event.id}`;let request=await readLocal<typeof body & {operationId:string}>(key);if(!request||JSON.stringify({eventPackage:request.eventPackage,status:request.status,expectedRevision:request.expectedRevision})!==JSON.stringify(body)){request={...body,operationId:uid()};await writeLocal(key,request)}await api<ActivityDTO>('/admin/events',token,request);await removeLocal(key);await removeLocal(draftKey);if(!target)await removeLocal('admin-activity-new-id');setScreen(null);setPack(null);await load()}catch(e){fail(e)}finally{setBusy(false)}}
 const ext=pack?.event.extensions?.convention??emptyConvention()
 return <><header className="page-heading"><h1 className="page-title">活动管理</h1>{headerActions}</header>{loading?<p role="status">正在读取活动…</p>:loadError?<section className="card online-section"><p role="alert">{loadError}</p><button className="btn btn-surface" onClick={()=>void load()}>重试读取</button></section>:<section className="card online-section">{items.length===0&&<p className="page-sub">还没有活动，先建立一场。</p>}{items.map(item=><button className="me-row" key={item.id} onClick={()=>void open(item)}><span className="sched-main"><span className="sched-title">{item.eventPackage.event.title}</span><span className="sched-meta">{statusNames[item.status]} · {item.eventPackage.event.startDate} · 第 {item.revision} 版</span></span><ChevronRight size={18}/></button>)}<button className="btn btn-primary" onClick={()=>void open(null)}>新建活动</button></section>}
 <Sheet open={!!screen} title={screen==='session'?'编辑场次':screen==='poi'?'编辑地点':screen==='json'?'活动文件':screen==='preview'?'确认活动资料':'编辑活动'} onClose={()=>setScreen(null)}>{error&&<p role="alert">{error}</p>}{conflict&&pack&&<button className="btn btn-surface" disabled={busy} onClick={async()=>{try{const latest=(await api<ActivityDTO[]>('/admin/events',token)).find(i=>i.id===pack.event.id);if(!latest){setError('当前活动无法读取，请保留草稿并重试。');return}if(confirm(`云端已是第 ${latest.revision} 版。保留本机编辑，核对后以此版本重新保存？`)){setTarget(latest);setBaseRevision(latest.revision);await writeLocal(draftKey,{pack,status,expectedRevision:latest.revision});setConflict(false);setError('已保留本机内容，请核对后再次预览保存。');setScreen('edit')}}catch(e){fail(e)}}}>读取最新版本并核对</button>}{pack&&screen==='edit'&&<>
 <div className="figma-admin-workbench-head"><div className="figma-admin-context"><span className="page-sub">管理员 · {statusNames[status]}</span><strong title={pack.event.title}>{pack.event.title||'新活动'}</strong><span className="figma-badge is-warning">本机编辑</span></div><div className="segmented figma-admin-view" aria-label="工作台模式">{(['edit','preview'] as const).map(mode=><button key={mode} className={view===mode?'on':''} aria-pressed={view===mode} onClick={()=>setView(mode)}>{mode==='edit'?'编辑':'预览'}</button>)}</div></div><FigmaAdminTabs value={section} onChange={setSection} convention={pack.event.eventType==='comic_convention'}/><div className="figma-admin-panel">{view==='preview'?<FigmaAdminPreview pack={pack} section={section}/>:<>{section==='info'&&<>
 <label>活动类型<select className="select" value={pack.event.eventType??'generic'} onChange={e=>{const type=e.target.value as 'generic'|'comic_convention';if(pack.event.eventType!==type&&pack.event.extensions&&!confirm('切换类型后保留地图、地点和通道资料，通用活动中暂不显示。继续？'))return;event({eventType:type,...(type==='comic_convention'&&!pack.event.extensions?{extensions:{convention:emptyConvention()}}:{})})}}><option value="generic">通用活动</option><option value="comic_convention">漫展</option></select></label>
 <label>活动名称<input className="input" maxLength={100} value={pack.event.title} onChange={e=>event({title:e.target.value})}/></label><label>简介<textarea className="input" maxLength={5000} value={pack.event.description??''} onChange={e=>event({description:e.target.value})}/></label>
 <label>开始日期<input className="input" type="date" value={pack.event.startDate} onChange={e=>event({startDate:e.target.value})}/></label><label>结束日期<input className="input" type="date" value={pack.event.endDate} onChange={e=>event({endDate:e.target.value})}/></label><label>活动时区<input className="input" value={pack.event.timezone} onChange={e=>event({timezone:e.target.value})}/></label>
 <button className="btn btn-surface" onClick={()=>{const range=dates(pack.event.startDate,pack.event.endDate);if(!range.length){setError('日期必须有效，范围最多31天。');return}if(pack.event.days.some(d=>!range.includes(d.date))&&!confirm('日期范围外的开放时段将移出活动，场次仍保留，请随后核对。继续？'))return;event({days:range.map(date=>pack.event.days.find(d=>d.date===date)??{date,openIntervals:[{start:'09:00',end:'21:00'}]})})}}>应用日期范围</button>
 <Disclosure title={<>每日开放时间</>}>{pack.event.days.map(d=><section key={d.date}><h3>{d.date}</h3><IntervalFields value={d.openIntervals} onChange={openIntervals=>event({days:pack.event.days.map(x=>x.date===d.date?{...x,openIntervals}:x)})}/></section>)}</Disclosure>
 <label>地点<input className="input" maxLength={200} value={pack.event.location??''} onChange={e=>event({location:e.target.value})}/></label><label>资料来源<textarea className="input" maxLength={1000} value={pack.meta?.sourceNote??''} onChange={e=>change({...pack,meta:{...pack.meta,sourceNote:e.target.value}})}/></label>
 </>}
 {section==='session'&&<>
 <Disclosure title={<>活动场次 · {pack.event.activities.reduce((n,a)=>n+a.sessions.length,0)}</>}>{pack.event.activities.map(a=><button className="me-row" key={a.id} onClick={()=>{setSession(structuredClone(a));setScreen('session')}}><span className="sched-main"><span className="sched-title">{a.title}</span><span className="sched-meta">{a.sessions.map(s=>`${s.date} ${s.start}–${s.end}`).join('；')}</span></span><ChevronRight size={18}/></button>)}<button className="btn btn-surface" onClick={()=>{setSession({id:`activity-${uid()}`,title:'',sessions:[{id:`session-${uid()}`,date:pack.event.startDate,start:'13:07',end:'13:52'}]});setScreen('session')}}>添加场次</button></Disclosure>
 </>}
 {pack.event.eventType==='comic_convention'&&section==='booth'&&<><Disclosure title={<>摊位与设施 · {ext.pois.length}</>}>{ext.pois.map(p=><button className="me-row" key={p.id} onClick={()=>{setPoi(structuredClone(p));setScreen('poi')}}><span className="sched-main"><span className="sched-title">{p.name}</span><span className="sched-meta">{kinds[p.kind]} {p.boothCode} {!p.position?'· 未标位置':''}</span></span><ChevronRight size={18}/></button>)}<button className="btn btn-surface" onClick={()=>{setPoi({id:`poi-${uid()}`,name:'',kind:'booth'});setScreen('poi')}}>添加地点</button>{undoPOI&&<button className="btn btn-surface" onClick={()=>{convention({...ext,pois:[...ext.pois,undoPOI]});setUndoPOI(null)}}>撤销删除地点</button>}</Disclosure></>}
 {pack.event.eventType==='comic_convention'&&section==='map'&&<>{target?(renderMaps?renderMaps({eventPackage:pack,onChange:change,eventId:target.id,token}):<MapEditor eventPackage={pack} onChange={change} eventId={target.id} token={token}/>):<p className="page-sub">先保存活动，再上传地图和标注通道。</p>}</>}
 {section==='info'&&<>
 <Disclosure title={<>更多设置</>}><label>默认缓冲（分钟）<input className="input" type="number" min={0} max={120} value={pack.event.defaultBufferMinutes} onChange={e=>event({defaultBufferMinutes:Number(e.target.value)})}/></label><label>默认最短空闲（分钟）<input className="input" type="number" min={1} max={240} value={pack.event.defaultMinSlotMinutes} onChange={e=>event({defaultMinSlotMinutes:Number(e.target.value)})}/></label><label>选择步长<select className="select" value={pack.event.defaultSelectionStepMinutes} onChange={e=>event({defaultSelectionStepMinutes:Number(e.target.value) as 5|10|15|30})}>{[5,10,15,30].map(v=><option key={v} value={v}>{v}分钟</option>)}</select></label></Disclosure>
 </>}</>}</div>
 {view==='edit'&&<><div className="figma-admin-controls"> <label>活动状态<select className="select" value={status} onChange={e=>{const value=e.target.value as EventStatus;setStatus(value);void writeLocal(draftKey,{pack,status:value,expectedRevision:baseRevision})}}>{Object.entries(statusNames).map(([v,name])=><option key={v} value={v}>{name}</option>)}</select></label><button className="btn btn-surface" onClick={()=>{setRaw(JSON.stringify(pack,null,2));setScreen('json')}}>导入或导出活动文件</button></div><div className="figma-admin-save"><div className="figma-admin-actions"><button className="btn btn-surface" disabled={busy} onClick={()=>preview('draft')}>保存草稿</button><button className="btn btn-primary" disabled={busy} onClick={()=>preview(status==='cancelled'||status==='archived'?status:'published')}>{status==='cancelled'||status==='archived'?'预览保存':'发布'}</button></div><p className="page-sub">修改先保存在本机，确认保存后才更新公开资料。</p></div></>}
 </>}
 {pack&&screen==='session'&&session&&<><label>场次名称<input className="input" value={session.title} onChange={e=>setSession({...session,title:e.target.value})}/></label>{session.sessions.map((s,i)=><section key={s.id}><label>日期<input className="input" type="date" value={s.date} onChange={e=>setSession({...session,sessions:session.sessions.map((x,j)=>j===i?{...x,date:e.target.value}:x)})}/></label><label>开始时间<input className="input" value={s.start} onChange={e=>setSession({...session,sessions:session.sessions.map((x,j)=>j===i?{...x,start:e.target.value}:x)})}/></label><label>结束时间<input className="input" value={s.end} onChange={e=>setSession({...session,sessions:session.sessions.map((x,j)=>j===i?{...x,end:e.target.value}:x)})}/></label><label>关联地点<select className="select" value={s.poiId??''} onChange={e=>{const next={...s};if(e.target.value)next.poiId=e.target.value;else delete next.poiId;setSession({...session,sessions:session.sessions.map((x,j)=>j===i?next:x)})}}><option value="">暂未确定</option>{ext.pois.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="btn btn-surface" onClick={()=>setSession({...session,sessions:session.sessions.filter((_,j)=>j!==i)})}>移除这段场次</button></section>)}<button className="btn btn-surface" onClick={()=>setSession({...session,sessions:[...session.sessions,{id:`session-${uid()}`,date:pack.event.startDate,start:'13:07',end:'13:52'}]})}>再加一段</button><button className="btn btn-primary" onClick={()=>{if(!session.title.trim()||!session.sessions.length){setError('请填写场次名称并保留至少一段时间。');return}event({activities:pack.event.activities.some(a=>a.id===session.id)?pack.event.activities.map(a=>a.id===session.id?session:a):[...pack.event.activities,session]});setScreen('edit')}}>完成场次</button><button className="btn btn-surface" onClick={()=>setScreen('edit')}>取消编辑场次</button>{pack.event.activities.some(a=>a.id===session.id)&&<button className="btn btn-danger" onClick={()=>{if(confirm('移除场次后，使用它的安排需要重新核对。继续？')){event({activities:pack.event.activities.filter(a=>a.id!==session.id)});setScreen('edit')}}}>移除此场次</button>}</>}
 {pack&&screen==='poi'&&poi&&<><label>地点名称<input className="input" value={poi.name} onChange={e=>setPoi({...poi,name:e.target.value})}/></label><label>类别<select className="select" value={poi.kind} onChange={e=>setPoi({...poi,kind:e.target.value as POIKind})}>{Object.entries(kinds).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>展位编号<input className="input" value={poi.boothCode??''} onChange={e=>setPoi({...poi,boothCode:e.target.value})}/></label><label>标签（逗号分隔）<input className="input" value={poi.tags?.join(',')??''} onChange={e=>setPoi({...poi,tags:e.target.value.split(/[,，]/).map(t=>t.trim()).filter(Boolean)})}/></label><label>地点说明<textarea className="input" value={poi.description??''} onChange={e=>setPoi({...poi,description:e.target.value})}/></label><label>地点来源<textarea className="input" value={poi.sourceNote??''} onChange={e=>setPoi({...poi,sourceNote:e.target.value})}/></label><label>所属地图<select className="select" value={poi.position?.mapId??''} onChange={e=>{const map=ext.maps.find(m=>m.id===e.target.value);if(map)setPoi({...poi,position:{mapId:map.id,mapRevision:map.revision,x:poi.position?.x??0.5,y:poi.position?.y??0.5}});else {const next={...poi};delete next.position;setPoi(next)}}}><option value="">未标位置</option>{ext.maps.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label>{poi.position&&<><label>横向位置（0–1）<input className="input" type="number" min={0} max={1} step="0.001" value={poi.position.x} onChange={e=>setPoi({...poi,position:{...poi.position!,x:Number(e.target.value)}})}/></label><label>纵向位置（0–1）<input className="input" type="number" min={0} max={1} step="0.001" value={poi.position.y} onChange={e=>setPoi({...poi,position:{...poi.position!,y:Number(e.target.value)}})}/></label></>}
 <label>通道连接点<select className="select" value={poi.routeNodeId??''} onChange={e=>{const next={...poi};if(e.target.value)next.routeNodeId=e.target.value;else delete next.routeNodeId;setPoi(next)}}><option value="">尚未连接</option>{ext.routingGraphs.filter(g=>g.mapId===poi.position?.mapId).flatMap(g=>g.nodes).map((n,i)=><option key={n.id} value={n.id}>节点 {i+1}</option>)}</select></label><label><input type="checkbox" checked={poi.closed??false} onChange={e=>setPoi({...poi,closed:e.target.checked})}/> 暂时关闭</label><button className="btn btn-primary" onClick={()=>{if(!poi.name.trim()){setError('请填写地点名称。');return}convention({...ext,pois:ext.pois.some(p=>p.id===poi.id)?ext.pois.map(p=>p.id===poi.id?poi:p):[...ext.pois,poi]});setScreen('edit')}}>完成地点</button><button className="btn btn-surface" onClick={()=>setScreen('edit')}>取消编辑地点</button>{ext.pois.some(p=>p.id===poi.id)&&<button className="btn btn-danger" onClick={()=>{if(confirm('删除后收藏和路线会显示该地点已失效。继续？')){setUndoPOI(poi);convention({...ext,pois:ext.pois.filter(p=>p.id!==poi.id)});setScreen('edit')}}}>删除地点</button>}</>}
 {pack&&screen==='json'&&<><label>上传 JSON<input className="input" type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1024*1024){setError('活动文件最多1 MiB。');return}setRaw(await f.text())}}/></label><label>或粘贴 JSON<textarea className="input" rows={10} value={raw} onChange={e=>setRaw(e.target.value)}/></label><button className="btn btn-primary" onClick={()=>{try{const valid=parseEventPackage(raw);if(target&&valid.event.id!==target.eventPackage.event.id){setError('导入的活动标识与当前活动不同。请从新建活动入口导入。');return}change(valid);setSection('info');setView('edit');setScreen('edit')}catch(e){fail(e)}}}>校验并使用</button><button className="btn btn-surface" onClick={()=>saveFile(pack)}>导出活动 JSON</button><p className="page-sub">JSON包含地图引用，不包含地图图片。地图文件需单独准备。</p><button className="btn btn-surface" onClick={()=>setScreen('edit')}>返回编辑</button><a href="/help/event-json/">格式与示例</a></>}
 {pack&&screen==='preview'&&<><h2>{pack.event.title}</h2><p>{pack.event.startDate} 至 {pack.event.endDate} · {pack.event.timezone}</p><p>{statusNames[status]} · {pack.event.activities.reduce((n,a)=>n+a.sessions.length,0)} 个场次 · {ext.pois.length} 个地点</p>{changes(target?.eventPackage,pack).map(text=><p key={text}>{text}</p>)}{pack.meta?.sourceNote&&<p>{pack.meta.sourceNote}</p>}{pack.meta?.isExample&&<p>这是示例资料，请勿冒充官方安排。</p>}{status==='draft'&&target&&<p className="page-sub">保存草稿不会替换已公开版本。检查后选择“已发布”再保存。</p>}<p className="page-sub">发布不代表来源已经核实。活动时间变化需要使用者重新确认，地图与通道变化需要重新检查路线。</p>{target&&<p className="page-sub">本次在第 {baseRevision} 版基础上保存；已有小队的活动快照不会被悄悄覆盖。</p>}{status==='cancelled'&&<p role="alert">活动将标记为取消，已使用该活动的人会看到取消提醒。</p>}<button className="btn btn-primary" disabled={busy} onClick={()=>void commit()}>{busy?'正在保存…':'确认保存'}</button><button className="btn btn-surface" disabled={busy} onClick={()=>setScreen('edit')}>继续编辑</button></>}
 </Sheet></>
}
