import {useEffect,useRef,useState} from 'react'
import {Clock,ChevronRight,Minus,Plus} from 'lucide-react'
import type {TimeInterval} from '../../../shared/types'
import {readLocal,writeLocal,removeLocal} from '../storage'
import {editableMinute,shiftedClock} from './figma-time-controls'

// Missing date: not answered. An explicit empty date: cannot attend.
export function FigmaPresenceSummary({intervals,state='draft',onClick}:{intervals:TimeInterval[]|undefined;state?:'draft'|'confirmed'|'review';onClick:()=>void}){
 const known=intervals!==undefined
 return <button className="figma-presence-summary" onClick={onClick}><span className="figma-presence-copy"><span className="figma-presence-label"><Clock size={15}/>本日在场时间{known&&<span className={`figma-badge ${state==='review'?'is-warning':state==='confirmed'?'is-accent':''}`}>{state==='review'?'资料变动，需复核':state==='confirmed'?'已确认':'未同步'}</span>}</span><span className="figma-presence-value">{!known?'尚未确认，点此设置':intervals.length?intervals.map(i=>`${i.start}–${i.end}`).join('、'):'不能参加'}</span></span><ChevronRight size={18}/></button>
}
interface EditorDraft{state:'present'|'absent';slots:TimeInterval[];step:number}
export function FigmaPresenceEditor({intervals,defaultInterval,selectionStep=15,storageKey,onSave}:{intervals:TimeInterval[]|undefined;defaultInterval?:TimeInterval;selectionStep?:number;storageKey:string;onSave:(intervals:TimeInterval[])=>Promise<void|boolean>}){
 const [draft,setDraft]=useState<EditorDraft>({state:intervals?.length===0?'absent':'present',slots:intervals?.length?intervals.map(i=>({...i})):[defaultInterval||{start:'13:00',end:'14:00'}],step:[5,10,15,30].includes(selectionStep)?selectionStep:15})
 const [ready,setReady]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const current=useRef(draft),writes=useRef(Promise.resolve()),mounted=useRef(true)
 useEffect(()=>{let cancelled=false;mounted.current=true;void readLocal<EditorDraft>(storageKey).then(saved=>{if(cancelled)return;if(saved&&['present','absent'].includes(saved.state)&&Array.isArray(saved.slots)&&saved.slots.length>=1&&saved.slots.length<=24&&saved.slots.every(i=>typeof i.start==='string'&&typeof i.end==='string')&&[5,10,15,30].includes(saved.step)){current.current=saved;setDraft(saved)}setReady(true)}).catch(e=>{if(!cancelled){setError(`本机草稿未能读取：${(e as Error).message}`)}});return()=>{cancelled=true;mounted.current=false}},[storageKey])
 function edit(next:EditorDraft){current.current=next;setDraft(next);const queued=writeLocal(storageKey,next,writes.current.catch(()=>{}));writes.current=queued;void queued.then(()=>{if(mounted.current)setError('')},e=>{if(mounted.current)setError(`本机草稿未能保存：${(e as Error).message}`)})}
 const valid=draft.slots.length>0&&draft.slots.every(i=>{const s=editableMinute(i.start),e=editableMinute(i.end,true);return s!==null&&e!==null&&e>s})
 const update=(n:number,key:'start'|'end',value:string)=>edit({...current.current,slots:current.current.slots.map((i,k)=>k===n?{...i,[key]:value}:i)})
 async function save(){setSaving(true);setError('');try{await writes.current;const captured=current.current;if(await onSave(captured.state==='absent'?[]:captured.slots.map(i=>({...i})))===false)throw new Error('尚未保存，编辑稿已保留');await removeLocal(storageKey)}catch(e){if(mounted.current)setError((e as Error).message)}finally{if(mounted.current)setSaving(false)}}
 return <div className="figma-presence-editor"><fieldset disabled={!ready||saving}><div className="segmented figma-presence-segment" aria-label="在场状态">{(['present','absent'] as const).map(state=><button key={state} className={draft.state===state?'on':''} aria-pressed={draft.state===state} onClick={()=>edit({...current.current,state})}>{state==='present'?'在场':'不能参加'}</button>)}</div>{draft.state==='present'&&<><div className="figma-presence-slots">{draft.slots.map((i,n)=><section className="figma-presence-slot" key={n}><div className="figma-presence-slot-head"><span>时段 {n+1}</span>{draft.slots.length>1&&<button className="figma-presence-delete" aria-label={`删除时段 ${n+1}`} onClick={()=>edit({...current.current,slots:current.current.slots.filter((_,k)=>k!==n)})}>删除</button>}</div><div className="figma-presence-fields">{(['start','end'] as const).map(key=>{const label=`${key==='start'?'开始':'结束'}时间 ${n+1}`;return <div className="figma-presence-field" key={key}><label><span>{key==='start'?'开始':'结束'}</span><input aria-label={label} inputMode="numeric" value={i[key]} aria-invalid={editableMinute(i[key],key==='end')===null} onChange={e=>update(n,key,e.target.value)}/></label><div className="figma-presence-nudges">{[-draft.step,draft.step].map(delta=>{const next=shiftedClock(i[key],delta,key==='end');return <button key={delta} disabled={next===null} aria-label={`${label}${delta<0?'提前':'推迟'}${draft.step}分钟`} onClick={()=>{if(next!==null)update(n,key,next)}}>{delta<0?<Minus size={12}/>:<Plus size={12}/>} {draft.step}</button>})}</div></div>})}</div><p className="figma-presence-step-label">快捷步长</p><div className="figma-presence-steps">{[5,10,15,30].map(step=><button key={step} className={draft.step===step?'on':''} aria-pressed={draft.step===step} onClick={()=>edit({...current.current,step})}>{step} 分</button>)}</div></section>)}</div><button className="btn btn-subtle btn-block figma-presence-add" disabled={draft.slots.length>=24} onClick={()=>edit({...current.current,slots:[...current.current.slots,{start:'13:00',end:'14:00'}]})}><Plus size={16}/>添加时段</button>{!valid&&<p className="notice" role="alert">请输入正确的 HH:mm 格式，且结束晚于开始；结束可填 24:00。</p>}</>}{error&&<p className="notice" role="alert">{error}</p>}<button className="btn btn-primary btn-block figma-presence-save" disabled={!ready||saving||draft.state==='present'&&!valid} onClick={save}>{saving?'保存中…':'保存'}</button></fieldset></div>
}
