import {Star,ChevronRight,Trash2} from 'lucide-react'
import type {ActivityDTO,PersonalPlan,POI} from '../../../shared/activity-contract'

type Favorite=PersonalPlan['favorites'][number]
export function FigmaFavorites({activity,plan,date,items,onSelect,onVisited,onRoute,onRemove}:{activity:ActivityDTO;plan:PersonalPlan;date:string;items:Favorite[];onSelect:(id:string)=>void;onVisited:(id:string)=>void;onRoute:(poi:POI)=>void;onRemove:(id:string)=>void}){
 const event=activity.eventPackage.event,pois=event.extensions?.convention.pois||[],route=plan.routes.find(r=>r.date===date)
 if(!plan.favorites.length)return <div className="empty"><Star size={24} aria-hidden="true"/><div className="empty-title">还没有收藏</div><div className="empty-sub">收藏不会自动加入日程或路线</div></div>
 if(!items.length)return <p className="page-sub">没有符合条件的收藏</p>
 return <div className="figma-favorite-list">{items.map(f=>{const poi=pois.find(p=>p.id===f.poiId),sessions=event.activities.flatMap(a=>a.sessions.filter(s=>s.poiId===f.poiId)),scheduled=plan.response.busy.some(b=>sessions.some(s=>s.id===b.sessionId)),position=route?.stops.findIndex(s=>s.poiId===f.poiId)??-1;return <div className="figma-favorite-entry" key={f.poiId}><button className="me-row personal-row-main" aria-label={poi?.name||'地点已移除'} onClick={()=>onSelect(f.poiId)}><Star size={17} fill="currentColor" className="figma-favorite-star"/><span className="me-row-label"><span className="sched-title">{poi?.name||'地点已移除'}</span><span className="sched-meta">{[poi?.boothCode,poi?.closed?'已关闭':undefined,position>=0?`今日路线第 ${position+1} 站`:'未加入今日路线',scheduled?'已排日程':'未排日程',f.visited?'去过':undefined].filter(Boolean).join(' · ')}</span></span><ChevronRight size={16}/></button><div className="figma-favorite-tools"><button className={`chip ${f.visited?'on':''}`} aria-pressed={f.visited} onClick={()=>onVisited(f.poiId)}>{f.visited?'去过':'标记去过'}</button>{poi&&<button className="chip" disabled={poi.closed||position>=0} onClick={()=>onRoute(poi)}>{position>=0?'已加入今日路线':'加入路线'}</button>}<button className="icon-btn" aria-label={`取消收藏 ${poi?.name||'地点已移除'}`} onClick={()=>onRemove(f.poiId)}><Trash2 size={17}/></button></div></div>})}</div>
}
