import {Star,CalendarDays,Route,MapPin,ChevronRight} from 'lucide-react'
import type {ActivityDTO,PersonalPlan,POI} from '../../../shared/activity-contract'
import {dateCn} from './fmt'

interface Props{activity:ActivityDTO;poi:POI;plan:PersonalPlan;date:string;onFavorite:()=>void;onSchedule:()=>void;onRoute:()=>void;onMap:()=>void;onSession:(id:string)=>void}
export function FigmaPoiDetails({activity,poi,plan,date,onFavorite,onSchedule,onRoute,onMap,onSession}:Props){
 const convention=activity.eventPackage.event.extensions?.convention,map=convention?.maps.find(m=>m.id===poi.position?.mapId)
 const favorite=plan.favorites.some(f=>f.poiId===poi.id),routeIndex=plan.routes.find(r=>r.date===date)?.stops.findIndex(s=>s.poiId===poi.id)??-1
 const sessions=activity.eventPackage.event.activities.flatMap(a=>a.sessions.filter(s=>s.poiId===poi.id).map(s=>({...s,title:a.title})))
 const scheduled=plan.response.busy.some(b=>sessions.some(s=>s.id===b.sessionId))
 return <div className="figma-poi-detail"><div className="figma-badges">{poi.boothCode&&<span className="figma-badge is-accent">{poi.boothCode}</span>}{map&&<span className="figma-badge">{map.title}</span>}{activity.eventPackage.meta?.isExample&&<span className="figma-example">示例</span>}{poi.closed&&<span className="figma-badge is-warning">已关闭</span>}</div><h2 className="figma-poi-name">{poi.name}</h2>{!!poi.tags?.length&&<p className="page-sub">{poi.tags.join(' · ')}</p>}<div className="figma-poi-actions"><button className={favorite?'is-on':''} aria-label={favorite?'取消收藏':'收藏'} aria-pressed={favorite} onClick={onFavorite}><Star size={20} fill={favorite?'currentColor':'none'}/><span>{favorite?'已收藏':'收藏'}</span></button><button className={scheduled?'is-on':''} aria-label="加入日程" disabled={poi.closed} onClick={onSchedule}><CalendarDays size={20}/><span>{scheduled?'再加一条':'加入日程'}</span></button><button className={routeIndex>=0?'is-on':''} aria-label={routeIndex>=0?'移出路线':'加入路线'} aria-pressed={routeIndex>=0} disabled={poi.closed&&routeIndex<0} onClick={onRoute}><Route size={20}/><span>{routeIndex>=0?`路线第 ${routeIndex+1} 站`:'加入路线'}</span></button></div>{(map||poi.description)&&<div className="figma-poi-info">{map&&<button className="me-row" onClick={onMap}><MapPin size={17}/><span className="me-row-label">{map.title}{poi.boothCode?' · '+poi.boothCode:''}</span><ChevronRight size={16}/></button>}{poi.description&&<p>{poi.description}</p>}</div>}{poi.sourceNote&&<p className="page-sub">{poi.sourceNote}</p>}<div className="section-label">相关场次</div>{sessions.length?<div className="figma-poi-sessions">{sessions.map(s=><button className="me-row" key={s.id} onClick={()=>onSession(s.id)}><span className="me-row-label"><span className="sched-title">{s.title}</span><span className="sched-meta">{dateCn(s.date)} · {s.start}–{s.end}</span></span><span className="figma-badge is-accent">排入日程</span></button>)}</div>:<p className="page-sub figma-poi-no-session">暂无公布的场次。</p>}</div>
}
