import {useState} from 'react'
import {Search,MapPin,ChevronRight,LockKeyhole} from 'lucide-react'
import type {ActivityDTO} from '../../../shared/activity-contract'
import type {CapabilityRecord} from '../../../shared/types'
import type {RecentActivity} from './activity-history'
import {activityReference,invitationTarget} from './figma-adapter'
import {activityDateStatus,activityUpdatedAt,dateStatusText} from './activity-tools'
import {rangeText} from './fmt'
interface Props{events:ActivityDTO[];recent:RecentActivity[];caps:CapabilityRecord[];loaded:boolean;error:string;search:string;onSearch:(v:string)=>void;typeFilter:string;onType:(v:string)=>void;dateFilter:string;onDate:(v:string)=>void;go:(path:string)=>void}
export function FigmaActivityList({events,recent,caps,loaded,error,search,onSearch,typeFilter,onType,dateFilter,onDate,go}:Props){
 const [invite,setInvite]=useState(''),[inviteError,setInviteError]=useState('')
 const list=events.filter(a=>[a.eventPackage.event.title,a.eventPackage.event.location||''].join(' ').toLowerCase().includes(search.trim().toLowerCase())&&(!typeFilter||(a.eventPackage.event.eventType||'generic')===typeFilter)&&(!dateFilter||activityDateStatus(a)===dateFilter))
 return <div className="app-shell figma-shell"><main className="page figma-event-select"><div className="figma-brand">同野·游</div><h1 className="page-title">选择活动</h1><label className="figma-search"><Search size={17}/><input aria-label="搜索活动" placeholder="搜索活动、城市或场馆" value={search} onChange={e=>onSearch(e.target.value)}/></label><div className="segmented figma-type-segment" aria-label="活动类型">{[['','全部'],['comic_convention','展会'],['generic','活动']].map(([key,label])=><button key={key} className={typeFilter===key?'on':''} aria-pressed={typeFilter===key} onClick={()=>onType(key)}>{label}</button>)}</div><select className="select figma-date-filter" aria-label="日期状态" value={dateFilter} onChange={e=>onDate(e.target.value)}><option value="">全部日期状态</option>{Object.entries(dateStatusText).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select>{error&&<p className="notice" role="alert">{error}</p>}{!loaded?<p className="page-sub" role="status">读取活动中…</p>:list.length===0?<div className="empty"><div className="empty-title">{events.length?'没有匹配的活动':'暂无公开活动'}</div>{events.length>0&&<button className="btn btn-surface" onClick={()=>{onSearch('');onType('');onDate('')}}>清除筛选</button>}</div>:<div className="activity-list-group figma-event-list">{list.map(a=>{const v=activityReference(a),first=v.dates[0],last=v.dates[v.dates.length-1];return <button className="sched-row figma-event-card" key={a.id} onClick={()=>go(`/events/${encodeURIComponent(a.id)}`)}><span className="figma-date-tile" aria-hidden="true"><span>{Number(first.slice(5,7))}月</span><strong>{first.slice(8)}</strong>{last!==first&&<span>–{last.slice(5,7)===first.slice(5,7)?last.slice(8):last.slice(5).replace('-','/')}</span>}</span><span className="sched-main"><span className="figma-badges"><span className={`figma-badge ${v.type==='comic_convention'?'is-accent':''}`}>{v.type==='comic_convention'?'展会':'活动'}</span>{v.example&&<span className="figma-example">示例</span>}{a.status==='cancelled'&&<span className="figma-badge is-warning">已取消</span>}</span><span className="sched-title">{v.title}</span><span className="sched-meta"><span>{rangeText(first,last)} · {dateStatusText[activityDateStatus(a)]}</span>{v.location&&<span className="figma-place"><MapPin size={13}/>{v.location}</span>}<span className="event-updated">资料更新：{activityUpdatedAt(a)}</span></span></span><ChevronRight size={18}/></button>})}</div>}
 <section className="figma-private-entry"><div className="section-label">私密活动</div><form className="figma-inline-entry" onSubmit={e=>{e.preventDefault();try{location.assign(invitationTarget(invite,location.origin));setInviteError('')}catch(e){setInviteError((e as Error).message)}}}><LockKeyhole size={18}/><input aria-label="小队邀请链接" placeholder="邀请链接" value={invite} onChange={e=>{setInvite(e.target.value);setInviteError('')}} autoComplete="off"/><button disabled={!invite.trim()}>进入</button></form>{inviteError&&<p className="notice" role="alert">{inviteError}</p>}<p className="page-sub">打开组织者提供的完整邀请链接。</p></section>
 {recent.length>0&&<section aria-label="最近活动"><div className="section-label">最近活动</div><div className="card me-card">{recent.map(a=><button className="me-row" key={a.id} onClick={()=>go(`/events/${encodeURIComponent(a.id)}`)}><span className="me-row-label">{events.find(e=>e.id===a.id)?.eventPackage.event.title||a.title}</span><ChevronRight size={17}/></button>)}</div></section>}<div className="section-label">我的活动</div><div className="card me-card"><button className="me-row" onClick={()=>go('/create?personal=1')}><span className="me-row-label">发起日常活动</span><ChevronRight size={17}/></button></div>{caps.length>0&&<><div className="section-label">最近小队</div><div className="card me-card">{Array.from(new Set(caps.map(c=>c.groupId))).map(id=><button className="me-row" key={id} onClick={()=>go(`/groups/${id}`)}><span className="me-row-label">{caps.find(c=>c.groupId===id)?.title||'小队'}</span><ChevronRight size={17}/></button>)}</div></>}<div className="section-label">更多</div><div className="card me-card"><button className="me-row" onClick={()=>go('/admin')}>管理员入口<ChevronRight size={17}/></button><button className="me-row" onClick={()=>location.assign('/help/index.html')}>帮助<ChevronRight size={17}/></button></div></main></div>
}
