import {useEffect,useRef,useState} from 'react'
import {Copy,Link2,Share2} from 'lucide-react'

// The three groups and replacement confirmation follow official Figma V18.
export function FigmaManageTeam({title,inviteLink,recoveryLink,canUpdate,confirming,onReplace,onBack,onRotate,onUpdate}:{title:string;inviteLink?:string;recoveryLink:string;canUpdate:boolean;confirming:boolean;onReplace:()=>void;onBack:()=>void;onRotate:()=>Promise<void>;onUpdate:()=>Promise<string>}){
 const [busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[error,setError]=useState(''),alive=useRef(true)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 async function copy(value:string,message:string){try{await navigator.clipboard.writeText(value);setFeedback(message);setError('')}catch{setError('复制失败，请重试。')}}
 async function rotate(){if(busy)return;setBusy(true);setError('');try{await onRotate();if(alive.current){setFeedback('已生成新邀请');onBack()}}catch(e){setError((e as Error).message)}finally{if(alive.current)setBusy(false)}}
 async function update(){if(busy)return;setBusy(true);setError('');try{const message=await onUpdate();if(alive.current)setFeedback(message)}catch(e){setError((e as Error).message)}finally{if(alive.current)setBusy(false)}}
 const notices=<>{error&&<p className="notice" role="alert">{error}</p>}{feedback&&<p className="page-sub" role="status">{feedback}</p>}</>
 if(confirming)return <div className="figma-confirm-content"><p>确定要更换成员邀请吗？旧的邀请链接将立即失效，且不能恢复。已加入的队员保留自己的权限。</p>{notices}<div className="btn-row"><button className="btn btn-subtle" disabled={busy} onClick={onBack}>取消</button><button className="btn btn-danger" disabled={busy} onClick={()=>void rotate()}>{busy?'更换中…':'确认更换'}</button></div></div>
 return <div className="figma-manage-team">{notices}<section className="figma-crew-section"><h2>邀请成员</h2><div className="figma-settings-group figma-manage-content"><p className="page-sub">加入「{title}」，一起查看共同空闲。</p><div className="figma-manage-invite-actions"><button className="btn btn-surface" disabled={!inviteLink||busy} onClick={()=>inviteLink&&void copy(inviteLink,'邀请链接已复制')}><Link2 size={17}/>复制链接</button><button className="btn btn-primary" disabled={!inviteLink||busy} onClick={async()=>{if(!inviteLink)return;try{if(navigator.share){await navigator.share({title:`加入${title}`,url:inviteLink});setFeedback('已分享邀请')}else{await navigator.clipboard.writeText(inviteLink);setFeedback('当前浏览器不支持分享，邀请链接已复制')}setError('')}catch(e){if((e as Error).name!=='AbortError')setError('分享失败，请重试。')}}}><Share2 size={17}/>分享</button></div>{!inviteLink&&<p className="page-sub">此设备未保存邀请链接，请更换成员邀请。</p>}<div className="figma-manage-divider"><button className="btn btn-subtle btn-block" disabled={busy} onClick={()=>{setError('');onReplace()}}>更换成员邀请</button></div></div><p className="page-sub">更换邀请后，旧链接立即失效。</p></section>
 <section className="figma-crew-section"><h2>队长恢复</h2><div className="figma-settings-group figma-manage-content"><input readOnly className="figma-recovery-value" aria-label="管理恢复链接" value={recoveryLink}/><button className="btn btn-subtle btn-block" onClick={()=>void copy(recoveryLink,'已复制，请妥善保存')}><Copy size={16}/>保存管理恢复链接</button></div><p className="page-sub">此链接可恢复队长权限，与普通邀请不同，请勿公开。</p></section>
 {canUpdate&&<section className="figma-crew-section"><h2>活动资料</h2><div className="figma-settings-group figma-manage-content"><p className="page-sub">核对并更新本队使用的公开活动资料。</p><button className="btn btn-subtle btn-block" disabled={busy} onClick={()=>void update()}>{busy?'更新中…':'更新活动资料'}</button></div><p className="page-sub">活动时间改变后，队员需要重新确认。</p></section>}
 </div>
}
