import {ArrowUp,ArrowDown,Check,ChevronRight,Trash2} from 'lucide-react'
import type {PersonalRoute,POI} from '../../../shared/activity-contract'

export function FigmaRouteStops({route,pois,onChange,onSelect,onEstimate}:{route:PersonalRoute|undefined;pois:POI[];onChange:(route:PersonalRoute)=>void;onSelect:(id:string)=>void;onEstimate:(id:string)=>void}){
 if(!route?.stops.length)return <div className="empty"><div className="empty-title">路线是空的</div><div className="empty-sub">从地点详情或收藏加入路线</div></div>
 const next=route.stops.findIndex(s=>!s.visited),name=(id:string)=>pois.find(p=>p.id===id)?.name||'地点已移除'
 const toggle=(id:string)=>onChange({...route,stops:route.stops.map(s=>s.poiId===id?{...s,visited:!s.visited}:s)})
 return <>{next>=0?<section className="figma-route-next"><p>下一站 · 第 {next+1} 站</p><h2>{name(route.stops[next].poiId)}</h2><div className="btn-row"><button className="btn btn-surface" onClick={()=>onSelect(route.stops[next].poiId)}>查看详情</button><button className="btn btn-surface" onClick={()=>toggle(route.stops[next].poiId)}>标记已到达</button></div></section>:<p className="notice">路线已全部完成</p>}<div className="figma-route-list">{route.stops.map((stop,i)=><div className="figma-route-entry" key={stop.poiId}><div className="figma-route-main"><button className={`figma-route-number ${stop.visited?'is-visited':next===i?'is-next':''}`} aria-label={`${stop.visited?'标记未经过':'标记经过'} ${name(stop.poiId)}`} aria-pressed={stop.visited} onClick={()=>toggle(stop.poiId)}>{stop.visited?<Check size={16}/>:i+1}</button><button className="personal-row-main" onClick={()=>onSelect(stop.poiId)}><span className={`sched-title ${stop.visited?'is-visited':''}`}>{name(stop.poiId)}</span><span className="sched-meta">{[pois.find(p=>p.id===stop.poiId)?.boothCode,stop.visited?'已经过':next===i?'下一站':'待前往'].filter(Boolean).join(' · ')}</span></button><ChevronRight size={16}/></div><div className="figma-route-tools"><button className="icon-btn" aria-label={`上移 ${name(stop.poiId)}`} disabled={i===0} onClick={()=>{const stops=[...route.stops];[stops[i-1],stops[i]]=[stops[i],stops[i-1]];onChange({...route,stops})}}><ArrowUp size={17}/></button><button className="icon-btn" aria-label={`下移 ${name(stop.poiId)}`} disabled={i===route.stops.length-1} onClick={()=>{const stops=[...route.stops];[stops[i+1],stops[i]]=[stops[i],stops[i+1]];onChange({...route,stops})}}><ArrowDown size={17}/></button><button className="chip" aria-label={`停留与排队 ${name(stop.poiId)}`} onClick={()=>onEstimate(stop.poiId)}>停留与排队</button><button className="icon-btn" aria-label={`移除路线 ${name(stop.poiId)}`} onClick={()=>onChange({...route,stops:route.stops.filter(s=>s.poiId!==stop.poiId)})}><Trash2 size={17}/></button></div></div>)}</div></>
}
