import type {ActivityDTO,PersonalDTO,MediaAssetDTO} from '../../../shared/activity-contract'
import {parseEventPackage} from '../../../shared/event-validation'
import {readLocal,writeLocal,removeLocal} from '../storage'
import {api} from '../api'
import {listAssets,fetchMapImage} from './media-client'
interface PreparedMap {mapId:string;mapRevision:number;asset:MediaAssetDTO;blob:Blob;displaySHA256:string}
interface PreparedRecord {format:1;eventId:string;identityScope:string;activity:ActivityDTO;personal?:PersonalDTO;maps:PreparedMap[];mapIds?:string[];preparedAt:string;sizeBytes:number}
export interface PreparedActivity {activity:ActivityDTO;personal?:PersonalDTO;blobURLs:Record<string,string>;status:'ready'|'stale'|'cached';preparedAt:string;sizeBytes:number;release:()=>void}
export interface OfflineIO {
 read:(key:string)=>Promise<unknown>;write:(key:string,value:unknown)=>Promise<void>
 list:(eventId:string,token?:string)=>Promise<MediaAssetDTO[]>;fetch:(eventId:string,assetId:string,token?:string)=>Promise<Blob>
 current:(eventId:string,token?:string)=>Promise<ActivityDTO>;dimensions:(blob:Blob)=>Promise<{width:number;height:number}>
 createURL:(blob:Blob)=>string;revokeURL:(url:string)=>void
}
async function imageDimensions(blob:Blob):Promise<{width:number;height:number}>{if(typeof createImageBitmap==='function'){const image=await createImageBitmap(blob);const value={width:image.width,height:image.height};image.close();return value}return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve({width:image.naturalWidth,height:image.naturalHeight})};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('地图不是可解码图片'))};image.src=url})}
const defaultIO:OfflineIO={read:readLocal,write:writeLocal,list:listAssets,fetch:fetchMapImage,current:(id,token)=>api<ActivityDTO>(`${token?'/admin':''}/events/${encodeURIComponent(id)}`,token),dimensions:imageDimensions,createURL:blob=>URL.createObjectURL(blob),revokeURL:url=>URL.revokeObjectURL(url)}
function key(eventId:string,scope:string){if(!eventId||!scope||scope.length>200||scope.includes('Bearer ')||/^[a-f0-9]{64}$/.test(scope))throw new Error('离线数据需要活动和身份范围；不能使用凭据作缓存键');return `activity-prepared:v1:${encodeURIComponent(eventId)}:${encodeURIComponent(scope)}`}
async function digest(blob:Blob){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('')}
function version(activity:ActivityDTO){return JSON.stringify({id:activity.id,revision:activity.revision,scheduleRevision:activity.scheduleRevision,spatialRevision:activity.spatialRevision,status:activity.status,eventPackage:activity.eventPackage})}
function assetSignature(asset:MediaAssetDTO){return JSON.stringify([asset.id,asset.eventId,asset.assetKey,asset.state,asset.revision,asset.mimeType,asset.width,asset.height,asset.sizeBytes,asset.sha256,asset.displaySizeBytes])}
function expose(record:PreparedRecord,current:ActivityDTO|undefined,io:OfflineIO):PreparedActivity {const blobURLs:Record<string,string>={};try{for(const map of record.maps)blobURLs[map.mapId]=io.createURL(map.blob)}catch(error){Object.values(blobURLs).forEach(io.revokeURL);throw error}let released=false;return{activity:record.activity,personal:record.personal,blobURLs,status:!current?'cached':version(current)!==version(record.activity)?'stale':'ready',preparedAt:record.preparedAt,sizeBytes:record.sizeBytes,release:()=>{if(!released){released=true;Object.values(blobURLs).forEach(io.revokeURL)}}}}
export async function loadPreparedActivity(eventId:string,identityScope:string,current?:ActivityDTO,options:{io?:OfflineIO}={}):Promise<PreparedActivity|undefined>{const io=options.io||defaultIO,record=await io.read(key(eventId,identityScope)) as PreparedRecord|undefined;if(!record)return undefined;if(record.format!==1||record.eventId!==eventId||record.identityScope!==identityScope||record.activity.id!==eventId)throw new Error('离线快照范围不符');parseEventPackage(JSON.stringify(record.activity.eventPackage));const available=record.activity.eventPackage.event.extensions?.convention.maps||[],ids=record.mapIds||available.map(m=>m.id);if(!Array.isArray(ids)||new Set(ids).size!==ids.length||ids.some(id=>!available.some(m=>m.id===id)))throw new Error('离线地图选择无效');const expected=available.filter(m=>ids.includes(m.id));if(expected.length!==record.maps.length)throw new Error('离线地图不完整');for(const map of record.maps){const ref=expected.find(m=>m.id===map.mapId);const manifest=record.activity.eventPackage.assetManifest?.find(a=>a.assetKey===ref?.assetKey);if(!ref||!manifest||ref.revision!==map.mapRevision||map.asset.eventId!==eventId||ref.assetKey!==map.asset.assetKey||manifest.sha256!==map.asset.sha256||manifest.sizeBytes!==map.asset.sizeBytes||manifest.mimeType!==map.asset.mimeType||manifest.width!==map.asset.width||manifest.height!==map.asset.height||!map.blob.size||await digest(map.blob)!==map.displaySHA256)throw new Error('离线地图版本或内容不符')}return expose(record,current,io)}
// A preparation is staged entirely in memory. One IDB record commits the complete
// activity, matching graph data, optional personal snapshot and all map blobs.
// An aborted quota transaction cannot replace the previous complete active record.
export async function prepareActivity(activity:ActivityDTO,identityScope:string,options:{adminToken?:string;personal?:PersonalDTO;onProgress?:(message:string)=>void;mapIds?:string[];io?:OfflineIO}={}):Promise<PreparedActivity>{const io=options.io||defaultIO,storageKey=key(activity.id,identityScope),snapshot=structuredClone(activity);if(options.adminToken&&identityScope==='public')throw new Error('管理员读取资料必须使用独立身份范围');parseEventPackage(JSON.stringify(snapshot.eventPackage));const available=snapshot.eventPackage.event.extensions?.convention.maps||[],mapIds=options.mapIds||available.map(m=>m.id);if(!Array.isArray(mapIds)||new Set(mapIds).size!==mapIds.length||mapIds.some(id=>!available.some(m=>m.id===id)))throw new Error('请选择当前活动的地图');const maps=available.filter(m=>mapIds.includes(m.id));if(options.personal&&(options.personal.eventId!==activity.id||identityScope!==options.personal.id))throw new Error('个人快照须保存在本人身份范围');if(options.personal&&(options.personal.scheduleRevision!==activity.scheduleRevision||options.personal.spatialRevision!==activity.spatialRevision))throw new Error('个人云端计划与活动版本不同，请复核；本机草稿仍独立保留');const assets=maps.length?structuredClone(await io.list(activity.id,options.adminToken)):[],prepared:PreparedMap[]=[];let sizeBytes=new TextEncoder().encode(JSON.stringify(snapshot)).length+(options.personal?new TextEncoder().encode(JSON.stringify(options.personal)).length:0)
 for(const map of maps){options.onProgress?.(`正在下载地图 ${map.title}`);const manifest=snapshot.eventPackage.assetManifest?.find(a=>a.assetKey===map.assetKey),matches=assets.filter(a=>a.eventId===activity.id&&a.assetKey===map.assetKey&&a.state==='ready');if(matches.length!==1||!manifest)throw new Error('地图资产缺失或有多个版本，请刷新活动后重试');const asset=matches[0];if(asset.width!==map.width||asset.height!==map.height||asset.sha256!==manifest.sha256||asset.sizeBytes!==manifest.sizeBytes||asset.mimeType!==manifest.mimeType)throw new Error('地图与活动清单版本不符，请刷新后重试');const blob=await io.fetch(activity.id,asset.id,options.adminToken);if(!blob.size||blob.size>12*1024*1024||!['image/png','image/jpeg','image/webp'].includes(blob.type)||asset.displaySizeBytes!==undefined&&asset.displaySizeBytes!==blob.size)throw new Error('地图显示文件大小或类型不符');const dimensions=await io.dimensions(blob);if(!dimensions.width||!dimensions.height||Math.abs(dimensions.width/dimensions.height-map.width/map.height)>0.002)throw new Error('地图显示图片构图比例不符');sizeBytes+=blob.size;if(sizeBytes>64*1024*1024)throw new Error('离线准备最多64MiB，请减少地图');prepared.push({mapId:map.id,mapRevision:map.revision,asset:structuredClone(asset),blob,displaySHA256:await digest(blob)})}
 options.onProgress?.('正在核对资料版本');const fresh=await io.current(activity.id,options.adminToken);if(version(fresh)!==version(snapshot))throw new Error('下载期间活动资料已更新，旧快照已保留，请重新准备');const freshAssets=maps.length?await io.list(activity.id,options.adminToken):[];for(const map of prepared){const a=freshAssets.find(a=>a.id===map.asset.id);if(!a||assetSignature(a)!==assetSignature(map.asset))throw new Error('下载期间地图版本已更新，旧快照已保留')}
 const record:PreparedRecord={format:1,eventId:activity.id,identityScope,activity:snapshot,personal:options.personal?structuredClone(options.personal):undefined,maps:prepared,mapIds,preparedAt:new Date().toISOString(),sizeBytes};options.onProgress?.('正在保存本机完整快照');await io.write(storageKey,record);options.onProgress?.('离线资料已准备');return expose(record,snapshot,io)
}
export async function removePreparedActivity(eventId:string,identityScope:string):Promise<void>{await removeLocal(key(eventId,identityScope))}
