if(process.env.TONGYE_PRODUCTION_DRILL !== '1')throw new Error('Explicit TONGYE_PRODUCTION_DRILL=1 is required for the isolated production drill')
/** Explicit authorized production single-group UI drill; excluded from normal CI. No traces or tokens in evidence. */
import {chromium,expect,type Page} from '@playwright/test'
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs'
const origin='https://coukong.vercel.app'
const api=origin+'/api/v1'
const worker='https://tongye-meet-api.xinglan233.workers.dev'
const creationCode=JSON.parse(readFileSync(process.env.TONGYE_DRILL_SECRET_FILE || (()=>{throw new Error('Set TONGYE_DRILL_SECRET_FILE to a private creation-code JSON file')})(),'utf8')).CREATION_CODE as string
if(!creationCode)throw new Error('Production creation code missing')
const output='/tmp/tongye-meet-production-ui-evidence';mkdirSync(output,{recursive:true})
const browser=await chromium.launch();const contexts=await Promise.all([browser.newContext(),browser.newContext(),browser.newContext()]);const [owner,a,b]=await Promise.all(contexts.map(c=>c.newPage()))
const title='生产上线隔离演练-20260930'
const report:{environment:string;api:string;startedAt:string;title:string;checks:string[];groupId?:string;remote:{path:string;status:number}[];result?:string;finishedAt?:string;cleaned?:boolean;error?:string}={environment:'Mac Chromium automation; real Vercel production frontend + same-origin API proxy + production cloud D1',api,startedAt:new Date().toISOString(),title,checks:[],remote:[]}
for(const page of [owner,a,b])page.on('response',r=>{if(r.url().startsWith(api))report.remote.push({path:new URL(r.url()).pathname,status:r.status()})})
async function submit(page:Page){const response=page.waitForResponse(r=>r.url().startsWith(api)&&r.request().method()==='PUT'&&r.url().endsWith('/response'));await page.getByRole('button',{name:'确认提交',exact:true}).click();expect((await response).status()).toBe(200);await expect(page.getByText('已提交，其他成员现在可以看到',{exact:false})).toBeVisible()}
async function join(page:Page,link:string,name:string,start:string,end:string){await page.goto(link);await page.getByLabel('你的名字').fill(name);await page.getByRole('button',{name:'加入小队',exact:true}).click();await expect(page.getByRole('heading',{name:'我的可参与时间'})).toBeVisible();await page.getByRole('button',{name:'添加区间',exact:true}).first().click();await page.getByLabel('开始时间 1',{exact:true}).first().fill(start);await page.getByLabel('结束时间 1',{exact:true}).first().fill(end);await submit(page)}
try{
 const ready=await owner.request.get(origin+'/api/v1/ready');expect(ready.status()).toBe(200);const directReady=await owner.request.get(worker+'/api/v1/ready');expect(directReady.status()).toBe(200);await owner.goto(origin);await expect(owner.getByRole('heading',{name:'找到能碰面的空档'})).toBeVisible();report.checks.push('Real production homepage and proxied/direct Worker ready returned 200');await owner.goto(origin+'/create');await owner.getByLabel('小队标题').fill(title);await expect(owner.getByLabel('站点创建码')).toBeVisible();await owner.getByLabel('站点创建码').fill(creationCode);await owner.getByRole('button',{name:'确认创建',exact:true}).click();await expect(owner.getByRole('heading',{name:title,exact:true})).toBeVisible();report.groupId=new URL(owner.url()).pathname.split('/')[2];report.checks.push('Visible UI created isolated group in real production D1');await owner.getByRole('button',{name:'管理',exact:true}).click();const invite=await owner.getByLabel('邀请链接').inputValue();
 await join(a,invite,'云UI成员A','13:07','13:52');await join(b,invite,'云UI成员B','13:00','14:00');await owner.getByRole('button',{name:'安排',exact:true}).click();await owner.getByLabel('你的名字').fill('云UI发起人');await owner.getByRole('button',{name:'加入小队',exact:true}).click();await expect(owner.getByRole('heading',{name:'我的可参与时间'})).toBeVisible();await owner.getByRole('button',{name:'明确选择全部开放时间可用'}).click();await submit(owner);report.checks.push('Three independent browser identities submitted their own responses to remote API');
 for(const page of [owner,a,b]){await page.reload();await expect(page.getByRole('heading',{name:'我的可参与时间'})).toBeVisible();await page.getByRole('button',{name:'共同空闲',exact:true}).click();await page.getByRole('button',{name:'刷新',exact:true}).click();await expect(page.getByText('3 人已加入，3 人已确认',{exact:true})).toBeVisible();await expect(page.getByText('13:07–13:52',{exact:true})).toBeVisible()}
 report.checks.push('Each identity independently reloaded and read three confirmations and 13:07–13:52 from remote D1');await a.getByRole('button',{name:'安排',exact:true}).click();await expect(a.getByLabel('开始时间 1',{exact:true}).first()).toHaveValue('13:07');await expect(a.getByLabel('结束时间 1',{exact:true}).first()).toHaveValue('13:52');const pending=a.waitForEvent('download');await a.getByRole('button',{name:'导出个人安排',exact:true}).click();const personal=JSON.parse(readFileSync((await (await pending).path())!,'utf8'));expect(personal.response.presence[0].intervals).toEqual([{start:'13:07',end:'13:52'}]);report.checks.push('Minute values survived remote save, refresh and personal JSON export');for(const width of [375,390]){await owner.setViewportSize({width,height:844});expect(await owner.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await owner.screenshot({path:output+`/production-common-${width}.png`,fullPage:true})}report.checks.push('375px and 390px real production screenshots captured without page overflow');
 await owner.getByRole('button',{name:'管理',exact:true}).click();const closed=owner.waitForResponse(r=>r.url().startsWith(api)&&r.request().method()==='PATCH'&&new URL(r.url()).pathname.endsWith('/'+report.groupId));await owner.getByRole('button',{name:'关闭填写',exact:true}).click();expect((await closed).status()).toBe(200);await expect(owner.getByText('Asia/Shanghai 活动时间 · 已关闭填写',{exact:true})).toBeVisible();report.cleaned=false;report.checks.push('Only this explicitly authorized production drill group was closed and retained; no group was deleted');report.result='passed'
}catch(error){const message=error instanceof Error?error.message:String(error);report.error=message.replaceAll(creationCode,'[creation code redacted]').replace(/[a-f0-9]{64}/g,'[capability redacted]');report.result='failed';process.exitCode=1}
finally{report.finishedAt=new Date().toISOString();writeFileSync(output+'/cloud-ui-result.json',JSON.stringify(report,null,2));await Promise.all(contexts.map(c=>c.close()));await browser.close();console.log(JSON.stringify({result:report.result,checks:report.checks.length,cleaned:report.cleaned===true,evidence:output+'/cloud-ui-result.json'}))}
