import {it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {activityDateStatus,activityUpdatedAt,activityLocalKey,readPersonalBackup,personalBackup} from '../../src/online/activity/activity-tools'
import type {ActivityDTO,PersonalPlan} from '../../shared/activity-contract'
const activity=():ActivityDTO=>({id:'event-a',revision:2,scheduleRevision:1,spatialRevision:1,status:'published',updatedAt:'2026-09-30T10:00:00Z',eventPackage:JSON.parse(readFileSync('examples/convention-demo.v2.json','utf8'))})
const plan=():PersonalPlan=>({response:{name:'本人',presence:[],busy:[{id:'busy-a',date:'2026-10-03',title:'分钟',source:'manual',start:'13:07',end:'13:52'}],bufferMinutes:5},favorites:[],routes:[]})
it('活动状态按活动时区日期，取消与归档独立，更新时间显示活动时间',()=>{const a=activity();expect(activityDateStatus(a,new Date('2026-10-02T16:01:00Z'))).toBe('ongoing');expect(activityDateStatus(a,new Date('2026-10-02T15:59:00Z'))).toBe('upcoming');expect(activityDateStatus(a,new Date('2026-10-03T16:01:00Z'))).toBe('ended');expect(activityDateStatus({...a,status:'cancelled'})).toBe('cancelled');expect(activityDateStatus({...a,status:'archived'})).toBe('archived');expect(activityUpdatedAt(a)).toBe('2026-09-30 18:00')})
it('个人备份同活动同身份保留分钟，不导出权限；兼容旧无身份数据包',()=>{const a=activity(),p=plan();const backup=personalBackup(a,p,'person-a');expect(readPersonalBackup(JSON.stringify(backup),a,'person-a',p)).toEqual(p);expect(JSON.stringify(backup)).not.toMatch(/token|Bearer/);expect(readPersonalBackup(JSON.stringify({kind:backup.kind,schemaVersion:1,eventId:a.id,plan:p}),a,'person-a',p)).toEqual(p)})
it('回导拒跨活动/身份/版本/权限字段/重复键/异常分钟，旧失效引用仅原身份已存在时可保留',()=>{const a=activity(),p=plan(),base=personalBackup(a,p,'person-a');for(const backup of [{...base,eventId:'other'},{...base,personId:'other'},{...base,scheduleRevision:2},{...base,spatialRevision:2},{...base,token:'a'.repeat(64)},{...base,plan:{...p,response:{...p.response,bufferMinutes:-1}}},{...base,plan:{...p,response:{...p.response,busy:[{...p.response.busy[0],end:'13:60'}]}}}])expect(()=>readPersonalBackup(JSON.stringify(backup),a,'person-a',p)).toThrow();expect(()=>readPersonalBackup(JSON.stringify(base),a,undefined,p)).toThrow();expect(()=>readPersonalBackup(JSON.stringify(base).replace('"schemaVersion":1','"schemaVersion":1,"schemaVersion":1'),a,'person-a',p)).toThrow();const removed={...p,favorites:[{poiId:'removed',visited:false}]};expect(()=>readPersonalBackup(JSON.stringify(personalBackup(a,removed,'person-a')),a,'person-a',p)).toThrow();expect(readPersonalBackup(JSON.stringify(personalBackup(a,removed,'person-a')),a,'person-a',removed)).toEqual(removed)})
it('本机清理匹配当前活动所有身份草稿、待提交、地图和设置，保留相似ID及其他资源',()=>{for(const key of ['activity-owner:event-a','activity-owner-edit:event-a','activity-cap:event-a','activity-personal:event-a','activity-snapshot:event-a','activity-personal-create:event-a','activity-create-group:event-a','activity-preferences:event-a','activity-recent:event-a','activity-submit:event-a:p','activity-delete:event-a:p','personal-busy-editor:event-a:unclaimed:2026-10-03','personal-presence-editor:event-a:unclaimed:2026-10-03','activity-prepared:v1:event-a:public','activity-prepared:v1:event-a:person-a'])expect(activityLocalKey(key,'event-a')).toBe(true);for(const key of ['activity-owner-edit:event-ab','activity-owner-edit:event-a:other','activity-cap:event-ab','activity-submit:event-ab:p','personal-busy-editor:event-ab:p:day','activity-prepared:v1:event-ab:public','capabilities','theme','published-activity-list'])expect(activityLocalKey(key,'event-a')).toBe(false)})

it('脏草稿导出记录实际确认的旧版本，不能假称属于新活动版本',()=>{const a={...activity(),scheduleRevision:2,spatialRevision:3},p=plan();expect(personalBackup(a,p,'person-a',{scheduleRevision:1,spatialRevision:1})).toMatchObject({scheduleRevision:1,spatialRevision:1});expect(()=>readPersonalBackup(JSON.stringify(personalBackup(a,p,'person-a',{scheduleRevision:1,spatialRevision:1})),a,'person-a',p)).toThrow('活动时间已变化')})

it('公开地点链接只含活动和地点，不携带私人或邀请上下文',async()=>{const {publicPoiLink}=await import('../../src/online/activity/activity-history');expect(publicPoiLink('https://coukong.vercel.app','event-a','poi-a')).toBe('https://coukong.vercel.app/events/event-a?poi=poi-a');expect(publicPoiLink('https://coukong.vercel.app','event-a','地点 / a')).toBe('https://coukong.vercel.app/events/event-a?poi=%E5%9C%B0%E7%82%B9+%2F+a')})
