import {readFileSync} from 'node:fs'
import {it,expect} from 'vitest'
import {parseEventPackage,validatePersonalPlan} from '../../shared/event-validation'
import type {EventPackage} from '../../shared/types'
const base=()=>JSON.parse(readFileSync('examples/event-minimal.json','utf8')) as EventPackage
export function sample():EventPackage {const p=base();p.schemaVersion=2;p.event.eventType='comic_convention';p.assetManifest=[{assetKey:'demo.png',mimeType:'image/png',width:2000,height:1000,sizeBytes:1000,sha256:'a'.repeat(64)}];p.event.extensions={convention:{maps:[{id:'m',title:'虚构示例',assetKey:'demo.png',width:2000,height:1000,revision:1,coordinateSpace:'normalized-image-top-left',sourceNote:'虚构测试图'}],pois:[{id:'p',name:'入口',kind:'entrance',position:{mapId:'m',mapRevision:1,x:.25,y:.6},routeNodeId:'a'}],routingGraphs:[{id:'g',mapId:'m',mapRevision:1,revision:1,nodes:[{id:'a',x:.25,y:.6},{id:'b',x:.5,y:.6}],edges:[{id:'ab',from:'a',to:'b',bidirectional:false,enabled:true,reviewed:true,estimatedTravelSeconds:90}]}]}};return p}
it('v1 and v2 valid, roundtrip exact minutes',()=>{expect(parseEventPackage(JSON.stringify(base())).schemaVersion).toBe(1);expect(parseEventPackage(JSON.stringify(sample()))).toEqual(sample())})
it('strict references coordinates versions weights manifests and extra fields',()=>{for(const mutate of [(p:EventPackage)=>{p.event.extensions!.convention.pois[0].position!.x=1.1},(p:EventPackage)=>{p.event.extensions!.convention.pois[0].position!.mapRevision=2},(p:EventPackage)=>{p.event.extensions!.convention.routingGraphs[0].edges[0].to='missing'},(p:EventPackage)=>{p.event.extensions!.convention.routingGraphs[0].edges[0].estimatedTravelSeconds=0},(p:EventPackage)=>{p.assetManifest=[]},(p:EventPackage)=>{Object.assign(p.event.extensions!.convention.maps[0],{url:'https://bad'})},(p:EventPackage)=>{p.event.extensions!.convention.pois[0].routeNodeId='missing'}]){const p=sample();mutate(p);expect(()=>parseEventPackage(JSON.stringify(p))).toThrow()}})
it('v1 refuses v2 extensions and larger byte allowance',()=>{const p=sample();p.schemaVersion=1;expect(()=>parseEventPackage(JSON.stringify(p))).toThrow()})
it('invalid dimensions duplicate IDs directions closures and numeric overflow reject',()=>{for(const mutate of [(p:EventPackage)=>{p.event.extensions!.convention.maps[0].width=24000001},(p:EventPackage)=>{p.event.extensions!.convention.pois.push(p.event.extensions!.convention.pois[0])},(p:EventPackage)=>{Object.assign(p.event.extensions!.convention.routingGraphs[0].edges[0],{bidirectional:'yes'})},(p:EventPackage)=>{p.event.extensions!.convention.routingGraphs[0].edges[0].closedDates=['2026-02-30']},(p:EventPackage)=>{p.event.extensions!.convention.routingGraphs[0].edges[0].geometry=[{x:.5,y:.6},{x:.25,y:.6}]},(p:EventPackage)=>{p.assetManifest![0].sha256='wrong'},(p:EventPackage)=>{p.event.activities=[{id:'s',title:'演示',sessions:[{id:'ss',date:'2026-10-03',start:'13:07',end:'13:52',poiId:'bad'}]}]}]){const p=sample();mutate(p);expect(()=>parseEventPackage(JSON.stringify(p))).toThrow()}})
it('v1 512KiB and v2 1MiB ceilings apply independently',()=>{const p=base();let raw=JSON.stringify(p)+' '.repeat(512*1024);expect(()=>parseEventPackage(raw)).toThrow();const v2=sample();raw=JSON.stringify(v2)+' '.repeat(1024*1024);expect(()=>parseEventPackage(raw)).toThrow()})
it('1000 POIs / 2000 nodes / 4000 edges remain valid at bounded scale',()=>{const p=sample(),c=p.event.extensions!.convention; c.pois=Array.from({length:1000},(_,i)=>({id:`p${i}`,name:`虚构${i}`,kind:'booth',position:{mapId:'m',mapRevision:1,x:(i%100)/100,y:.5},routeNodeId:'a'}));c.routingGraphs[0].nodes=Array.from({length:2000},(_,i)=>({id:i===0?'a':i===1?'b':`n${i}`,x:(i%100)/100,y:Math.floor(i/100)/20}));c.routingGraphs[0].edges=Array.from({length:4000},(_,i)=>({id:`e${i}`,from:i%2000===0?'a':i%2000===1?'b':`n${i%2000}`,to:(i+1)%2000===0?'a':(i+1)%2000===1?'b':`n${(i+1)%2000}`,bidirectional:true,enabled:true,reviewed:true,estimatedTravelSeconds:60}));expect(()=>parseEventPackage(JSON.stringify(p))).not.toThrow();c.pois.push({...c.pois[0],id:'overflow'});expect(()=>parseEventPackage(JSON.stringify(p))).toThrow()})

it('personal strict states and missing references only by explicit option',()=>{const e=sample().event;const plan={response:{name:'人',presence:[],busy:[],bufferMinutes:0},favorites:[{poiId:'p',visited:false}],routes:[{date:'2026-10-03',mapId:'m',spatialRevision:1,startPoiId:'p',stops:[{poiId:'p',visited:false,stayMinutes:5,queueMinutes:0}]}]};expect(validatePersonalPlan(plan,e)).toEqual(plan);plan.favorites[0].poiId='deleted';expect(()=>validatePersonalPlan(plan,e)).toThrow();expect(validatePersonalPlan(plan,e,{allowMissingReferences:true})).toEqual(plan);expect(()=>validatePersonalPlan({...plan,admin:true},e,{allowMissingReferences:true})).toThrow()})
it('no-map personal route retains station list without inventing map',()=>{const event=sample().event;delete event.extensions;const plan={response:{name:'人',presence:[],busy:[],bufferMinutes:0},favorites:[],routes:[{date:'2026-10-03',spatialRevision:1,stops:[]}]};expect(validatePersonalPlan(plan,event)).toEqual(plan);Object.assign(plan.routes[0],{mapId:''});expect(()=>validatePersonalPlan(plan,event)).toThrow()})
it('needsReview map permits older references for recheck but rejects future and activated mismatch',()=>{const p=sample(),c=p.event.extensions!.convention;c.maps[0].revision=2;c.maps[0].needsReview=true;expect(()=>parseEventPackage(JSON.stringify(p))).not.toThrow();c.pois[0].position!.mapRevision=3;expect(()=>parseEventPackage(JSON.stringify(p))).toThrow();c.pois[0].position!.mapRevision=1;c.maps[0].needsReview=false;expect(()=>parseEventPackage(JSON.stringify(p))).toThrow()})
