import {readFileSync} from 'node:fs'
import {it,expect} from 'vitest'
import {parseEventPackage,validateEventTransition,eventSpatialSignature} from '../../shared/event-validation'
import {routeFixedOrder} from '../../shared/routing'
const sample=()=>parseEventPackage(readFileSync('examples/convention-demo.v2.json','utf8'))
it('reproduces byte-only map replacement leaving valid old 270s path',()=>{const previous=sample(),next=structuredClone(previous);next.assetManifest![0].sha256='b'.repeat(64);next.assetManifest![0].sizeBytes++;expect(()=>parseEventPackage(JSON.stringify(next))).not.toThrow();expect(routeFixedOrder(next.event.extensions!.convention,'demo-map',['poi-a','poi-d'],'2026-10-03').estimatedTravelSeconds).toBe(270)})

it('byte identity change rejected unless map revision increased AND old references pending recheck',()=>{
 for(const field of ['sha256','sizeBytes','mimeType','assetKey','dimensions'] as const){const previous=sample(),next=structuredClone(previous),m=next.event.extensions!.convention.maps[0],a=next.assetManifest![0];if(field==='sha256')a.sha256='b'.repeat(64);else if(field==='sizeBytes')a.sizeBytes++;else if(field==='mimeType')a.mimeType='image/webp';else if(field==='assetKey'){m.assetKey='replacement.png';a.assetKey=m.assetKey}else{m.width++;a.width=m.width}expect(()=>parseEventPackage(JSON.stringify(next))).not.toThrow();expect(eventSpatialSignature(next)).not.toBe(eventSpatialSignature(previous));expect(()=>validateEventTransition(previous,next)).toThrow(/地图文件身份已变化/);m.revision++;next.event.extensions!.convention.pois.forEach(p=>{if(p.position)p.position.mapRevision=m.revision});next.event.extensions!.convention.routingGraphs.forEach(g=>g.mapRevision=m.revision);expect(()=>validateEventTransition(previous,next)).toThrow(/重新校对/);m.needsReview=true;expect(()=>validateEventTransition(previous,next)).not.toThrow();expect(routeFixedOrder(next.event.extensions!.convention,'demo-map',['poi-a','poi-d'],'2026-10-03').segments[0].status).toBe('stale')}
})
it('pending old refs can be saved then explicit checked current refs activate, history untouched',()=>{const previous=sample(),history=JSON.stringify(previous),next=structuredClone(previous);next.assetManifest![0].sha256='c'.repeat(64);next.event.extensions!.convention.maps[0].revision=2;next.event.extensions!.convention.maps[0].needsReview=true;expect(()=>validateEventTransition(previous,parseEventPackage(JSON.stringify(next)))).not.toThrow();const checked=structuredClone(next);checked.event.extensions!.convention.maps[0].needsReview=false;expect(()=>parseEventPackage(JSON.stringify(checked))).toThrow();checked.event.extensions!.convention.pois.forEach(p=>{if(p.position)p.position.mapRevision=2});checked.event.extensions!.convention.routingGraphs.forEach(g=>g.mapRevision=2);expect(()=>validateEventTransition(next,parseEventPackage(JSON.stringify(checked)))).not.toThrow();expect(JSON.stringify(previous)).toBe(history)})
it('pure map title/source/POI names do not invalidate spatial version',()=>{const previous=sample(),next=structuredClone(previous);next.event.extensions!.convention.maps[0].title='说明标题';next.event.extensions!.convention.maps[0].sourceNote='说明文字';next.event.extensions!.convention.pois[0].name='新名字';next.event.extensions!.convention.routingGraphs[0].sourceNote='说明';expect(eventSpatialSignature(next)).toBe(eventSpatialSignature(previous));expect(()=>validateEventTransition(previous,next)).not.toThrow()})
