import {it,expect,vi} from 'vitest'
import {prepareActivity,loadPreparedActivity,type OfflineIO} from '../../src/online/activity/offline'
import type {ActivityDTO,MediaAssetDTO} from '../../shared/activity-contract'
import {readFileSync} from 'node:fs'
const event=():ActivityDTO=>({id:'e',revision:1,scheduleRevision:1,spatialRevision:1,status:'published',updatedAt:'2026-10-01T00:00:00Z',eventPackage:JSON.parse(readFileSync('examples/convention-demo.v2.json','utf8'))})
function adapter(){const data=new Map<string,unknown>(),activity=event(),m=activity.eventPackage.assetManifest![0];const assets:MediaAssetDTO[]=[{id:'asset',eventId:'e',assetKey:m.assetKey,state:'ready',mimeType:m.mimeType,width:m.width,height:m.height,sizeBytes:m.sizeBytes,sha256:m.sha256,revision:1}];const blob=new Blob([readFileSync('examples/assets/convention-demo.png')],{type:'image/png'});const io:OfflineIO={read:async key=>data.get(key),write:async(key,value)=>{data.set(key,value)},list:async()=>assets,fetch:async()=>blob,current:async()=>activity,dimensions:async()=>({width:2000,height:1000}),createURL:()=> 'blob:test',revokeURL:vi.fn()};return{io,data,activity,assets}}
it('all graph map and asset data activate atomically then load scoped',async()=>{const a=adapter();const ready=await prepareActivity(a.activity,'person-a',{io:a.io});expect(ready.status).toBe('ready');expect(ready.blobURLs['demo-map']).toBe('blob:test');expect((await loadPreparedActivity('e','person-a',a.activity,{io:a.io}))?.status).toBe('ready');expect(await loadPreparedActivity('e','person-b',a.activity,{io:a.io})).toBeUndefined();expect(await loadPreparedActivity('other','person-a',undefined,{io:a.io})).toBeUndefined();ready.release();expect(a.io.revokeURL).toHaveBeenCalled()})
it('one image failure and quota failure retain previous complete active',async()=>{const a=adapter();await prepareActivity(a.activity,'public',{io:a.io});const before=structuredClone([...a.data]);a.io.fetch=async()=>{throw Error('failed')};await expect(prepareActivity(a.activity,'public',{io:a.io})).rejects.toThrow();expect([...a.data]).toEqual(before);a.io.fetch=async()=>new Blob([readFileSync('examples/assets/convention-demo.png')],{type:'image/png'});a.io.write=async()=>{throw Error('quota')};await expect(prepareActivity(a.activity,'public',{io:a.io})).rejects.toThrow();expect([...a.data]).toEqual(before)})
it('asset or spatial revision changes before activation reject and older cache is stale',async()=>{const a=adapter();await prepareActivity(a.activity,'public',{io:a.io});a.io.current=async()=>({...a.activity,spatialRevision:2});await expect(prepareActivity(a.activity,'public',{io:a.io})).rejects.toThrow();expect((await loadPreparedActivity('e','public',{...a.activity,spatialRevision:2},{io:a.io}))?.status).toBe('stale');a.assets[0].sha256='b'.repeat(64);await expect(prepareActivity(a.activity,'public',{io:a.io})).rejects.toThrow()})
it('convention without map is not reported map-complete',async()=>{const a=adapter();a.activity.eventPackage.event.extensions!.convention.maps=[];await expect(prepareActivity(a.activity,'public',{io:a.io})).rejects.toThrow()})
it('unknown current version is labelled cached, not current-ready',async()=>{const a=adapter();await prepareActivity(a.activity,'public',{io:a.io});expect((await loadPreparedActivity('e','public',undefined,{io:a.io}))?.status).toBe('cached')})
it('mid-download asset mutation and corrupt blob cannot activate or load',async()=>{const a=adapter();await prepareActivity(a.activity,'public',{io:a.io});a.io.fetch=async()=>{a.assets[0].revision=2;return new Blob([readFileSync('examples/assets/convention-demo.png')],{type:'image/png'})};await expect(prepareActivity(a.activity,'public',{io:a.io})).rejects.toThrow();expect((await loadPreparedActivity('e','public',a.activity,{io:a.io}))?.status).toBe('ready');const record=[...a.data.values()][0] as {maps:{blob:Blob}[]};record.maps[0].blob=new Blob(['wrong'],{type:'image/png'});await expect(loadPreparedActivity('e','public',a.activity,{io:a.io})).rejects.toThrow()})
it('private admin and personal snapshots cannot fall into public cache',async()=>{const a=adapter();await expect(prepareActivity(a.activity,'public',{adminToken:'secret',io:a.io})).rejects.toThrow();await expect(prepareActivity(a.activity,'public',{personal:{id:'person-a',eventId:'e',revision:1,scheduleRevision:1,spatialRevision:1,updatedAt:'',plan:{response:{name:'A',presence:[],busy:[],bufferMinutes:0},favorites:[],routes:[]}},io:a.io})).rejects.toThrow()})
it('second map failure retains prior one-map coherent snapshot',async()=>{const a=adapter();await prepareActivity(a.activity,'public',{io:a.io});const previous=structuredClone([...a.data]);const map=a.activity.eventPackage.event.extensions!.convention.maps[0];a.activity.eventPackage.event.extensions!.convention.maps.push({...map,id:'second-map'});a.activity.spatialRevision++;let calls=0;a.io.fetch=async()=>{if(++calls===2)throw Error('second map failed');return new Blob([readFileSync('examples/assets/convention-demo.png')],{type:'image/png'})};await expect(prepareActivity(a.activity,'public',{io:a.io})).rejects.toThrow();expect([...a.data]).toEqual(previous);const loaded=await loadPreparedActivity('e','public',a.activity,{io:a.io});expect(loaded?.status).toBe('stale');expect(Object.keys(loaded!.blobURLs)).toEqual(['demo-map'])})
