import {it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import type {ActivityDTO} from '../../shared/activity-contract'
import {parsePrivateActivityEdit,privateDateRange,privatePatchRequest,initialPrivateEdit} from '../../src/online/activity/PrivateActivityEditor'
const pack=JSON.parse(readFileSync('examples/event-minimal.json','utf8'))
const activity:ActivityDTO={id:'private-example',visibility:'private',revision:3,scheduleRevision:2,spatialRevision:1,status:'published',updatedAt:'2026-10-01T00:00:00Z',eventPackage:pack}
it('私人编辑保留外部活动ID及分钟，拒绝身份字段、漫展、错误ID与重复键',()=>{const exact=structuredClone(pack);exact.event.days[0].openIntervals=[{start:'13:07',end:'13:52'}];expect(parsePrivateActivityEdit(JSON.stringify(exact),pack.event.id).event.days[0].openIntervals[0]).toEqual({start:'13:07',end:'13:52'});for(const p of [{...exact,ownerToken:'secret'},{...exact,event:{...exact.event,id:'other'}},{...exact,schemaVersion:2,event:{...exact.event,eventType:'comic_convention'}},{...exact,schemaVersion:2,event:{...exact.event,eventType:'generic',extensions:{convention:{maps:[],pois:[],routingGraphs:[]}}}}])expect(()=>parsePrivateActivityEdit(JSON.stringify(p),pack.event.id)).toThrow();expect(()=>parsePrivateActivityEdit(JSON.stringify(exact).replace('"schemaVersion":1','"schemaVersion":1,"schemaVersion":1'),pack.event.id)).toThrow()})
it('日期范围最多31天，已存在多段开放时间及场次不被暗删',()=>{const p=privateDateRange(pack,'2026-10-02','2026-10-04');expect(p.event.days).toHaveLength(3);expect(p.event.days[1].openIntervals).toEqual(pack.event.days[0].openIntervals);expect(p.event.id).toBe(pack.event.id);expect(()=>privateDateRange(pack,'2026-10-02','2026-11-03')).toThrow();expect(()=>privateDateRange(pack,'2026-02-30','2026-03-01')).toThrow();const withSession={...pack,event:{...pack.event,activities:[{id:'x',title:'场次',sessions:[{id:'s',date:'2026-10-03',start:'13:07',end:'13:52'}]}]}};const shortened=privateDateRange(withSession,'2026-10-04','2026-10-04');expect(shortened.event.activities).toEqual(withSession.event.activities);expect(()=>parsePrivateActivityEdit(JSON.stringify(shortened),pack.event.id)).toThrow()})
it('同内容网络重试固定操作，编辑或显式复核才产生新操作；不携带owner令牌',()=>{const draft=initialPrivateEdit(activity),request=privatePatchRequest(draft,pack,'operation-first');const restored={...draft,pending:request};expect(privatePatchRequest(restored,pack,'operation-new')).toEqual(request);const changed=structuredClone(pack);changed.event.title='修改';expect(privatePatchRequest(restored,changed,'operation-next').operationId).toBe('operation-next');expect(privatePatchRequest({...restored,expectedRevision:4},pack,'operation-review').expectedRevision).toBe(4);expect(JSON.stringify(request)).not.toMatch(/Token|Bearer/);expect(draft.expectedRevision).toBe(3)})
