import {it,expect,vi,beforeEach,afterEach} from 'vitest'
import {uploadMap,pendingMapUpload,finishMapUpload} from '../../src/online/activity/media-client'
const mocks=vi.hoisted(()=>({api:vi.fn(),upload:vi.fn()}))
vi.mock('../../src/online/api',async original=>({...await original<object>(),api:mocks.api}))
vi.mock('@vercel/blob/client',()=>({uploadPresigned:mocks.upload}))
const values=new Map<string,string>()
beforeEach(()=>{values.clear();vi.stubGlobal('localStorage',{get length(){return values.size},key:(i:number)=>[...values.keys()][i]??null,getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v),removeItem:(k:string)=>values.delete(k)});mocks.api.mockReset();mocks.upload.mockReset();mocks.api.mockImplementation(async(path:string,_token:string,body:{operationId:string})=>({asset:{id:body.operationId,state:'ready'},pathname:path}));vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('lost finish response')))})
afterEach(()=>vi.unstubAllGlobals())
it('不同活动和文件不会覆盖模糊finish的恢复记录，完成只删除自己',async()=>{await expect(uploadMap('event-a','admin',new File(['aaa'],'a.png',{type:'image/png'}))).rejects.toThrow();const a=pendingMapUpload('event-a');expect(a?.assetId).toBeTruthy();await expect(uploadMap('event-b','admin',new File(['bbb'],'b.png',{type:'image/png'}))).rejects.toThrow();const b=pendingMapUpload('event-b');expect(b?.assetId).toBeTruthy();expect(pendingMapUpload('event-a')).toEqual(a);vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({data:{id:b!.assetId,state:'ready'}}),{status:200}));await finishMapUpload(b!);expect(pendingMapUpload('event-b')).toBeUndefined();expect(pendingMapUpload('event-a')).toEqual(a)})
it('同活动换文件保留两份恢复记录，重试原文件复用原operation和token',async()=>{const a=new File(['aaa'],'a.png',{type:'image/png'}),b=new File(['bbb'],'b.png',{type:'image/png'});await expect(uploadMap('event-a','admin',a)).rejects.toThrow();const first=pendingMapUpload('event-a');await expect(uploadMap('event-a','admin',b)).rejects.toThrow();await expect(uploadMap('event-a','admin',a)).rejects.toThrow();expect(mocks.api.mock.calls[2][2]).toMatchObject({operationId:first!.operationId,uploadToken:first!.uploadToken,assetKey:first!.assetKey});expect([...values.values()].map(v=>JSON.parse(v)).filter(v=>v.eventId==='event-a')).toHaveLength(2)})

it('旧global模糊上传迁移保留，其他活动成功不能删除它',async()=>{const old={eventId:'legacy',assetId:'legacy-asset',assetKey:'map.png',uploadToken:'a'.repeat(64),operationId:'legacy-op',sizeBytes:3,mimeType:'image/png'};values.set('tongye.media.pending.v1',JSON.stringify(old));expect(pendingMapUpload('legacy')).toEqual(old);expect(values.has('tongye.media.pending.v1:legacy-op')).toBe(true);vi.mocked(fetch).mockResolvedValue(new Response(JSON.stringify({data:{id:'new-ready'}}),{status:200}));await uploadMap('different','admin',new File(['bbb'],'b.png',{type:'image/png'}));expect(pendingMapUpload('legacy')).toEqual(old)})
