import {it,expect} from 'vitest'
import * as routing from '../../shared/routing'
import type {ConventionData,PersonalRoute} from '../../shared/activity-contract'
const convention:ConventionData={maps:[{id:'m',title:'虚构图',assetKey:'m.png',width:2000,height:1000,revision:1,coordinateSpace:'normalized-image-top-left'}],pois:['a','b'].map((id,i)=>({id,name:id,kind:'booth',routeNodeId:id,position:{mapId:'m',mapRevision:1,x:i,y:0}})),routingGraphs:[{id:'g',mapId:'m',mapRevision:1,revision:1,nodes:[{id:'a',x:0,y:0},{id:'b',x:1,y:0}],edges:[{id:'ab',from:'a',to:'b',enabled:true,reviewed:true,bidirectional:true,estimatedTravelSeconds:270}]}]}
const route=():PersonalRoute=>({date:'2026-10-03',mapId:'m',startPoiId:'a',spatialRevision:1,stops:[{poiId:'b',visited:false,stayMinutes:20,queueMinutes:10}]})
it('fits buffered minute window without subtracting buffer again or changing plan',()=>{const r=route(),original=JSON.stringify(r);expect(routing.routeWindowFit(convention,r,1,{date:r.date,start:'13:07',end:'13:52'})).toMatchObject({status:'fits',requiredMinutes:34.5,start:'13:07',end:'13:42'});expect(JSON.stringify(r)).toBe(original)})
it('too short window never creates a schedule; visited stops not counted',()=>{const r=route();expect(routing.routeWindowFit(convention,r,1,{date:r.date,start:'13:07',end:'13:41'}).status).toBe('too_short');r.stops[0].visited=true;expect(routing.routeWindowFit(convention,r,1,{date:r.date,start:'13:07',end:'13:52'}).status).toBe('unknown')})
it('unset stay or queue and unknown path time stay unknown, not zero',()=>{const r=route();delete r.stops[0].queueMinutes;expect(routing.routeWindowFit(convention,r,1,{date:r.date,start:'13:07',end:'13:52'}).status).toBe('unknown');const c=structuredClone(convention);delete c.routingGraphs[0].edges[0].estimatedTravelSeconds;expect(routing.routeWindowFit(c,route(),1,{date:r.date,start:'13:07',end:'13:52'}).status).toBe('unknown')})
it('stale, closed path, no declared origin and mismatched date cannot claim fits',()=>{const r=route(),w={date:r.date,start:'13:07',end:'13:52'};expect(routing.routeWindowFit(convention,r,2,w).status).toBe('stale');delete r.startPoiId;expect(routing.routeWindowFit(convention,r,1,w).status).toBe('unknown');const c=structuredClone(convention);c.routingGraphs[0].edges[0].enabled=false;expect(routing.routeWindowFit(c,route(),1,w).status).toBe('unknown');expect(routing.routeWindowFit(convention,route(),1,{...w,date:'2026-10-04'}).status).toBe('unknown')})
