import {it,expect} from 'vitest'
import {shortestPath,normalizedToImage,imageToNormalized,requiredTravelMinutes,routeFixedOrder} from '../../shared/routing'
import type {RoutingGraph} from '../../shared/activity-contract'
const graph=():RoutingGraph=>({id:'g',mapId:'m',mapRevision:1,revision:1,nodes:[{id:'a',x:0,y:0},{id:'b',x:0,y:1},{id:'c',x:1,y:1},{id:'d',x:1,y:0}],edges:['ab','bc','cd'].map((id,i)=>({id,from:'abcd'[i],to:'abcd'[i+1],bidirectional:false,enabled:true,reviewed:true,estimatedTravelSeconds:60,distanceMeters:10}))})
it('must detour a-b-c-d, not draw a-d straight',()=>{const p=shortestPath(graph(),'a','d','2026-10-03');expect(p.nodeIds).toEqual(['a','b','c','d']);expect(p.geometry).toHaveLength(4);expect(p.estimatedTravelSeconds).toBe(180)})
it('direction, closure date, disabled and unreviewed block route',()=>{expect(shortestPath(graph(),'d','a','2026-10-03').status).toBe('unreachable');for(const patch of [{enabled:false},{reviewed:false},{closedDates:['2026-10-03']}]){const g=graph();Object.assign(g.edges[1],patch);const r=shortestPath(g,'a','d','2026-10-03');expect(r.status).toBe('unreachable');expect(r.geometry).toEqual([])}})
it('partial unknown metric never becomes zero/full ETA',()=>{const g=graph();delete g.edges[1].estimatedTravelSeconds;delete g.edges[0].distanceMeters;expect(shortestPath(g,'a','d','2026-10-03')).toMatchObject({status:'ok',estimatedTravelSeconds:null,distanceMeters:null,weightUnit:'relative'})})
it('2000x1000 coordinate mapping and inverse exact',()=>{expect(normalizedToImage({x:.25,y:.6},2000,1000)).toEqual({x:500,y:600});expect(imageToNormalized({x:500,y:600},2000,1000)).toEqual({x:.25,y:.6});expect(()=>normalizedToImage({x:2,y:0},2000,1000)).toThrow()})
it('travel uses max not double buffer and unknown stays unknown',()=>{expect(requiredTravelMinutes(180,5,5)).toBe(10);expect(requiredTravelMinutes(900,5,5,2,3)).toBe(20);expect(requiredTravelMinutes(null,5,5)).toBeNull();expect(requiredTravelMinutes(61,0,0)).toBeCloseTo(61/60)})
it('fixed order preserves order and stale map cannot route',()=>{const g=graph();const c={maps:[{id:'m',title:'demo',assetKey:'m.png',width:2000,height:1000,revision:1,coordinateSpace:'normalized-image-top-left' as const}],routingGraphs:[g],pois:['a','b','c','d'].map(id=>({id,name:id,kind:'booth' as const,position:{mapId:'m',mapRevision:1,x:0,y:0},routeNodeId:id}))};expect(routeFixedOrder(c,'m',['a','c','d'],'2026-10-03').segments.map(s=>s.nodeIds)).toEqual([['a','b','c'],['c','d']]);c.maps[0].revision=2;expect(routeFixedOrder(c,'m',['a','d'],'2026-10-03').segments[0].status).toBe('stale')})
