import { describe,it,expect } from 'vitest'
import { personalAvailability,commonAvailability } from '../../shared/availability'
import { toMinute,fromMinute,dateOrdinal,validateTimeRange,mergeRanges,intersectRanges } from '../../shared/time'
import type { EventData,ParticipantResponse,AvailabilityPerson } from '../../shared/types'
const date='2026-10-03'
const event:EventData={id:'test',title:'测试',timezone:'Asia/Shanghai',startDate:date,endDate:date,defaultBufferMinutes:0,defaultMinSlotMinutes:30,defaultSelectionStepMinutes:15,days:[{date,openIntervals:[{start:'09:00',end:'12:00'}]}],activities:[]}
const response=(start:string,end:string,busyStart?:string,busyEnd?:string,bufferMinutes=0):ParticipantResponse=>({name:'成员',presence:[{date,intervals:[{start,end}]}],busy:busyStart?[{id:'b',date,start:busyStart,end:busyEnd!,title:'私密',source:'manual'}]:[],bufferMinutes})
const person=(id:string,r:ParticipantResponse,status:AvailabilityPerson['status']='confirmed'):AvailabilityPerson=>({id,name:id,status,revision:1,confirmedScheduleRevision:1,updatedAt:'2026-09-30T00:00:00Z',submittedAt:'2026-09-30T00:00:00Z',availability:personalAvailability(event,r)})
const A=person('A',response('09:00','12:00','10:07','10:22',5)),B=person('B',response('09:15','11:50','09:40','09:55'))
const exact=[{date,start:'09:15',end:'09:40'},{date,start:'09:55',end:'10:02'},{date,start:'10:27',end:'11:50'}]
describe('minute time and safe availability',()=>{
 it('exact_intersection_with_per_member_buffers',()=>{expect(commonAvailability(event,[A,B],['A','B'],1).intervals).toEqual(exact);expect(commonAvailability(event,[A,B],['A','B'],5).intervals).toEqual(exact);expect(commonAvailability(event,[A,B],['A','B'],15).intervals).toEqual([exact[0],exact[2]])})
 it('minute_precision_survives_roundtrip and display_step_does_not_change_data',()=>{const e={...event,days:[{date,openIntervals:[{start:'13:00',end:'18:00'}]}]};const r=response('13:07','13:52');for(const step of [5,10,15,30] as const) expect(personalAvailability({...e,defaultSelectionStepMinutes:step},JSON.parse(JSON.stringify(r)))).toEqual([{date,start:'13:07',end:'13:52'}]);expect(fromMinute(toMinute('09:05'))).toBe('09:05')})
 it('half_open_boundaries and invalid ranges',()=>{expect(intersectRanges([[600,630]],[[630,660]])).toEqual([]);expect(mergeRanges([[600,630],[630,660]])).toEqual([[600,660]]);expect(validateTimeRange({start:'10:00',end:'10:00'})).toBe(false);expect(validateTimeRange({start:'11:00',end:'10:00'})).toBe(false)})
 it('twenty_four_only_allowed_as_end',()=>{expect(toMinute('24:00',true)).toBe(1440);expect(()=>toMinute('24:00')).toThrow();expect(validateTimeRange({start:'23:30',end:'24:00'})).toBe(true);expect(validateTimeRange({start:'23:30',end:'00:30'})).toBe(false)})
 it('multiple_open_and_presence_intervals',()=>{const e={...event,days:[{date,openIntervals:[{start:'09:00',end:'12:00'},{start:'13:00',end:'18:00'}]}]};const r={...response('10:00','14:00'),presence:[{date,intervals:[{start:'10:00',end:'11:00'},{start:'11:30',end:'14:00'}]}]};expect(personalAvailability(e,r)).toEqual([{date,start:'10:00',end:'11:00'},{date,start:'11:30',end:'12:00'},{date,start:'13:00',end:'14:00'}])})
 it('midnight_buffer_spills_to_adjacent_day in both directions',()=>{const next='2026-10-04';const e={...event,endDate:next,days:[{date,openIntervals:[{start:'23:00',end:'24:00'}]},{date:next,openIntervals:[{start:'00:00',end:'01:00'}]}]};const r:ParticipantResponse={name:'a',bufferMinutes:10,presence:e.days.map(d=>({date:d.date,intervals:d.openIntervals})),busy:[{id:'b',date,start:'23:45',end:'23:55',title:'x',source:'manual'}]};expect(personalAvailability(e,r)).toEqual([{date,start:'23:00',end:'23:35'},{date:next,start:'00:05',end:'01:00'}]);r.busy=[{id:'c',date:next,start:'00:05',end:'00:15',title:'x',source:'manual'}];expect(personalAvailability(e,r)).toEqual([{date,start:'23:00',end:'23:55'},{date:next,start:'00:25',end:'01:00'}])})
 it('unsubmitted_not_free and selected_subset_is_exact',()=>{const pending={...B,status:'unsubmitted' as const};expect(commonAvailability(event,[A,pending],['A','B'],1).intervals).toEqual([]);expect(commonAvailability(event,[A,pending],['A','B'],1).waiting[0].id).toBe('B');expect(commonAvailability(event,[A,pending],['A'],1).intervals).toEqual(A.availability);expect(commonAvailability(event,[A],[],1).intervals).toEqual([]);expect(commonAvailability(event,[A],['missing'],1).waiting[0].id).toBe('missing')})
 it('schedule_change_requires_reconfirmation',()=>{expect(commonAvailability(event,[{...A,status:'needs_review'}],['A'],1).waiting[0].status).toBe('needs_review')})
 it('confirmed_empty_means_unavailable',()=>{const empty=person('empty',{name:'empty',presence:[],busy:[],bufferMinutes:0});expect(empty.availability).toEqual([]);expect(commonAvailability(event,[A,empty],['A','empty'],1)).toEqual({intervals:[],waiting:[]})})
 it('dates use UTC ordinal independent of device and reject invalid calendar',()=>{expect(dateOrdinal('2026-10-04')-dateOrdinal(date)).toBe(1);expect(()=>dateOrdinal('2026-02-30')).toThrow();expect(()=>dateOrdinal('10-03')).toThrow()})
 it('does not mutate input or expose private fields',()=>{const snapshot=JSON.stringify([event,A,B]);expect(JSON.stringify(commonAvailability(event,[A,B],['A','B'],1))).not.toContain('私密');expect(JSON.stringify([event,A,B])).toBe(snapshot)})
})
